In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#ambil data accelerometer dengan range cikarang - purwakarta
akse2 = pd.read_csv("/content/drive/MyDrive/Proyek Penelitian Terapan/eksplorasi data/Dataset/EM120/Dt_Accelerometer cikarang-purwakarta.csv",delimiter=';')
akse2

,date,time,longitude1,latitude1,kecepatan1,sb_x_kiri1,sb_y_kiri1,sb_z_kiri1,sb_x_kanan1,sb_y_kanan1,...,keterangan,longitude,latitude,kecepatan,sb_x_kiri,sb_y_kiri,sb_z_kiri,sb_x_kanan,sb_y_kanan,sb_z_kanan
0,1657040400,10:35:16,107.445750,-6.551282,56.833433,2.784681,1.500215,1.952996,-0.455706,2.843078,...,NaN,107.4458,-6.5513,56.8334,2.7847,1.5002,1.9530,-0.4557,2.8431,1.4705
1,1657040400,10:35:20,107.445450,-6.550623,57.837620,3.658504,-0.226272,1.937565,1.159260,1.908970,...,NaN,107.4455,-6.5506,57.8376,3.6585,-0.2263,1.9376,1.1593,1.9090,1.9827
2,1657040400,10:35:21,107.445417,-6.550498,60.102211,4.152782,-1.223934,2.066793,4.870716,1.208530,...,NaN,107.4454,-6.5505,60.1022,4.1528,-1.2239,2.0668,4.8707,1.2085,2.0895
3,1657040400,10:35:22,107.445400,-6.550372,53.880511,3.071366,-0.391284,1.992196,-2.557408,0.180453,...,NaN,107.4454,-6.5504,53.8805,3.0714,-0.3913,1.9922,-2.5574,0.1805,1.9266
4,1657040400,10:35:29,107.445133,-6.549307,52.853449,3.967005,-1.501092,2.162447,4.284134,2.849284,...,NaN,107.4451,-6.5493,52.8534,3.9670,-1.5011,2.1624,4.2841,2.8493,2.0184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,1657040400,11:28:00,107.144683,-6.254763,57.863441,2.825338,-0.931560,1.897700,-1.927796,-3.636068,...,NaN,107.1447,-6.2548,57.8634,2.8253,-0.9316,1.8977,-1.9278,-3.6361,1.5258
568,1657040400,11:28:03,107.144267,-6.254608,58.472420,3.162350,-1.386417,1.931784,0.963172,2.213132,...,NaN,107.1443,-6.2546,58.4724,3.1624,-1.3864,1.9318,0.9632,2.2131,2.0545
569,1657040400,11:28:03,107.144270,-6.254610,55.260000,3.691323,1.442916,2.073688,-1.302851,2.872291,...,NaN,107.1443,-6.2546,55.2600,3.6913,1.4429,2.0737,-1.3029,2.8723,2.0727
570,1657040400,11:28:04,107.144117,-6.254550,57.681834,4.041780,-0.113902,2.164904,4.914484,2.786356,...,NaN,107.1441,-6.2546,57.6818,4.0418,-0.1139,2.1649,4.9145,2.7864,2.1241
571,1657040400,11:28:04,107.144117,-6.254550,54.034911,4.102389,-0.497811,2.154322,4.889952,2.384902,...,NaN,107.1441,-6.2546,54.0349,4.1024,-0.4978,2.1543,4.8900,2.3849,2.1206

In [ ]:
print(akse2['longitude1'].min())
print(akse2['longitude1'].max())      
print(akse2['latitude1'].min())
print(akse2['latitude1'].max())

107.144117
107.480167
-6.551282
-6.25455

In [ ]:
#ambil data ciremai profiling
prof = pd.read_csv("/content/drive/MyDrive/Proyek Penelitian Terapan/eksplorasi data/Dataset/BTP_Jabar/Cikarang - Purwakarta/2022080803041_GEOMETRY.csv")
prof

,MP,MPFT,SYNC_COUNT,SYNC_SAMPLE,SPEED,DIV_CODE,TRK_CLASS,POSTED_SPD,TRK_NUM,GRADIENT,...,SHORT_RPROF_MCO,LPROF_SC,RPROF_SC,LALGN_SC,RALGN_SC,TERMIX_SB,TWIST_S,TWIST_M,TWIST_L,Unnamed: 45
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239002,103.0,680.0,119.0,522.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
239003,103.0,681.0,119.0,523.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
239004,103.0,682.0,119.0,524.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
239005,103.0,683.0,119.0,525.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
239006,103.0,684.0,119.0,526.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [ ]:
unik = prof['MP'].unique()
unik

array([  0.,  43.,  44.,  45.,  46.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103.])

## Ambil data KM 84

In [ ]:
#cek index km 84
km = prof.groupby("MP")
ems = km.get_group(84).reset_index()
ems

,index,MP,MPFT,SYNC_COUNT,SYNC_SAMPLE,SPEED,DIV_CODE,TRK_CLASS,POSTED_SPD,TRK_NUM,...,SHORT_RPROF_MCO,LPROF_SC,RPROF_SC,LALGN_SC,RALGN_SC,TERMIX_SB,TWIST_S,TWIST_M,TWIST_L,Unnamed: 45
0,162322,84.0,0.0,80.0,1842.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.17,0.01,2.39,2.57,0.0,0.43,-0.22,-0.53,NaN
1,162323,84.0,1.0,80.0,1843.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.32,0.22,2.37,2.95,0.0,-0.03,0.00,-0.16,NaN
2,162324,84.0,2.0,80.0,1844.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.48,0.47,2.11,3.10,0.0,-0.16,-0.43,0.19,NaN
3,162325,84.0,3.0,80.0,1845.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.72,0.81,1.95,3.25,0.0,-0.53,-0.37,0.43,NaN
4,162326,84.0,4.0,80.0,1846.0,27.0,0.0,0.0,0.0,0.0,...,0.0,0.76,1.30,1.91,3.31,0.0,-0.47,-0.28,1.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,166317,84.0,3995.0,82.0,1837.0,49.0,0.0,0.0,0.0,0.0,...,0.0,-0.12,-1.27,-1.55,-1.74,0.0,4.31,5.36,4.84,NaN
3996,166318,84.0,3996.0,82.0,1838.0,49.0,0.0,0.0,0.0,0.0,...,0.0,-0.64,-2.53,-1.48,-1.69,0.0,4.53,5.12,4.50,NaN
3997,166319,84.0,3997.0,82.0,1839.0,49.0,0.0,0.0,0.0,0.0,...,0.0,-0.96,-3.36,-1.53,-1.83,0.0,4.43,4.93,3.66,NaN
3998,166320,84.0,3998.0,82.0,1840.0,49.0,0.0,0.0,0.0,0.0,...,0.0,-1.09,-3.91,-1.26,-1.76,0.0,4.56,4.78,3.75,NaN
3999,166321,84.0,3999.0,82.0,1841.0,49.0,0.0,0.0,0.0,0.0,...,0.0,-1.11,-4.29,-1.02,-1.63,0.0,4.09,4.53,3.75,NaN

In [ ]:
#ambil data
prof1= prof.iloc[162322:239007]
prof1

,MP,MPFT,SYNC_COUNT,SYNC_SAMPLE,SPEED,DIV_CODE,TRK_CLASS,POSTED_SPD,TRK_NUM,GRADIENT,...,SHORT_RPROF_MCO,LPROF_SC,RPROF_SC,LALGN_SC,RALGN_SC,TERMIX_SB,TWIST_S,TWIST_M,TWIST_L,Unnamed: 45
162322,84.0,0.0,80.0,1842.0,27.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.17,0.01,2.39,2.57,0.0,0.43,-0.22,-0.53,NaN
162323,84.0,1.0,80.0,1843.0,27.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.32,0.22,2.37,2.95,0.0,-0.03,0.00,-0.16,NaN
162324,84.0,2.0,80.0,1844.0,27.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.48,0.47,2.11,3.10,0.0,-0.16,-0.43,0.19,NaN
162325,84.0,3.0,80.0,1845.0,27.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.72,0.81,1.95,3.25,0.0,-0.53,-0.37,0.43,NaN
162326,84.0,4.0,80.0,1846.0,27.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.76,1.30,1.91,3.31,0.0,-0.47,-0.28,1.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239002,103.0,680.0,119.0,522.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
239003,103.0,681.0,119.0,523.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
239004,103.0,682.0,119.0,524.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
239005,103.0,683.0,119.0,525.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
239006,103.0,684.0,119.0,526.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN

In [ ]:
prof1['MP'] = prof1['MP'].astype(int)
prof1['MPFT'] = prof1['MPFT'].astype(int)
prof1['SPEED'] = prof1['SPEED'].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
prof1 = prof1.reset_index()
prof1

,index,MP,MPFT,SYNC_COUNT,SYNC_SAMPLE,SPEED,DIV_CODE,TRK_CLASS,POSTED_SPD,TRK_NUM,...,SHORT_RPROF_MCO,LPROF_SC,RPROF_SC,LALGN_SC,RALGN_SC,TERMIX_SB,TWIST_S,TWIST_M,TWIST_L,Unnamed: 45
0,162322,84,0,80.0,1842.0,27,0.0,0.0,0.0,0.0,...,0.0,0.17,0.01,2.39,2.57,0.0,0.43,-0.22,-0.53,NaN
1,162323,84,1,80.0,1843.0,27,0.0,0.0,0.0,0.0,...,0.0,0.32,0.22,2.37,2.95,0.0,-0.03,0.00,-0.16,NaN
2,162324,84,2,80.0,1844.0,27,0.0,0.0,0.0,0.0,...,0.0,0.48,0.47,2.11,3.10,0.0,-0.16,-0.43,0.19,NaN
3,162325,84,3,80.0,1845.0,27,0.0,0.0,0.0,0.0,...,0.0,0.72,0.81,1.95,3.25,0.0,-0.53,-0.37,0.43,NaN
4,162326,84,4,80.0,1846.0,27,0.0,0.0,0.0,0.0,...,0.0,0.76,1.30,1.91,3.31,0.0,-0.47,-0.28,1.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76680,239002,103,680,119.0,522.0,4,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
76681,239003,103,681,119.0,523.0,4,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
76682,239004,103,682,119.0,524.0,4,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
76683,239005,103,683,119.0,525.0,4,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN
76684,239006,103,684,119.0,526.0,4,0.0,0.0,0.0,0.0,...,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,NaN

In [ ]:
prof2 = prof1.drop(['index','TERMIX_SB','Unnamed: 45','SHORT_RPROF_MCO','SYNC_COUNT','SYNC_SAMPLE','TRK_NUM',	'GRADIENT',	'ALD','DIV_CODE',	'TRK_CLASS',	'POSTED_SPD',	'LPROF31',
                    'TBS',	'WARP_62',	'SHORT_LPROF_MCO',	'LPROF_SC',	'RPROF_SC',	'LALGN_SC',	'RALGN_SC',	'TWIST_S','TWIST_M',	'TWIST_L','LPROF124',	'RPROF31','CTS',	'RCTS',	'ISR1',	'ISR2',
                    'RPROF124',	'LALIGN31','LALIGN124',	'RALIGN31','RALIGN124'], axis=1)
prof2

,MP,MPFT,SPEED,LPROF62,RPROF62,LALIGN62,RALIGN62,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE
0,84,0,27,1.36,1.64,1.41,2.41,1066.94,0.0,0.06,0.19,-0.12,0.21
1,84,1,27,1.56,1.89,1.51,2.97,1066.54,0.0,0.43,0.50,-0.12,0.22
2,84,2,27,1.68,2.17,1.33,3.28,1066.14,0.0,0.16,0.19,-0.12,0.20
3,84,3,27,2.09,2.80,1.31,3.66,1065.84,0.0,0.19,0.19,-0.12,0.17
4,84,4,27,2.14,3.46,1.44,3.73,1065.74,0.0,-0.12,-0.19,-0.12,0.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76680,103,680,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00
76681,103,681,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00
76682,103,682,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00
76683,103,683,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00
76684,103,684,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00

In [ ]:
#menggabungkan LPROF62 dengan RPROF62 dan LALIGN62 dengan RALIGN62
prof2['PROF'] = (prof2['LPROF62'] + prof2['RPROF62'])/2
prof2['ALIGN'] = (prof2['LALIGN62'] + prof2['RALIGN62'])/2

#mengurangi gauge dengan 1067 mm
prof2['Lebar Sepur'] = prof2['GAUGE'] - 1067

In [ ]:
prof2

,MP,MPFT,SPEED,LPROF62,RPROF62,LALIGN62,RALIGN62,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,84,0,27,1.36,1.64,1.41,2.41,1066.94,0.0,0.06,0.19,-0.12,0.21,1.500,1.910,-0.06
1,84,1,27,1.56,1.89,1.51,2.97,1066.54,0.0,0.43,0.50,-0.12,0.22,1.725,2.240,-0.46
2,84,2,27,1.68,2.17,1.33,3.28,1066.14,0.0,0.16,0.19,-0.12,0.20,1.925,2.305,-0.86
3,84,3,27,2.09,2.80,1.31,3.66,1065.84,0.0,0.19,0.19,-0.12,0.17,2.445,2.485,-1.16
4,84,4,27,2.14,3.46,1.44,3.73,1065.74,0.0,-0.12,-0.19,-0.12,0.21,2.800,2.585,-1.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76680,103,680,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76681,103,681,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76682,103,682,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76683,103,683,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76684,103,684,4,0.00,0.00,0.00,0.00,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25

In [ ]:
prof2 = prof2.drop(['LPROF62',	'RPROF62',	'LALIGN62',	'RALIGN62'],axis=1)
prof2

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,84,0,27,1066.94,0.0,0.06,0.19,-0.12,0.21,1.500,1.910,-0.06
1,84,1,27,1066.54,0.0,0.43,0.50,-0.12,0.22,1.725,2.240,-0.46
2,84,2,27,1066.14,0.0,0.16,0.19,-0.12,0.20,1.925,2.305,-0.86
3,84,3,27,1065.84,0.0,0.19,0.19,-0.12,0.17,2.445,2.485,-1.16
4,84,4,27,1065.74,0.0,-0.12,-0.19,-0.12,0.21,2.800,2.585,-1.26
...,...,...,...,...,...,...,...,...,...,...,...,...
76680,103,680,4,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76681,103,681,4,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76682,103,682,4,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76683,103,683,4,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25
76684,103,684,4,1065.75,0.0,-7.32,0.00,-0.05,0.00,0.000,0.000,-1.25

In [ ]:
print(prof2.columns)

Index(['MP', 'MPFT', 'SPEED', 'GAUGE', 'GAUGE2', 'XLEVEL', 'XLEVEL_RATE',
       'CURVE', 'CURVE_RATE', 'PROF', 'ALIGN', 'Lebar Sepur'],
      dtype='object')

## ambil data ciremai km 84

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(84)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,84,0,27,1066.94,0.0,0.06,0.19,-0.12,0.21,1.500,1.910,-0.06
1,84,1,27,1066.54,0.0,0.43,0.50,-0.12,0.22,1.725,2.240,-0.46
2,84,2,27,1066.14,0.0,0.16,0.19,-0.12,0.20,1.925,2.305,-0.86
3,84,3,27,1065.84,0.0,0.19,0.19,-0.12,0.17,2.445,2.485,-1.16
4,84,4,27,1065.74,0.0,-0.12,-0.19,-0.12,0.21,2.800,2.585,-1.26
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,84,3995,49,1065.74,0.0,-77.83,0.74,-2.36,0.10,-0.460,-2.865,-1.26
3996,84,3996,49,1065.74,0.0,-76.96,1.64,-2.36,0.13,-1.150,-2.740,-1.26
3997,84,3997,49,1065.84,0.0,-76.47,2.17,-2.36,0.13,-1.425,-2.820,-1.16
3998,84,3998,49,1066.05,0.0,-76.09,2.57,-2.36,0.10,-1.515,-2.735,-0.95
3999,84,3999,49,1066.15,0.0,-75.50,3.19,-2.36,0.04,-1.480,-2.455,-0.85

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,84,1968,21,1094.93,0.0,78.33,-1.05,8.42,-0.17,-7.420,0.000,27.93
1969,84,1969,21,1094.93,0.0,78.45,-1.09,8.42,-0.15,-5.775,0.000,27.93
1970,84,1970,21,1095.04,0.0,78.17,-1.55,8.42,-0.13,-3.690,0.000,28.04
1971,84,1971,21,1095.04,0.0,78.33,-1.52,8.42,-0.12,-1.945,0.000,28.04
1972,84,1972,21,1095.04,0.0,78.73,-1.27,8.42,-0.06,0.620,0.000,28.04
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,84,2619,25,1082.63,0.0,66.73,-2.02,4.79,-0.42,8.820,-4.505,15.63
2620,84,2620,25,1082.14,0.0,66.88,-1.86,4.80,-0.43,9.200,-4.770,15.14
2621,84,2621,25,1081.53,0.0,66.70,-2.02,4.80,-0.39,9.125,-5.240,14.53
2622,84,2622,25,1081.14,0.0,67.07,-1.61,4.80,-0.42,8.430,-5.725,14.14
2623,84,2623,25,1081.04,0.0,67.10,-1.55,4.81,-0.40,8.040,-6.085,14.04

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 5.41
Listringan 4.91
Lebar Sepur 0.73
pertinggian 3.77
Angkatan 7.32
Listringan 20.3
Lebar Sepur 4.48
pertinggian 7.43
Angkatan 9.11
Listringan 0.0
Lebar Sepur 11.97
pertinggian 32.21
Angkatan 11.4
Listringan 9.7
Lebar Sepur 9.95
pertinggian 28.52

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[84.000,84.200,84.400,84.600],
      'KM_Akhir':[84.200,84.400,84.600,84.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem84 = pd.DataFrame(seg)
df_cem84

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     84.0      84.2      5.41        4.91         0.73         3.77
1     84.2      84.4      7.32       20.30         4.48         7.43
2     84.4      84.6      9.11        0.00        11.97        32.21
3     84.6      84.8     11.40        9.70         9.95        28.52

## ambil data ciremai km 85

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(85).reset_index()
cem = cem.drop(['index'],axis=1)
cem
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,85,0,49,1066.24,0.0,-75.32,3.41,-2.36,0.05,-0.930,-2.235,-0.76
1,85,1,49,1066.24,0.0,-74.82,3.94,-2.36,0.06,-0.375,-1.935,-0.76
2,85,2,49,1066.05,0.0,-74.42,4.34,-2.36,0.09,0.480,-1.680,-0.95
3,85,3,49,1065.94,0.0,-74.17,4.59,-2.36,0.10,1.120,-1.550,-1.06
4,85,4,49,1065.64,0.0,-74.17,4.62,-2.36,0.10,1.775,-1.220,-1.36
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,85,3995,75,1065.65,0.0,-0.87,-2.67,0.01,0.01,-3.475,-1.890,-1.35
3996,85,3996,75,1065.65,0.0,-0.09,-1.89,0.01,0.02,-5.300,-1.975,-1.35
3997,85,3997,75,1065.85,0.0,0.56,-1.21,0.01,0.00,-7.320,-2.235,-1.15
3998,85,3998,75,1065.95,0.0,0.81,-0.96,0.01,-0.02,-9.200,-2.290,-1.05
3999,85,3999,75,1066.05,0.0,2.02,0.28,0.01,-0.02,-11.045,-2.390,-0.95

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,85,1968,65,1065.74,0.0,-6.91,-1.18,-0.44,-0.29,-13.510,3.610,-1.26
1969,85,1969,65,1065.84,0.0,-6.45,-1.02,-0.44,-0.27,-13.840,3.935,-1.16
1970,85,1970,65,1065.84,0.0,-5.95,-0.84,-0.44,-0.27,-13.640,4.070,-1.16
1971,85,1971,66,1066.44,0.0,-5.89,-1.12,-0.43,-0.31,-13.650,4.390,-0.56
1972,85,1972,66,1066.25,0.0,-5.15,-0.68,-0.43,-0.29,-13.230,4.055,-0.75
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,85,2619,69,1065.74,0.0,-5.83,-0.74,-0.04,0.06,1.825,-1.245,-1.26
2620,85,2620,69,1065.64,0.0,-5.58,-0.50,-0.04,0.04,1.710,-1.260,-1.36
2621,85,2621,69,1065.84,0.0,-5.80,-0.68,-0.04,0.05,1.500,-1.210,-1.16
2622,85,2622,69,1065.84,0.0,-5.95,-0.84,-0.04,0.03,1.470,-1.015,-1.16
2623,85,2623,69,1065.84,0.0,-5.80,-0.65,-0.04,0.03,1.630,-0.770,-1.16

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 8.74
Listringan 4.5
Lebar Sepur 1.83
pertinggian 5.92
Angkatan 7.43
Listringan 4.47
Lebar Sepur 1.3
pertinggian 16.66
Angkatan 7.04
Listringan 3.15
Lebar Sepur 1.22
pertinggian 28.84
Angkatan 7.38
Listringan 3.13
Lebar Sepur 1.48
pertinggian 7.16

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[85.000,85.200,85.400,85.600],
      'KM_Akhir':[85.200,85.400,85.600,85.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem85 = pd.DataFrame(seg)
df_cem85

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     85.0      85.2      8.74        4.50         1.83         5.92
1     85.2      85.4      7.43        4.47         1.30        16.66
2     85.4      85.6      7.04        3.15         1.22        28.84
3     85.6      85.8      7.38        3.13         1.48         7.16

## ambil data ciremai km 86

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(86).reset_index()
cem = cem.drop(['index'],axis=1)
cem
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,86,0,75,1066.05,0.0,2.05,0.34,0.01,-0.03,-12.480,-2.510,-0.95
1,86,1,75,1066.05,0.0,2.91,1.21,0.01,-0.02,-13.735,-2.525,-0.95
2,86,2,75,1065.94,0.0,2.91,1.21,0.01,-0.06,-14.780,-2.555,-1.06
3,86,3,75,1066.44,0.0,3.35,1.67,0.01,-0.04,-15.565,-2.765,-0.56
4,86,4,75,1066.64,0.0,3.44,1.80,0.01,0.02,-15.935,-2.780,-0.36
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,86,3995,80,1066.84,0.0,-10.85,0.06,0.02,0.08,-4.250,-2.870,-0.16
3996,86,3996,80,1066.94,0.0,-10.48,0.37,0.01,0.09,-3.310,-3.035,-0.06
3997,86,3997,80,1067.05,0.0,-9.61,1.18,0.01,0.11,-2.485,-3.060,0.05
3998,86,3998,80,1067.15,0.0,-9.09,1.64,0.01,0.17,-1.595,-2.930,0.15
3999,86,3999,80,1067.35,0.0,-8.56,2.11,0.01,0.18,-1.250,-2.935,0.35

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,86,1968,80,1065.94,0.0,-0.93,-0.90,0.0,0.06,-5.765,2.630,-1.06
1969,86,1969,80,1065.95,0.0,-0.59,-0.59,0.0,0.07,-5.975,2.530,-1.05
1970,86,1970,80,1065.95,0.0,-1.02,-1.09,0.0,0.03,-6.330,2.585,-1.05
1971,86,1971,80,1066.15,0.0,-1.27,-1.36,0.0,0.01,-5.825,2.840,-0.85
1972,86,1972,80,1066.45,0.0,-1.18,-1.33,0.0,0.01,-5.685,3.195,-0.55
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,86,2619,80,1066.26,0.0,-1.86,0.16,0.0,-0.03,5.870,-1.070,-0.74
2620,86,2620,80,1066.26,0.0,-2.17,-0.16,0.0,-0.02,5.225,-0.850,-0.74
2621,86,2621,80,1065.95,0.0,-2.26,-0.25,0.0,-0.01,4.740,-0.900,-1.05
2622,86,2622,80,1065.85,0.0,-2.51,-0.50,0.0,0.00,4.450,-0.800,-1.15
2623,86,2623,80,1065.65,0.0,-2.14,-0.12,0.0,0.02,3.965,-0.570,-1.35

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 6.41
Listringan 2.19
Lebar Sepur 1.42
pertinggian 2.0
Angkatan 3.63
Listringan 2.04
Lebar Sepur 1.1
pertinggian 29.08
Angkatan 5.98
Listringan 2.64
Lebar Sepur 1.05
pertinggian 27.06
Angkatan 5.77
Listringan 1.9
Lebar Sepur 1.83
pertinggian 2.86

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[86.000,86.200,86.400,86.600],
      'KM_Akhir':[86.200,86.400,86.600,86.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem86 = pd.DataFrame(seg)
df_cem86

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     86.0      86.2      6.41        2.19         1.42         2.00
1     86.2      86.4      3.63        2.04         1.10        29.08
2     86.4      86.6      5.98        2.64         1.05        27.06
3     86.6      86.8      5.77        1.90         1.83         2.86

## ambil data ciremai km 87

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(87).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,87,0,80,1067.05,0.0,-8.06,2.51,0.01,0.19,-1.315,-2.960,0.05
1,87,1,80,1066.84,0.0,-8.03,2.48,0.01,0.21,-1.560,-2.670,-0.16
2,87,2,80,1066.84,0.0,-7.91,2.51,0.01,0.23,-2.245,-2.415,-0.16
3,87,3,80,1066.64,0.0,-7.57,2.79,0.00,0.18,-2.800,-2.285,-0.36
4,87,4,80,1066.54,0.0,-7.35,2.91,0.00,0.13,-3.300,-2.070,-0.46
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,87,3995,81,1070.13,0.0,43.63,1.52,1.30,0.78,1.560,-1.185,3.13
3996,87,3996,81,1070.03,0.0,43.44,1.64,1.29,0.76,1.905,-1.080,3.03
3997,87,3997,81,1069.84,0.0,43.44,1.95,1.29,0.75,2.340,-1.095,2.84
3998,87,3998,81,1070.04,0.0,42.73,1.55,1.28,0.71,2.370,-0.885,3.04
3999,87,3999,81,1070.04,0.0,42.57,1.71,1.28,0.70,2.745,-0.975,3.04

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,87,1968,80,1073.74,0.0,58.64,-1.71,1.64,-0.71,-8.925,5.155,6.74
1969,87,1969,80,1073.53,0.0,59.19,-1.46,1.64,-0.72,-8.285,5.040,6.53
1970,87,1970,80,1073.44,0.0,59.88,-1.05,1.65,-0.70,-7.900,4.750,6.44
1971,87,1971,80,1073.34,0.0,60.62,-0.59,1.66,-0.71,-7.535,4.585,6.34
1972,87,1972,80,1073.44,0.0,61.52,0.03,1.66,-0.71,-7.625,4.240,6.44
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,87,2619,79,1073.84,0.0,99.94,-0.62,2.97,0.12,-1.805,1.005,6.84
2620,87,2620,79,1073.74,0.0,99.69,-0.87,2.97,0.15,-0.850,1.000,6.74
2621,87,2621,79,1073.74,0.0,99.57,-0.96,2.96,0.17,0.170,1.050,6.74
2622,87,2622,79,1074.14,0.0,99.47,-1.05,2.96,0.19,0.975,1.145,7.14
2623,87,2623,79,1074.74,0.0,99.44,-1.09,2.96,0.17,0.940,1.175,7.74

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 4.8
Listringan 2.89
Lebar Sepur 1.47
pertinggian 3.26
Angkatan 4.03
Listringan 2.36
Lebar Sepur 1.07
pertinggian 3.27
Angkatan 7.47
Listringan 3.58
Lebar Sepur 2.16
pertinggian 18.64
Angkatan 4.64
Listringan 4.08
Lebar Sepur 1.49
pertinggian 13.16

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[87.000,87.200,87.400,87.600],
      'KM_Akhir':[87.200,87.400,87.600,87.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem87 = pd.DataFrame(seg)
df_cem87

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     87.0      87.2      4.80        2.89         1.47         3.26
1     87.2      87.4      4.03        2.36         1.07         3.27
2     87.4      87.6      7.47        3.58         2.16        18.64
3     87.6      87.8      4.64        4.08         1.49        13.16

## ambil data ciremai km 88

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(88).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,88,0,81,1070.03,0.0,42.23,1.64,1.27,0.67,3.100,-1.070,3.03
1,88,1,81,1069.93,0.0,42.02,1.74,1.26,0.68,3.370,-0.945,2.93
2,88,2,81,1069.93,0.0,41.33,1.33,1.26,0.68,3.080,-0.830,2.93
3,88,3,81,1070.03,0.0,40.87,1.18,1.25,0.71,2.745,-0.755,3.03
4,88,4,81,1070.13,0.0,40.74,1.33,1.25,0.71,1.995,-0.435,3.13
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,88,3995,73,1077.05,0.0,-101.46,4.16,-4.06,-0.13,2.530,-5.685,10.05
3996,88,3996,73,1077.34,0.0,-101.43,4.25,-4.05,-0.13,3.660,-4.845,10.34
3997,88,3997,73,1077.44,0.0,-101.18,4.53,-4.05,-0.11,4.675,-4.170,10.44
3998,88,3998,73,1077.35,0.0,-102.17,3.60,-4.05,-0.03,4.800,-3.680,10.35
3999,88,3999,72,1077.44,0.0,-102.51,3.32,-4.05,0.01,4.975,-3.250,10.44

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,88,1968,77,1064.74,0.0,-85.52,0.84,-2.13,-0.32,0.245,4.505,-2.26
1969,88,1969,77,1064.94,0.0,-85.30,1.09,-2.13,-0.30,-0.400,4.465,-2.06
1970,88,1970,77,1065.15,0.0,-85.86,0.53,-2.13,-0.24,-0.785,4.480,-1.85
1971,88,1971,77,1065.35,0.0,-85.64,0.78,-2.13,-0.21,-1.055,4.715,-1.65
1972,88,1972,77,1065.45,0.0,-85.83,0.59,-2.12,-0.17,-1.180,4.855,-1.55
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,88,2619,74,1064.94,0.0,0.84,1.18,0.00,-0.08,-1.305,0.145,-2.06
2620,88,2620,74,1064.94,0.0,0.53,0.96,0.00,-0.09,-0.930,0.255,-2.06
2621,88,2621,74,1064.94,0.0,0.90,1.40,0.00,-0.09,-0.525,0.325,-2.06
2622,88,2622,74,1064.84,0.0,1.02,1.61,0.00,-0.06,-0.125,0.425,-2.16
2623,88,2623,74,1064.94,0.0,1.43,2.11,0.00,-0.07,-0.075,0.700,-2.06

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 7.98
Listringan 3.23
Lebar Sepur 2.07
pertinggian 11.67
Angkatan 5.69
Listringan 3.57
Lebar Sepur 1.24
pertinggian 42.01
Angkatan 5.0
Listringan 3.15
Lebar Sepur 1.43
pertinggian 4.14
Angkatan 3.03
Listringan 3.38
Lebar Sepur 1.69
pertinggian 36.68

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[88.000,88.200,88.400,88.600],
      'KM_Akhir':[88.200,88.400,88.600,88.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem88 = pd.DataFrame(seg)
df_cem88

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     88.0      88.2      7.98        3.23         2.07        11.67
1     88.2      88.4      5.69        3.57         1.24        42.01
2     88.4      88.6      5.00        3.15         1.43         4.14
3     88.6      88.8      3.03        3.38         1.69        36.68

## ambil data ciremai km 89

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(89).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,89,0,72,1077.34,0.0,-102.73,3.16,-4.05,0.01,4.590,-2.915,10.34
1,89,1,72,1077.14,0.0,-103.26,2.73,-4.05,0.05,3.755,-2.610,10.14
2,89,2,72,1077.04,0.0,-103.88,2.17,-4.05,0.15,2.890,-2.400,10.04
3,89,3,72,1076.74,0.0,-104.34,1.77,-4.06,0.20,2.015,-2.265,9.74
4,89,4,72,1076.74,0.0,-105.09,1.09,-4.06,0.22,1.205,-1.925,9.74
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,89,3995,73,1072.05,0.0,59.72,-0.93,1.23,-0.42,-3.910,1.585,5.05
3996,89,3996,73,1072.35,0.0,60.03,-0.90,1.24,-0.46,-4.295,1.815,5.35
3997,89,3997,73,1072.45,0.0,60.16,-1.09,1.24,-0.48,-5.000,1.810,5.45
3998,89,3998,73,1072.45,0.0,60.31,-1.24,1.25,-0.49,-5.635,2.355,5.45
3999,89,3999,73,1072.15,0.0,60.90,-0.96,1.25,-0.51,-6.370,2.575,5.15

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,89,1968,71,1066.45,0.0,87.94,-0.09,2.15,-0.19,4.050,2.910,-0.55
1969,89,1969,70,1066.36,0.0,88.34,0.34,2.15,-0.15,4.060,2.755,-0.64
1970,89,1970,70,1066.26,0.0,88.31,0.37,2.15,-0.12,4.415,2.520,-0.74
1971,89,1971,70,1065.85,0.0,87.97,0.09,2.15,-0.04,4.380,2.180,-1.15
1972,89,1972,70,1065.85,0.0,87.69,-0.12,2.15,-0.08,4.480,1.805,-1.15
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,89,2619,71,1064.95,0.0,92.19,1.09,1.95,0.20,4.005,0.285,-2.05
2620,89,2620,71,1064.75,0.0,92.40,1.33,1.95,0.14,4.235,0.680,-2.25
2621,89,2621,71,1064.55,0.0,92.47,1.46,1.95,0.15,4.545,0.705,-2.45
2622,89,2622,71,1064.26,0.0,92.84,1.89,1.95,0.14,4.830,0.955,-2.74
2623,89,2623,71,1064.15,0.0,93.24,2.36,1.95,0.10,5.185,1.295,-2.85

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 5.23
Listringan 4.23
Lebar Sepur 4.7
pertinggian 45.33
Angkatan 7.98
Listringan 3.02
Lebar Sepur 0.71
pertinggian 4.35
Angkatan 5.37
Listringan 2.75
Lebar Sepur 0.88
pertinggian 38.16
Angkatan 4.68
Listringan 3.1
Lebar Sepur 1.62
pertinggian 3.52

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[89.000,89.200,89.400,89.600],
      'KM_Akhir':[89.200,89.400,89.600,89.800],
      'Angkatan' : [5.41,7.32,9.11,11.4],
      'Lestrengan' : [4.91,20.3,0.0,9.7],
      'Lebar Sepur' : [0.73,4.48,11.97,9.95],
      'Pertinggian' :[3.77,7.43,32.21,28.52]}

df_cem89 = pd.DataFrame(seg)
df_cem89

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     89.0      89.2      5.41        4.91         0.73         3.77
1     89.2      89.4      7.32       20.30         4.48         7.43
2     89.4      89.6      9.11        0.00        11.97        32.21
3     89.6      89.8     11.40        9.70         9.95        28.52

## ambil data ciremai km 90

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(90).reset_index()
cem = cem.drop(['index'],axis=1).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,90,0,73,1071.74,0.0,61.27,-0.90,1.26,-0.58,-6.995,2.690,4.74
1,90,1,73,1071.54,0.0,61.83,-0.65,1.26,-0.63,-7.415,2.575,4.54
2,90,2,73,1071.15,0.0,61.89,-0.90,1.27,-0.62,-7.745,2.480,4.15
3,90,3,73,1070.84,0.0,62.54,-0.56,1.27,-0.64,-7.975,2.395,3.84
4,90,4,73,1070.74,0.0,62.88,-0.53,1.28,-0.68,-7.720,2.240,3.74
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,90,3995,73,1081.63,0.0,103.94,4.03,3.68,0.16,3.010,-2.745,14.63
3996,90,3996,73,1081.53,0.0,103.72,4.00,3.68,0.14,3.045,-3.020,14.53
3997,90,3997,73,1081.33,0.0,103.16,3.63,3.67,0.11,3.360,-2.970,14.33
3998,90,3998,73,1081.14,0.0,102.67,3.32,3.67,0.06,3.135,-3.095,14.14
3999,90,3999,73,1080.94,0.0,102.60,3.41,3.67,0.03,2.325,-3.060,13.94

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,90,1968,73,1081.14,0.0,-114.11,-0.34,-4.38,0.08,-5.310,-4.760,14.14
1969,90,1969,73,1081.64,0.0,-113.74,-0.03,-4.38,0.04,-4.835,-4.820,14.64
1970,90,1970,73,1082.14,0.0,-113.61,0.06,-4.38,-0.04,-3.905,-4.770,15.14
1971,90,1971,73,1082.54,0.0,-113.77,-0.12,-4.38,-0.06,-3.330,-4.550,15.54
1972,90,1972,73,1083.05,0.0,-113.77,-0.19,-4.38,-0.08,-2.055,-4.230,16.05
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,90,2619,71,1071.15,0.0,-11.22,-1.09,-1.01,-0.82,1.560,-2.320,4.15
2620,90,2620,71,1071.54,0.0,-11.19,-1.33,-1.00,-0.84,1.985,-2.450,4.54
2621,90,2621,71,1071.94,0.0,-10.82,-1.24,-1.00,-0.86,2.340,-2.415,4.94
2622,90,2622,71,1072.24,0.0,-10.73,-1.43,-0.99,-0.87,2.295,-2.450,5.24
2623,90,2623,71,1072.44,0.0,-10.17,-1.15,-0.98,-0.88,2.260,-2.465,5.44

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi1p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 3.71
Listringan 1.74
Lebar Sepur 1.5
pertinggian 26.48
Angkatan 7.98
Listringan 2.25
Lebar Sepur 2.12
pertinggian 4.87
Angkatan 6.64
Listringan 3.55
Lebar Sepur 4.76
pertinggian 44.53
Angkatan 5.28
Listringan 3.62
Lebar Sepur 3.91
pertinggian 31.32

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[90.000,90.200,90.400,90.600],
      'KM_Akhir':[90.200,90.400,90.600,90.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem90 = pd.DataFrame(seg)
df_cem90

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     90.0      90.2      4.95        1.74         1.50        26.48
1     90.2      90.4      7.98        2.25         2.12         4.87
2     90.4      90.6      6.64        3.55         4.76        44.53
3     90.6      90.8      5.28        3.62         3.91        31.32

## ambil data ciremai km 91

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(91).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,91,0,73,1080.84,0.0,102.17,3.16,3.67,0.02,1.480,-2.805,13.84
1,91,1,73,1080.84,0.0,102.14,3.32,3.67,0.01,0.215,-2.760,13.84
2,91,2,73,1080.63,0.0,101.18,2.54,3.67,0.01,-0.855,-2.370,13.63
3,91,3,73,1080.53,0.0,101.02,2.54,3.67,0.00,-2.005,-2.200,13.53
4,91,4,73,1080.63,0.0,100.65,2.36,3.67,0.00,-2.745,-2.085,13.63
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,91,3995,73,1075.15,0.0,-93.30,-2.79,-3.99,0.38,-7.970,-5.165,8.15
3996,91,3996,73,1075.74,0.0,-94.17,-3.38,-4.00,0.39,-9.185,-6.015,8.74
3997,91,3997,73,1076.35,0.0,-95.38,-4.31,-4.00,0.32,-9.840,-6.630,9.35
3998,91,3998,73,1077.04,0.0,-96.03,-4.68,-4.00,0.27,-9.925,-7.035,10.04
3999,91,3999,73,1077.34,0.0,-94.67,-3.04,-4.00,0.23,-10.435,-6.855,10.34

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,91,1968,71,1063.45,0.0,68.68,0.96,1.90,0.86,2.120,-2.670,-3.55
1969,91,1969,71,1063.45,0.0,68.62,1.24,1.89,0.81,1.755,-2.055,-3.55
1970,91,1970,71,1063.64,0.0,68.03,0.99,1.89,0.82,1.375,-1.580,-3.36
1971,91,1971,71,1063.94,0.0,67.66,0.93,1.88,0.81,0.990,-1.300,-3.06
1972,91,1972,71,1064.25,0.0,67.29,0.90,1.87,0.83,0.840,-0.995,-2.75
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,91,2619,73,1064.65,0.0,3.19,-1.77,0.00,-0.10,-0.670,0.735,-2.35
2620,91,2620,73,1064.65,0.0,3.57,-1.40,0.00,-0.05,-1.125,0.660,-2.35
2621,91,2621,73,1064.85,0.0,3.35,-1.61,0.00,-0.06,-1.030,0.620,-2.15
2622,91,2622,73,1064.75,0.0,3.50,-1.46,0.00,-0.10,-1.445,0.325,-2.25
2623,91,2623,73,1065.25,0.0,3.84,-1.12,0.00,-0.11,-1.670,0.195,-1.75

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 5.94
Listringan 4.99
Lebar Sepur 5.3
pertinggian 33.72
Angkatan 2.85
Listringan 2.82
Lebar Sepur 3.08
pertinggian 40.29
Angkatan 3.17
Listringan 2.67
Lebar Sepur 2.99
pertinggian 9.98
Angkatan 3.18
Listringan 2.51
Lebar Sepur 1.28
pertinggian 20.59

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[91.000,91.200,91.400,91.600],
      'KM_Akhir':[91.200,91.400,91.600,91.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem91 = pd.DataFrame(seg)
df_cem91

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     91.0      91.2      5.94        4.99         5.30        33.72
1     91.2      91.4      2.85        2.82         3.08        40.29
2     91.4      91.6      3.17        2.67         2.99         9.98
3     91.6      91.8      3.18        2.51         1.28        20.59

## ambil data ciremai km 92

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(92).reset_index()
cem = cem.drop(['index'],axis=1)
cem
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,92,0,73,1077.54,0.0,-93.49,-1.58,-4.01,0.28,-10.170,-6.280,10.54
1,92,1,74,1077.24,0.0,-93.21,-1.02,-4.01,0.29,-9.425,-5.765,10.24
2,92,2,74,1076.94,0.0,-92.62,-0.16,-4.01,0.30,-8.310,-5.170,9.94
3,92,3,74,1077.05,0.0,-93.02,-0.28,-4.02,0.35,-7.220,-4.520,10.05
4,92,4,74,1076.74,0.0,-93.02,0.00,-4.02,0.40,-6.220,-3.840,9.74
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,92,3995,77,1065.64,0.0,0.43,-3.13,-0.03,0.07,-8.710,0.595,-1.36
3996,92,3996,77,1065.74,0.0,0.62,-2.95,-0.03,0.08,-8.295,0.370,-1.26
3997,92,3997,77,1065.74,0.0,1.21,-2.36,-0.03,0.04,-7.725,0.630,-1.26
3998,92,3998,77,1065.94,0.0,1.36,-2.20,-0.03,0.00,-7.145,0.820,-1.06
3999,92,3999,77,1065.94,0.0,1.24,-2.29,-0.03,0.01,-6.180,0.935,-1.06

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,92,1968,72,1072.24,0.0,105.27,-0.34,2.92,-0.29,3.935,-3.085,5.24
1969,92,1969,72,1071.94,0.0,104.87,-0.71,2.92,-0.28,3.000,-2.515,4.94
1970,92,1970,72,1071.64,0.0,105.30,-0.25,2.92,-0.28,1.680,-2.160,4.64
1971,92,1971,72,1071.55,0.0,105.64,0.12,2.92,-0.33,0.595,-1.500,4.55
1972,92,1972,72,1071.45,0.0,105.55,0.06,2.93,-0.38,-0.510,-1.530,4.45
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,92,2619,73,1069.14,0.0,-0.50,-2.33,0.09,0.41,-0.120,-3.075,2.14
2620,92,2620,73,1068.94,0.0,-0.06,-1.74,0.08,0.45,-0.515,-2.750,1.94
2621,92,2621,73,1068.84,0.0,-0.56,-2.08,0.08,0.46,-0.740,-3.160,1.84
2622,92,2622,73,1068.74,0.0,-0.68,-2.02,0.07,0.46,-0.945,-2.915,1.74
2623,92,2623,73,1068.74,0.0,-1.12,-2.29,0.07,0.48,-1.125,-3.065,1.74

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 5.37
Listringan 4.55
Lebar Sepur 1.64
pertinggian 10.09
Angkatan 5.61
Listringan 3.75
Lebar Sepur 2.23
pertinggian 35.64
Angkatan 8.34
Listringan 7.58
Lebar Sepur 1.86
pertinggian 10.34
Angkatan 3.63
Listringan 3.16
Lebar Sepur 2.41
pertinggian 36.4

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[92.000,92.200,92.400,92.600],
      'KM_Akhir':[92.200,92.400,92.600,92.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem92 = pd.DataFrame(seg)
df_cem92

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     92.0      92.2      5.37        4.55         1.64        10.09
1     92.2      92.4      5.61        3.75         2.23        35.64
2     92.4      92.6      8.34        7.58         1.86        10.34
3     92.6      92.8      3.63        3.16         2.41        36.40

## ambil data ciremai km 93

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(93).reset_index()
cem = cem.drop(['index'],axis=1)
cem
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,93,0,77,1066.15,0.0,1.67,-1.86,-0.03,0.01,-5.030,0.790,-0.85
1,93,1,77,1066.25,0.0,1.74,-1.80,-0.03,0.01,-4.110,0.640,-0.75
2,93,2,77,1066.24,0.0,1.92,-1.61,-0.04,0.06,-2.900,0.665,-0.76
3,93,3,77,1066.14,0.0,1.95,-1.55,-0.04,0.05,-1.860,0.585,-0.86
4,93,4,77,1066.34,0.0,2.14,-1.36,-0.04,0.09,-1.325,0.305,-0.66
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,93,3995,77,1065.14,0.0,67.97,1.89,1.76,0.08,-3.360,-0.465,-1.86
3996,93,3996,77,1065.34,0.0,68.06,1.95,1.76,0.09,-3.230,-0.475,-1.66
3997,93,3997,77,1065.54,0.0,67.72,1.61,1.76,0.00,-3.005,-0.695,-1.46
3998,93,3998,77,1065.74,0.0,67.97,1.86,1.76,-0.01,-2.935,-0.780,-1.26
3999,93,3999,77,1065.84,0.0,68.00,1.86,1.76,0.00,-2.595,-0.900,-1.16

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,93,1968,79,1067.24,0.0,1.55,-0.09,-0.04,-0.05,1.785,0.065,0.24
1969,93,1969,79,1067.15,0.0,1.43,-0.22,-0.04,-0.05,1.915,0.055,0.15
1970,93,1970,79,1067.25,0.0,1.46,-0.19,-0.04,-0.02,1.710,-0.185,0.25
1971,93,1971,79,1067.34,0.0,1.46,-0.19,-0.04,-0.01,1.515,0.100,0.34
1972,93,1972,79,1067.44,0.0,1.43,-0.22,-0.04,-0.03,1.305,-0.345,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,93,2619,77,1066.84,0.0,-1.15,0.25,-0.03,-0.12,-3.385,-0.365,-0.16
2620,93,2620,77,1067.05,0.0,-0.81,0.59,-0.03,-0.11,-3.255,-0.445,0.05
2621,93,2621,77,1067.34,0.0,-0.65,0.74,-0.03,-0.11,-2.730,-0.370,0.34
2622,93,2622,77,1067.44,0.0,-0.93,0.47,-0.03,-0.10,-2.410,-0.385,0.44
2623,93,2623,77,1067.54,0.0,-0.93,0.50,-0.03,-0.09,-1.300,-0.465,0.54

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 5.22
Listringan 2.92
Lebar Sepur 0.96
pertinggian 2.09
Angkatan 4.24
Listringan 2.13
Lebar Sepur 1.58
pertinggian 2.17
Angkatan 3.25
Listringan 1.49
Lebar Sepur 0.96
pertinggian 1.97
Angkatan 1.99
Listringan 1.89
Lebar Sepur 1.16
pertinggian 1.03

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[93.000,93.200,93.400,93.600],
      'KM_Akhir':[93.200,93.400,93.600,93.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem93 = pd.DataFrame(seg)
df_cem93

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     93.0      93.2      5.22        2.92         0.96         2.09
1     93.2      93.4      4.24        2.13         1.58         2.17
2     93.4      93.6      3.25        1.49         0.96         1.97
3     93.6      93.8      1.99        1.89         1.16         1.03

## ambil data ciremai km 94

In [ ]:
#ambil data 1 km ciremai
km = prof2.groupby("MP")
cem = km.get_group(94).reset_index()
cem = cem.drop(['index'],axis=1)
cem

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
0,94,0,77,1066.05,0.0,67.81,1.67,1.76,0.00,-2.145,-1.085,-0.95
1,94,1,77,1066.04,0.0,67.44,1.30,1.76,0.00,-1.700,-1.335,-0.96
2,94,2,77,1066.14,0.0,67.47,1.30,1.76,0.01,-0.990,-1.550,-0.86
3,94,3,77,1066.15,0.0,67.16,0.99,1.76,0.00,-0.365,-1.845,-0.85
4,94,4,77,1065.94,0.0,66.95,0.78,1.76,0.03,0.040,-1.830,-1.06
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,94,3995,73,1064.05,0.0,-1.77,-1.09,-0.04,-0.04,-2.530,-3.395,-2.95
3996,94,3996,73,1063.95,0.0,-1.43,-0.74,-0.04,-0.07,-2.735,-3.580,-3.05
3997,94,3997,73,1063.85,0.0,-1.33,-0.68,-0.04,-0.06,-2.855,-3.545,-3.15
3998,94,3998,73,1063.65,0.0,-1.24,-0.59,-0.04,-0.04,-3.100,-3.800,-3.35
3999,94,3999,73,1063.55,0.0,-1.21,-0.56,-0.04,-0.12,-3.115,-3.940,-3.45

In [ ]:
#ambil data per segmen 200 m = 656 ft
seg1 = cem.iloc[0:656] #200
seg2 = cem.iloc[656:1312] #200-400
seg3 = cem.iloc[1312:1968] #400-600
seg4 = cem.iloc[1968:2624] #600-800
seg4

,MP,MPFT,SPEED,GAUGE,GAUGE2,XLEVEL,XLEVEL_RATE,CURVE,CURVE_RATE,PROF,ALIGN,Lebar Sepur
1968,94,1968,75,1066.54,0.0,0.06,0.31,0.01,-0.01,-2.270,2.775,-0.46
1969,94,1969,75,1066.34,0.0,0.71,0.96,0.01,0.02,-2.015,2.315,-0.66
1970,94,1970,75,1066.14,0.0,0.90,1.18,0.01,0.08,-1.570,2.210,-0.86
1971,94,1971,75,1066.05,0.0,1.46,1.74,0.01,0.06,-1.195,1.795,-0.95
1972,94,1972,75,1065.74,0.0,1.77,2.08,0.01,0.03,-0.905,1.410,-1.26
...,...,...,...,...,...,...,...,...,...,...,...,...
2619,94,2619,74,1067.64,0.0,0.47,0.96,-0.01,-0.04,-3.910,1.755,0.64
2620,94,2620,74,1067.84,0.0,0.62,1.12,-0.01,-0.04,-3.425,2.110,0.84
2621,94,2621,74,1067.84,0.0,0.50,0.96,-0.01,0.00,-3.235,2.200,0.84
2622,94,2622,74,1067.84,0.0,0.71,1.18,-0.01,0.00,-3.645,2.415,0.84
2623,94,2623,74,1067.94,0.0,0.56,0.99,-0.01,0.00,-3.985,2.040,0.94

In [ ]:
#menghitung standar deviasi prof, align, lebar sepur, dan pertinggian pad data ciremai
import statistics

#seg1
std_deviasi1p = round(statistics.stdev(seg1['PROF']),2)
print('Angkatan',std_deviasi1p)
std_deviasi1a = round(statistics.stdev(seg1['ALIGN']),2)
print('Listringan',std_deviasi1a)
std_deviasi1l = round(statistics.stdev(seg1['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi1l)
std_deviasi1x = round(statistics.stdev(seg1['XLEVEL']),2)
print('pertinggian',std_deviasi1x)

#seg2
std_deviasi2p = round(statistics.stdev(seg2['PROF']),2)
print('Angkatan',std_deviasi2p)
std_deviasi2a = round(statistics.stdev(seg2['ALIGN']),2)
print('Listringan',std_deviasi2a)
std_deviasi2l = round(statistics.stdev(seg2['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi2l)
std_deviasi2x = round(statistics.stdev(seg2['XLEVEL']),2)
print('pertinggian',std_deviasi2x)

#seg3
std_deviasi3p = round(statistics.stdev(seg3['PROF']),2)
print('Angkatan',std_deviasi3p)
std_deviasi3a = round(statistics.stdev(seg3['ALIGN']),2)
print('Listringan',std_deviasi3a)
std_deviasi3l = round(statistics.stdev(seg3['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi3l)
std_deviasi3x = round(statistics.stdev(seg3['XLEVEL']),2)
print('pertinggian',std_deviasi3x)

#seg4
std_deviasi4p = round(statistics.stdev(seg4['PROF']),2)
print('Angkatan',std_deviasi4p)
std_deviasi4a = round(statistics.stdev(seg4['ALIGN']),2)
print('Listringan',std_deviasi4a)
std_deviasi4l = round(statistics.stdev(seg4['Lebar Sepur']),2)
print('Lebar Sepur',std_deviasi4l)
std_deviasi4x = round(statistics.stdev(seg4['XLEVEL']),2)
print('pertinggian',std_deviasi4x)

Angkatan 3.96
Listringan 2.55
Lebar Sepur 1.31
pertinggian 30.01
Angkatan 3.61
Listringan 1.46
Lebar Sepur 0.62
pertinggian 3.07
Angkatan 3.64
Listringan 1.42
Lebar Sepur 0.93
pertinggian 2.19
Angkatan 3.69
Listringan 1.59
Lebar Sepur 1.3
pertinggian 1.45

In [ ]:
#dataframe baru ciremai mengikuti format EM120

seg ={'KM_Awal':[94.000,94.200,94.400,94.600],
      'KM_Akhir':[94.200,94.400,94.600,94.800],
      'Angkatan' : [std_deviasi1p,std_deviasi2p,std_deviasi3p,std_deviasi4p],
      'Lestrengan' : [std_deviasi1a,std_deviasi2a,std_deviasi3a,std_deviasi4a],
      'Lebar Sepur' : [std_deviasi1l,std_deviasi2l,std_deviasi3l,std_deviasi4l],
      'Pertinggian' :[std_deviasi1x,std_deviasi2x,std_deviasi3x,std_deviasi4x]}

df_cem94 = pd.DataFrame(seg)
df_cem94

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     94.0      94.2      3.96        2.55         1.31        30.01
1     94.2      94.4      3.61        1.46         0.62         3.07
2     94.4      94.6      3.64        1.42         0.93         2.19
3     94.6      94.8      3.69        1.59         1.30         1.45

## menggabungkan data baru ciremai

In [ ]:
ciremai_baru = pd.concat([df_cem84,df_cem85,df_cem86,df_cem87,df_cem88,df_cem89,df_cem90,df_cem91,df_cem92,df_cem93,df_cem94])
ciremai_baru = ciremai_baru.reset_index()
ciremai_baru = ciremai_baru.drop(['index'],axis=1)
ciremai_baru

    KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0      84.0      84.2      5.41        4.91         0.73         3.77
1      84.2      84.4      7.32       20.30         4.48         7.43
2      84.4      84.6      9.11        0.00        11.97        32.21
3      84.6      84.8     11.40        9.70         9.95        28.52
4      85.0      85.2      8.74        4.50         1.83         5.92
5      85.2      85.4      7.43        4.47         1.30        16.66
6      85.4      85.6      7.04        3.15         1.22        28.84
7      85.6      85.8      7.38        3.13         1.48         7.16
8      86.0      86.2      6.41        2.19         1.42         2.00
9      86.2      86.4      3.63        2.04         1.10        29.08
10     86.4      86.6      5.98        2.64         1.05        27.06
11     86.6      86.8      5.77        1.90         1.83         2.86
12     87.0      87.2      4.80        2.89         1.47         3.26
13     87.2      87.4      4.03        2.36         1.07         3.27
14     87.4      87.6      7.47        3.58         2.16        18.64
15     87.6      87.8      4.64        4.08         1.49        13.16
16     88.0      88.2      7.98        3.23         2.07        11.67
17     88.2      88.4      5.69        3.57         1.24        42.01
18     88.4      88.6      5.00        3.15         1.43         4.14
19     88.6      88.8      3.03        3.38         1.69        36.68
20     89.0      89.2      5.41        4.91         0.73         3.77
21     89.2      89.4      7.32       20.30         4.48         7.43
22     89.4      89.6      9.11        0.00        11.97        32.21
23     89.6      89.8     11.40        9.70         9.95        28.52
24     90.0      90.2      4.95        1.74         1.50        26.48
25     90.2      90.4      7.98        2.25         2.12         4.87
26     90.4      90.6      6.64        3.55         4.76        44.53
27     90.6      90.8      5.28        3.62         3.91        31.32
28     91.0      91.2      5.94        4.99         5.30        33.72
29     91.2      91.4      2.85        2.82         3.08        40.29
30     91.4      91.6      3.17        2.67         2.99         9.98
31     91.6      91.8      3.18        2.51         1.28        20.59
32     92.0      92.2      5.37        4.55         1.64        10.09
33     92.2      92.4      5.61        3.75         2.23        35.64
34     92.4      92.6      8.34        7.58         1.86        10.34
35     92.6      92.8      3.63        3.16         2.41        36.40
36     93.0      93.2      5.22        2.92         0.96         2.09
37     93.2      93.4      4.24        2.13         1.58         2.17
38     93.4      93.6      3.25        1.49         0.96         1.97
39     93.6      93.8      1.99        1.89         1.16         1.03
40     94.0      94.2      3.96        2.55         1.31        30.01
41     94.2      94.4      3.61        1.46         0.62         3.07
42     94.4      94.6      3.64        1.42         0.93         2.19
43     94.6      94.8      3.69        1.59         1.30         1.45

In [ ]:
ciremai_baru.to_csv('ciremai_prepos.csv',index=False)

# Data EM120

In [ ]:
#Load data dt_em120
em = pd.read_csv("/content/drive/MyDrive/Proyek Penelitian Terapan/eksplorasi data/Dataset/EM120/Dt_EM120 (4).csv",delimiter=';')
em

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,159.977,159.907,LRS,70,2,32.6,8.6,14.1,9.5,0.4,2282.0,159,977,159,907
1,PDL0CKP,159.907,159.800,LK,107,2,37.5,12.6,16.7,7.7,0.5,4012.5,159,907,159,800
2,PDL0CKP,159.800,159.798,LK,2,2,10.8,4.8,0.8,5.2,0.1,21.6,159,800,159,798
3,PDL0CKP,159.798,159.792,BH,7,2,21.3,10.9,6.9,3.3,0.2,149.1,159,798,159,792
4,PDL0CKP,159.792,159.729,LK,63,2,42.1,15.9,20.1,6.2,0.0,2652.3,159,792,159,729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3961,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0
3962,CKP0CD,84.124,84.196,LK,73,2,25.5,6.9,10.7,7.1,0.8,1861.5,84,124,84,196
3963,CKP0CD,84.100,84.124,LRS,25,2,16.3,3.3,8.3,3.5,1.2,407.5,84,100,84,124
3964,CKP0CD,84.007,84.100,LRS,98,2,24.5,5.5,11.3,6.4,1.3,2401.0,84,7,84,100
3965,PDL0CKP,84.000,83.967,LRS,24,2,24.1,5.7,8.4,8.6,1.4,578.4,84,0,83,967

In [ ]:
em.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3966 entries, 0 to 3965
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   antara       3966 non-null   object
 1   km_awal      3966 non-null   float64
 2   km_akhir     3966 non-null   float64
 3   device_type  3966 non-null   object
 4   panjang      3966 non-null   int64
 5   kelas        3966 non-null   int64
 6   tqi          3966 non-null   float64
 7   pertinggian  3966 non-null   float64
 8   angkatan     3966 non-null   float64
 9   lestrengan   3966 non-null   float64
 10  lebar_sepur  3966 non-null   float64
 11  tqi_pjg      3966 non-null   float64
 12  km1          3966 non-null   int64
 13  hm1          3966 non-null   int64
 14  km2          3966 non-null   int64
 15  hm2          3966 non-null   int64
dtypes: float64(8), int64(6), object(2)
memory usage: 495.9+ KB

## ambil data km 84

In [ ]:
#ambil data dari km 84
km = em.groupby("km1")
ems = km.get_group(84).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1938,CKP0CD,84.804,85.000,LK,195,2,26.8,8.5,12.7,4.4,1.2,5226.0,84,804,85,0
1,1939,PDL0CKP,84.800,84.791,LK,9,2,20.4,12.9,4.1,2.4,1.0,183.6,84,800,84,791
2,1940,CKP0CD,84.800,84.804,LK,5,2,16.9,4.8,8.5,2.5,1.0,84.5,84,800,84,804
3,1941,PDL0CKP,84.791,84.600,LK,192,2,23.9,8.3,9.6,5.1,0.9,4588.8,84,791,84,600
4,1942,CKP0CD,84.779,84.800,LK,20,2,28.6,9.1,9.6,9.1,0.8,572.0,84,779,84,800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,3961,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0
86,3962,CKP0CD,84.124,84.196,LK,73,2,25.5,6.9,10.7,7.1,0.8,1861.5,84,124,84,196
87,3963,CKP0CD,84.100,84.124,LRS,25,2,16.3,3.3,8.3,3.5,1.2,407.5,84,100,84,124
88,3964,CKP0CD,84.007,84.100,LRS,98,2,24.5,5.5,11.3,6.4,1.3,2401.0,84,7,84,100
89,3965,PDL0CKP,84.000,83.967,LRS,24,2,24.1,5.7,8.4,8.6,1.4,578.4,84,0,83,967

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1,1939,PDL0CKP,84.800,84.791,LK,9,2,20.4,12.9,4.1,2.4,1.0,183.6,84,800,84,791
1,3,1941,PDL0CKP,84.791,84.600,LK,192,2,23.9,8.3,9.6,5.1,0.9,4588.8,84,791,84,600
2,8,1946,PDL0CKP,84.600,84.581,LK,19,2,32.1,7.8,16.0,8.3,0.0,609.9,84,600,84,581
3,10,1948,PDL0CKP,84.581,84.559,JPL,23,2,34.6,19.5,11.3,3.6,0.1,795.8,84,581,84,559
4,12,1950,PDL0CKP,84.559,84.545,LK,15,2,54.0,28.4,18.0,6.7,0.9,810.0,84,559,84,545
5,13,1951,PDL0CKP,84.545,84.493,LK,52,2,44.3,20.5,13.2,9.3,1.2,2303.6,84,545,84,493
6,16,1954,PDL0CKP,84.493,84.472,JPL,21,2,51.5,15.3,29.9,5.6,0.8,1081.5,84,493,84,472
7,18,1956,PDL0CKP,84.472,84.400,LK,73,2,34.6,12.3,11.8,9.2,1.4,2525.8,84,472,84,400
8,19,1957,PDL0CKP,84.400,84.365,LK,35,2,26.5,4.5,11.4,9.8,0.8,927.5,84,400,84,365
9,21,1959,PDL0CKP,84.365,84.337,WSL,29,2,61.1,21.0,23.4,16.1,0.6,1771.9,84,365,84,337
10,23,1961,PDL0CKP,84.337,84.329,LK,8,2,77.8,20.2,24.8,32.6,0.2,622.4,84,337,84,329
11,24,1962,PDL0CKP,84.329,84.303,WSL,26,2,68.8,23.1,22.2,22.5,1.0,1788.8,84,329,84,303
12,27,1965,PDL0CKP,84.303,84.301,LK,2,2,11.5,7.8,2.3,1.3,0.1,23.0,84,303,84,301
13,28,1966,PDL0CKP,84.301,84.267,WSL,35,2,55.8,16.0,19.2,19.4,1.2,1953.0,84,301,84,267
14,30,1968,PDL0CKP,84.267,84.222,LK,45,2,47.8,18.7,17.2,10.9,1.0,2151.0,84,267,84,222
15,33,1971,PDL0CKP,84.222,84.204,LK,18,2,34.7,8.9,13.5,10.9,1.4,624.6,84,222,84,204
16,34,1972,PDL0CKP,84.204,84.200,WSL,5,2,24.0,6.6,7.1,9.9,0.4,120.0,84,204,84,200
17,35,1973,PDL0CKP,84.200,84.169,WSL,31,2,41.4,11.2,18.9,9.3,1.9,1283.4,84,200,84,169
18,38,1976,PDL0CKP,84.169,84.159,LK,11,2,28.9,8.7,16.1,3.0,1.1,317.9,84,169,84,159
19,39,1977,PDL0CKP,84.159,84.138,LK,21,2,30.0,6.9,17.9,3.9,1.3,630.0,84,159,84,138
20,40,1978,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0
21,44,1982,PDL0CKP,84.000,83.967,LRS,24,2,24.1,5.7,8.4,8.6,1.4,578.4,84,0,83,967
22,46,3922,PDL0CKP,84.800,84.791,LK,9,2,20.4,12.9,4.1,2.4,1.0,183.6,84,800,84,791
23,48,3924,PDL0CKP,84.791,84.600,LK,192,2,23.9,8.3,9.6,5.1,0.9,4588.8,84,791,84,600
24,53,3929,PDL0CKP,84.600,84.581,LK,19,2,32.1,7.8,16.0,8.3,0.0,609.9,84,600,84,581
25,55,3931,PDL0CKP,84.581,84.559,JPL,23,2,34.6,19.5,11.3,3.6,0.1,795.8,84,581,84,559
26,57,3933,PDL0CKP,84.559,84.545,LK,15,2,54.0,28.4,18.0,6.7,0.9,810.0,84,559,84,545
27,58,3934,PDL0CKP,84.545,84.493,LK,52,2,44.3,20.5,13.2,9.3,1.2,2303.6,84,545,84,493
28,61,3937,PDL0CKP,84.493,84.472,JPL,21,2,51.5,15.3,29.9,5.6,0.8,1081.5,84,493,84,472
29,63,3939,PDL0CKP,84.472,84.400,LK,73,2,34.6,12.3,11.8,9.2,1.4,2525.8,84,472,84,400
30,64,3940,PDL0CKP,84.400,84.365,LK,35,2,26.5,4.5,11.4,9.8,0.8,927.5,84,400,84,365
31,66,3942,PDL0CKP,84.365,84.337,WSL,29,2,61.1,21.0,23.4,16.1,0.6,1771.9,84,365,84,337
32,68,3944,PDL0CKP,84.337,84.329,LK,8,2,77.8,20.2,24.8,32.6,0.2,622.4,84,337,84,329
33,69,3945,PDL0CKP,84.329,84.303,WSL,26,2,68.8,23.1,22.2,22.5,1.0,1788.8,84,329,84,303
34,72,3948,PDL0CKP,84.303,84.301,LK,2,2,11.5,7.8,2.3,1.3,0.1,23.0,84,303,84,301
35,73,3949,PDL0CKP,84.301,84.267,WSL,35,2,55.8,16.0,19.2,19.4,1.2,1953.0,84,301,84,267
36,75,3951,PDL0CKP,84.267,84.222,LK,45,2,47.8,18.7,17.2,10.9,1.0,2151.0,84,267,84,222
37,78,3954,PDL0CKP,84.222,84.204,LK,18,2,34.7,8.9,13.5,10.9,1.4,624.6,84,222,84,204
38,79,3955,PDL0CKP,84.204,84.200,WSL,5,2,24.0,6.6,7.1,9.9,0.4,120.0,84,204,84,200
39,80,3956,PDL0CKP,84.200,84.169,WSL,31,2,41.4,11.2,18.9,9.3,1.9,1283.4,84,200,84,169
40,83,3959,PDL0CKP,84.169,84.159,LK,11,2,28.9,8.7,16.1,3.0,1.1,317.9,84,169,84,159
41,84,3960,PDL0CKP,84.159,84.138,LK,21,2,30.0,6.9,17.9,3.9,1.3,630.0,84,159,84,138
42,85,3961,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0
43,89,3965,PDL0CKP,84.000,83.967,LRS,24,2,24.1,5.7,8.4,8.6,1.4,578.4,84,0,83,967

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em84 = ckp.iloc[:21]
em84

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,84.800,84.791,LK,9,2,20.4,12.9,4.1,2.4,1.0,183.6,84,800,84,791
1,PDL0CKP,84.791,84.600,LK,192,2,23.9,8.3,9.6,5.1,0.9,4588.8,84,791,84,600
2,PDL0CKP,84.600,84.581,LK,19,2,32.1,7.8,16.0,8.3,0.0,609.9,84,600,84,581
3,PDL0CKP,84.581,84.559,JPL,23,2,34.6,19.5,11.3,3.6,0.1,795.8,84,581,84,559
4,PDL0CKP,84.559,84.545,LK,15,2,54.0,28.4,18.0,6.7,0.9,810.0,84,559,84,545
5,PDL0CKP,84.545,84.493,LK,52,2,44.3,20.5,13.2,9.3,1.2,2303.6,84,545,84,493
6,PDL0CKP,84.493,84.472,JPL,21,2,51.5,15.3,29.9,5.6,0.8,1081.5,84,493,84,472
7,PDL0CKP,84.472,84.400,LK,73,2,34.6,12.3,11.8,9.2,1.4,2525.8,84,472,84,400
8,PDL0CKP,84.400,84.365,LK,35,2,26.5,4.5,11.4,9.8,0.8,927.5,84,400,84,365
9,PDL0CKP,84.365,84.337,WSL,29,2,61.1,21.0,23.4,16.1,0.6,1771.9,84,365,84,337
10,PDL0CKP,84.337,84.329,LK,8,2,77.8,20.2,24.8,32.6,0.2,622.4,84,337,84,329
11,PDL0CKP,84.329,84.303,WSL,26,2,68.8,23.1,22.2,22.5,1.0,1788.8,84,329,84,303
12,PDL0CKP,84.303,84.301,LK,2,2,11.5,7.8,2.3,1.3,0.1,23.0,84,303,84,301
13,PDL0CKP,84.301,84.267,WSL,35,2,55.8,16.0,19.2,19.4,1.2,1953.0,84,301,84,267
14,PDL0CKP,84.267,84.222,LK,45,2,47.8,18.7,17.2,10.9,1.0,2151.0,84,267,84,222
15,PDL0CKP,84.222,84.204,LK,18,2,34.7,8.9,13.5,10.9,1.4,624.6,84,222,84,204
16,PDL0CKP,84.204,84.200,WSL,5,2,24.0,6.6,7.1,9.9,0.4,120.0,84,204,84,200
17,PDL0CKP,84.200,84.169,WSL,31,2,41.4,11.2,18.9,9.3,1.9,1283.4,84,200,84,169
18,PDL0CKP,84.169,84.159,LK,11,2,28.9,8.7,16.1,3.0,1.1,317.9,84,169,84,159
19,PDL0CKP,84.159,84.138,LK,21,2,30.0,6.9,17.9,3.9,1.3,630.0,84,159,84,138
20,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em84['pertinggian_pjg'] = em84['pertinggian']*em84['panjang']
em84['angkatan_pjg'] = em84['angkatan']*em84['panjang']
em84['lestrengan_pjg'] = em84['lestrengan']*em84['panjang']
em84['lebar_sepur_pjg'] = em84['lebar_sepur']*em84['panjang']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
em84

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
0,PDL0CKP,84.800,84.791,LK,9,2,20.4,12.9,4.1,2.4,1.0,183.6,84,800,84,791,116.1,36.9,21.6,9.0
1,PDL0CKP,84.791,84.600,LK,192,2,23.9,8.3,9.6,5.1,0.9,4588.8,84,791,84,600,1593.6,1843.2,979.2,172.8
2,PDL0CKP,84.600,84.581,LK,19,2,32.1,7.8,16.0,8.3,0.0,609.9,84,600,84,581,148.2,304.0,157.7,0.0
3,PDL0CKP,84.581,84.559,JPL,23,2,34.6,19.5,11.3,3.6,0.1,795.8,84,581,84,559,448.5,259.9,82.8,2.3
4,PDL0CKP,84.559,84.545,LK,15,2,54.0,28.4,18.0,6.7,0.9,810.0,84,559,84,545,426.0,270.0,100.5,13.5
5,PDL0CKP,84.545,84.493,LK,52,2,44.3,20.5,13.2,9.3,1.2,2303.6,84,545,84,493,1066.0,686.4,483.6,62.4
6,PDL0CKP,84.493,84.472,JPL,21,2,51.5,15.3,29.9,5.6,0.8,1081.5,84,493,84,472,321.3,627.9,117.6,16.8
7,PDL0CKP,84.472,84.400,LK,73,2,34.6,12.3,11.8,9.2,1.4,2525.8,84,472,84,400,897.9,861.4,671.6,102.2
8,PDL0CKP,84.400,84.365,LK,35,2,26.5,4.5,11.4,9.8,0.8,927.5,84,400,84,365,157.5,399.0,343.0,28.0
9,PDL0CKP,84.365,84.337,WSL,29,2,61.1,21.0,23.4,16.1,0.6,1771.9,84,365,84,337,609.0,678.6,466.9,17.4
10,PDL0CKP,84.337,84.329,LK,8,2,77.8,20.2,24.8,32.6,0.2,622.4,84,337,84,329,161.6,198.4,260.8,1.6
11,PDL0CKP,84.329,84.303,WSL,26,2,68.8,23.1,22.2,22.5,1.0,1788.8,84,329,84,303,600.6,577.2,585.0,26.0
12,PDL0CKP,84.303,84.301,LK,2,2,11.5,7.8,2.3,1.3,0.1,23.0,84,303,84,301,15.6,4.6,2.6,0.2
13,PDL0CKP,84.301,84.267,WSL,35,2,55.8,16.0,19.2,19.4,1.2,1953.0,84,301,84,267,560.0,672.0,679.0,42.0
14,PDL0CKP,84.267,84.222,LK,45,2,47.8,18.7,17.2,10.9,1.0,2151.0,84,267,84,222,841.5,774.0,490.5,45.0
15,PDL0CKP,84.222,84.204,LK,18,2,34.7,8.9,13.5,10.9,1.4,624.6,84,222,84,204,160.2,243.0,196.2,25.2
16,PDL0CKP,84.204,84.200,WSL,5,2,24.0,6.6,7.1,9.9,0.4,120.0,84,204,84,200,33.0,35.5,49.5,2.0
17,PDL0CKP,84.200,84.169,WSL,31,2,41.4,11.2,18.9,9.3,1.9,1283.4,84,200,84,169,347.2,585.9,288.3,58.9
18,PDL0CKP,84.169,84.159,LK,11,2,28.9,8.7,16.1,3.0,1.1,317.9,84,169,84,159,95.7,177.1,33.0,12.1
19,PDL0CKP,84.159,84.138,LK,21,2,30.0,6.9,17.9,3.9,1.3,630.0,84,159,84,138,144.9,375.9,81.9,27.3
20,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0,861.8,2029.4,1320.5,166.8

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em84.iloc[0:2] #600-800
em3 = em84.iloc[2:8] #400-600
em2 = em84.iloc[8:17] #200-400
em1 = em84.iloc[17:21] #200
em1

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
17,PDL0CKP,84.200,84.169,WSL,31,2,41.4,11.2,18.9,9.3,1.9,1283.4,84,200,84,169,347.2,585.9,288.3,58.9
18,PDL0CKP,84.169,84.159,LK,11,2,28.9,8.7,16.1,3.0,1.1,317.9,84,169,84,159,95.7,177.1,33.0,12.1
19,PDL0CKP,84.159,84.138,LK,21,2,30.0,6.9,17.9,3.9,1.3,630.0,84,159,84,138,144.9,375.9,81.9,27.3
20,PDL0CKP,84.138,84.000,LRS,139,2,31.5,6.2,14.6,9.5,1.2,4378.5,84,138,84,0,861.8,2029.4,1320.5,166.8

(akumulasi (nilai per parameter*panjang))/total_panjang_dari kumpulan_baris

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 15.84
lestrengan 1: 8.62
lebar sepur 1: 1.33
pertinggian 1: 7.25
angkatan 2: 17.91
lestrengan 2: 15.37
lebar sepur 2: 0.94
pertinggian 2: 15.7
angkatan 3: 15.05
lestrengan 3: 8.07
lebar sepur 3: 0.99
pertinggian 3: 16.54
angkatan 4: 9.4
lestrengan 4: 5.0
lebar sepur 4: 0.91
pertinggian 4: 8.55

In [ ]:
#bikin dataframe baru
em_baru84 ={'KM_Awal':[84.000,84.200,84.400,84.600],
      'KM_Akhir':[84.200,84.400,84.600,84.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em84 = pd.DataFrame(em_baru84)
df_em84

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     84.0      84.2     15.84        8.62         1.33         7.25
1     84.2      84.4     17.91       15.37         0.94        15.70
2     84.4      84.6     15.05        8.07         0.99        16.54
3     84.6      84.8      9.40        5.00         0.91         8.55

## ambil data km 85

In [ ]:
#ambil data dari km 84
km = em.groupby("km1")
ems_85 = km.get_group(85).reset_index()
ems_85

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1888,CKP0CD,85.894,86.000,LRS,106,2,31.6,8.7,14.1,8.5,0.4,3349.6,85,894,86,0
1,1889,CKP0CD,85.886,85.894,JPL,8,2,23.8,4.3,16.9,2.5,0.0,190.4,85,886,85,894
2,1890,CKP0CD,85.824,85.886,LRS,62,2,22.2,3.9,8.4,9.5,0.4,1376.4,85,824,85,886
3,1891,PDL0CKP,85.800,85.609,LK,191,2,18.7,5.7,8.3,3.7,1.0,3571.7,85,800,85,609
4,1892,CKP0CD,85.800,85.824,LK,25,2,17.0,2.9,7.9,5.5,0.7,425.0,85,800,85,824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3916,CKP0CD,85.023,85.031,JPL,8,2,23.3,12.9,6.9,3.1,0.4,186.4,85,23,85,31
96,3917,PDL0CKP,85.016,85.012,JPL,4,2,25.0,14.0,8.2,2.8,0.0,100.0,85,16,85,12
97,3918,PDL0CKP,85.012,85.000,LK,13,2,38.5,19.1,9.7,8.6,1.2,500.5,85,12,85,0
98,3919,PDL0CKP,85.000,84.800,LK,200,2,24.7,10.5,9.7,3.8,0.7,4940.0,85,0,84,800
99,3920,CKP0CD,85.000,85.023,LK,24,2,18.4,5.9,6.2,5.5,0.8,441.6,85,0,85,23

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems_85.groupby("antara")
ckp_85 = antara.get_group('PDL0CKP').reset_index()
ckp_85

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,3,1891,PDL0CKP,85.800,85.609,LK,191,2,18.7,5.7,8.3,3.7,1.0,3571.7,85,800,85,609
1,9,1897,PDL0CKP,85.609,85.600,LK,10,2,13.8,1.5,8.2,2.6,1.4,138.0,85,609,85,600
2,10,1898,PDL0CKP,85.600,85.492,LK,99,2,20.2,3.7,12.0,3.4,1.0,1999.8,85,600,85,492
3,15,1903,PDL0CKP,85.505,85.450,LRS,46,2,27.5,4.9,15.2,4.3,3.0,1265.0,85,505,85,450
4,19,1907,PDL0CKP,85.450,85.445,JPL,5,2,17.4,6.3,0.7,7.9,2.5,87.0,85,450,85,445
5,20,1908,PDL0CKP,85.445,85.400,LRS,46,2,39.0,10.0,17.7,10.1,1.2,1794.0,85,445,85,400
6,22,1910,PDL0CKP,85.400,85.308,LRS,92,2,30.8,8.5,13.7,7.4,1.2,2833.6,85,400,85,308
7,28,1916,PDL0CKP,85.308,85.220,LRS,88,2,27.6,6.7,14.3,5.9,0.8,2428.8,85,308,85,220
8,34,1922,PDL0CKP,85.220,85.218,JPL,2,2,11.6,5.6,3.2,1.8,0.9,23.2,85,220,85,218
9,35,1923,PDL0CKP,85.218,85.215,LRS,3,2,14.5,3.6,6.9,3.9,0.1,43.5,85,218,85,215
10,36,1924,PDL0CKP,85.215,85.200,WSL,16,2,33.8,12.1,18.1,3.4,0.3,540.8,85,215,85,200
11,37,1925,PDL0CKP,85.200,85.179,WSL,21,2,34.9,7.4,18.6,8.7,0.2,732.9,85,200,85,179
12,40,1928,PDL0CKP,85.179,85.160,LRS,20,2,25.4,10.1,7.6,6.8,0.8,508.0,85,179,85,160
13,41,1929,PDL0CKP,85.160,85.016,LK,144,2,34.2,14.4,13.3,5.8,0.7,4924.8,85,160,85,16
14,46,1934,PDL0CKP,85.016,85.012,JPL,4,2,25.0,14.0,8.2,2.8,0.0,100.0,85,16,85,12
15,47,1935,PDL0CKP,85.012,85.000,LK,13,2,38.5,19.1,9.7,8.6,1.2,500.5,85,12,85,0
16,48,1936,PDL0CKP,85.000,84.800,LK,200,2,24.7,10.5,9.7,3.8,0.7,4940.0,85,0,84,800
17,53,3874,PDL0CKP,85.800,85.609,LK,191,2,18.7,5.7,8.3,3.7,1.0,3571.7,85,800,85,609
18,59,3880,PDL0CKP,85.609,85.600,LK,10,2,13.8,1.5,8.2,2.6,1.4,138.0,85,609,85,600
19,60,3881,PDL0CKP,85.600,85.492,LK,99,2,20.2,3.7,12.0,3.4,1.0,1999.8,85,600,85,492
20,65,3886,PDL0CKP,85.505,85.450,LRS,46,2,27.5,4.9,15.2,4.3,3.0,1265.0,85,505,85,450
21,69,3890,PDL0CKP,85.450,85.445,JPL,5,2,17.4,6.3,0.7,7.9,2.5,87.0,85,450,85,445
22,70,3891,PDL0CKP,85.445,85.400,LRS,46,2,39.0,10.0,17.7,10.1,1.2,1794.0,85,445,85,400
23,72,3893,PDL0CKP,85.400,85.308,LRS,92,2,30.8,8.5,13.7,7.4,1.2,2833.6,85,400,85,308
24,78,3899,PDL0CKP,85.308,85.220,LRS,88,2,27.6,6.7,14.3,5.9,0.8,2428.8,85,308,85,220
25,84,3905,PDL0CKP,85.220,85.218,JPL,2,2,11.6,5.6,3.2,1.8,0.9,23.2,85,220,85,218
26,85,3906,PDL0CKP,85.218,85.215,LRS,3,2,14.5,3.6,6.9,3.9,0.1,43.5,85,218,85,215
27,86,3907,PDL0CKP,85.215,85.200,WSL,16,2,33.8,12.1,18.1,3.4,0.3,540.8,85,215,85,200
28,87,3908,PDL0CKP,85.200,85.179,WSL,21,2,34.9,7.4,18.6,8.7,0.2,732.9,85,200,85,179
29,90,3911,PDL0CKP,85.179,85.160,LRS,20,2,25.4,10.1,7.6,6.8,0.8,508.0,85,179,85,160
30,91,3912,PDL0CKP,85.160,85.016,LK,144,2,34.2,14.4,13.3,5.8,0.7,4924.8,85,160,85,16
31,96,3917,PDL0CKP,85.016,85.012,JPL,4,2,25.0,14.0,8.2,2.8,0.0,100.0,85,16,85,12
32,97,3918,PDL0CKP,85.012,85.000,LK,13,2,38.5,19.1,9.7,8.6,1.2,500.5,85,12,85,0
33,98,3919,PDL0CKP,85.000,84.800,LK,200,2,24.7,10.5,9.7,3.8,0.7,4940.0,85,0,84,800

In [ ]:
ckp_85= ckp_85.drop(['level_0','index'],axis=1)

In [ ]:
em85 = ckp_85.iloc[:16]
em85

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,85.800,85.609,LK,191,2,18.7,5.7,8.3,3.7,1.0,3571.7,85,800,85,609
1,PDL0CKP,85.609,85.600,LK,10,2,13.8,1.5,8.2,2.6,1.4,138.0,85,609,85,600
2,PDL0CKP,85.600,85.492,LK,99,2,20.2,3.7,12.0,3.4,1.0,1999.8,85,600,85,492
3,PDL0CKP,85.505,85.450,LRS,46,2,27.5,4.9,15.2,4.3,3.0,1265.0,85,505,85,450
4,PDL0CKP,85.450,85.445,JPL,5,2,17.4,6.3,0.7,7.9,2.5,87.0,85,450,85,445
5,PDL0CKP,85.445,85.400,LRS,46,2,39.0,10.0,17.7,10.1,1.2,1794.0,85,445,85,400
6,PDL0CKP,85.400,85.308,LRS,92,2,30.8,8.5,13.7,7.4,1.2,2833.6,85,400,85,308
7,PDL0CKP,85.308,85.220,LRS,88,2,27.6,6.7,14.3,5.9,0.8,2428.8,85,308,85,220
8,PDL0CKP,85.220,85.218,JPL,2,2,11.6,5.6,3.2,1.8,0.9,23.2,85,220,85,218
9,PDL0CKP,85.218,85.215,LRS,3,2,14.5,3.6,6.9,3.9,0.1,43.5,85,218,85,215
10,PDL0CKP,85.215,85.200,WSL,16,2,33.8,12.1,18.1,3.4,0.3,540.8,85,215,85,200
11,PDL0CKP,85.200,85.179,WSL,21,2,34.9,7.4,18.6,8.7,0.2,732.9,85,200,85,179
12,PDL0CKP,85.179,85.160,LRS,20,2,25.4,10.1,7.6,6.8,0.8,508.0,85,179,85,160
13,PDL0CKP,85.160,85.016,LK,144,2,34.2,14.4,13.3,5.8,0.7,4924.8,85,160,85,16
14,PDL0CKP,85.016,85.012,JPL,4,2,25.0,14.0,8.2,2.8,0.0,100.0,85,16,85,12
15,PDL0CKP,85.012,85.000,LK,13,2,38.5,19.1,9.7,8.6,1.2,500.5,85,12,85,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em85['pertinggian_pjg'] = em85['pertinggian']*em85['panjang']
em85['angkatan_pjg'] = em85['angkatan']*em85['panjang']
em85['lestrengan_pjg'] = em85['lestrengan']*em85['panjang']
em85['lebar_sepur_pjg'] = em85['lebar_sepur']*em85['panjang']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em85.iloc[0:2] #600-800
em3 = em85.iloc[2:6] #400-600
em2 = em85.iloc[6:11] #200-400
em1 = em85.iloc[11:16] #200
em3

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
2,PDL0CKP,85.600,85.492,LK,99,2,20.2,3.7,12.0,3.4,1.0,1999.8,85,600,85,492,366.3,1188.0,336.6,99.0
3,PDL0CKP,85.505,85.450,LRS,46,2,27.5,4.9,15.2,4.3,3.0,1265.0,85,505,85,450,225.4,699.2,197.8,138.0
4,PDL0CKP,85.450,85.445,JPL,5,2,17.4,6.3,0.7,7.9,2.5,87.0,85,450,85,445,31.5,3.5,39.5,12.5
5,PDL0CKP,85.445,85.400,LRS,46,2,39.0,10.0,17.7,10.1,1.2,1794.0,85,445,85,400,460.0,814.2,464.6,55.2

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 13.08
lestrengan 1: 6.38
lebar sepur 1: 0.68
pertinggian 1: 13.68
angkatan 2: 14.18
lestrengan 2: 6.35
lebar sepur 2: 0.94
pertinggian 2: 7.94
angkatan 3: 13.52
lestrengan 3: 5.19
lebar sepur 3: 1.52
pertinggian 3: 5.42
angkatan 4: 8.34
lestrengan 4: 3.66
lebar sepur 4: 1.02
pertinggian 4: 5.52

In [ ]:
#bikin dataframe baru
em_baru85 ={'KM_Awal':[84.000,84.200,84.400,84.600],
      'KM_Akhir':[84.200,84.400,84.600,84.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em85 = pd.DataFrame(em_baru85)
df_em85

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     84.0      84.2     13.08        6.38         0.68        13.68
1     84.2      84.4     14.18        6.35         0.94         7.94
2     84.4      84.6     13.52        5.19         1.52         5.42
3     84.6      84.8      8.34        3.66         1.02         5.52

## ambil data km 86

In [ ]:
#ambil data dari km 86
km = em.groupby("km1")
ems_86 = km.get_group(86).reset_index()
ems_86

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1861,CKP0CD,86.927,87.000,LRS,73,2,20.0,4.3,7.3,8.1,0.4,1460.0,86,927,87,0
1,1862,CKP0CD,86.824,86.927,LK,103,2,19.2,4.5,7.7,6.5,0.5,1977.6,86,824,86,927
2,1863,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741
3,1864,CKP0CD,86.800,86.824,LRS,25,2,13.1,5.8,3.8,3.5,0.0,327.5,86,800,86,824
4,1865,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651
5,1866,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600
6,1867,PDL0CKP,86.600,86.470,LK,130,2,16.5,4.8,4.6,6.9,0.3,2145.0,86,600,86,470
7,1868,CKP0CD,86.600,86.800,LRS,200,2,18.2,3.8,7.4,6.6,0.5,3640.0,86,600,86,800
8,1869,CKP0CD,86.509,86.600,LRS,91,2,19.9,5.7,8.5,5.4,0.3,1810.9,86,509,86,600
9,1870,CKP0CD,86.490,86.509,LK,20,2,18.5,5.5,8.8,4.1,0.1,370.0,86,490,86,509
10,1871,CKP0CD,86.483,86.490,JPL,7,2,7.4,3.2,2.8,1.1,0.2,51.8,86,483,86,490
11,1872,PDL0CKP,86.470,86.465,JPL,6,2,16.7,9.5,1.5,5.7,0.0,100.2,86,470,86,465
12,1873,PDL0CKP,86.465,86.408,LK,57,2,25.9,10.2,5.1,10.0,0.6,1476.3,86,465,86,408
13,1874,CKP0CD,86.434,86.483,LK,49,2,22.4,6.7,9.2,6.3,0.3,1097.6,86,434,86,483
14,1875,PDL0CKP,86.408,86.400,LRS,9,2,9.7,2.2,2.3,3.2,2.0,87.3,86,408,86,400
15,1876,PDL0CKP,86.400,86.251,LRS,149,2,21.1,6.5,7.4,5.9,1.3,3143.9,86,400,86,251
16,1877,CKP0CD,86.400,86.434,LRS,35,2,29.4,7.5,13.7,7.6,0.6,1029.0,86,400,86,434
17,1878,CKP0CD,86.257,86.400,LRS,143,2,21.7,5.6,10.1,5.5,0.5,3103.1,86,257,86,400
18,1879,PDL0CKP,86.251,86.200,LK,52,2,15.0,4.5,4.5,5.1,1.0,780.0,86,251,86,200
19,1880,CKP0CD,86.205,86.257,LK,53,2,24.3,8.2,7.8,7.8,0.6,1287.9,86,205,86,257
20,1881,PDL0CKP,86.200,86.000,LK,200,2,15.1,4.3,4.7,5.3,0.8,3020.0,86,200,86,0
21,1882,CKP0CD,86.200,86.205,LK,6,2,19.9,9.5,3.9,6.3,0.2,119.4,86,200,86,205
22,1883,CKP0CD,86.119,86.200,LK,81,2,24.9,6.8,8.8,8.4,0.9,2016.9,86,119,86,200
23,1884,CKP0CD,86.104,86.119,LRS,15,2,17.3,3.8,7.8,5.7,0.1,259.5,86,104,86,119
24,1885,CKP0CD,86.062,86.104,LK,42,2,22.6,5.3,8.8,7.7,0.7,949.2,86,62,86,104
25,1886,PDL0CKP,86.000,85.800,LK,200,2,27.7,8.2,12.6,5.9,0.9,5540.0,86,0,85,800
26,1887,CKP0CD,86.000,86.062,LRS,63,2,22.2,6.1,7.8,8.1,0.2,1398.6,86,0,86,62
27,3844,CKP0CD,86.927,87.000,LRS,73,2,20.0,4.3,7.3,8.1,0.4,1460.0,86,927,87,0
28,3845,CKP0CD,86.824,86.927,LK,103,2,19.2,4.5,7.7,6.5,0.5,1977.6,86,824,86,927
29,3846,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741
30,3847,CKP0CD,86.800,86.824,LRS,25,2,13.1,5.8,3.8,3.5,0.0,327.5,86,800,86,824
31,3848,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651
32,3849,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600
33,3850,PDL0CKP,86.600,86.470,LK,130,2,16.5,4.8,4.6,6.9,0.3,2145.0,86,600,86,470
34,3851,CKP0CD,86.600,86.800,LRS,200,2,18.2,3.8,7.4,6.6,0.5,3640.0,86,600,86,800
35,3852,CKP0CD,86.509,86.600,LRS,91,2,19.9,5.7,8.5,5.4,0.3,1810.9,86,509,86,600
36,3853,CKP0CD,86.490,86.509,LK,20,2,18.5,5.5,8.8,4.1,0.1,370.0,86,490,86,509
37,3854,CKP0CD,86.483,86.490,JPL,7,2,7.4,3.2,2.8,1.1,0.2,51.8,86,483,86,490
38,3855,PDL0CKP,86.470,86.465,JPL,6,2,16.7,9.5,1.5,5.7,0.0,100.2,86,470,86,465
39,3856,PDL0CKP,86.465,86.408,LK,57,2,25.9,10.2,5.1,10.0,0.6,1476.3,86,465,86,408
40,3857,CKP0CD,86.434,86.483,LK,49,2,22.4,6.7,9.2,6.3,0.3,1097.6,86,434,86,483
41,3858,PDL0CKP,86.408,86.400,LRS,9,2,9.7,2.2,2.3,3.2,2.0,87.3,86,408,86,400
42,3859,PDL0CKP,86.400,86.251,LRS,149,2,21.1,6.5,7.4,5.9,1.3,3143.9,86,400,86,251
43,3860,CKP0CD,86.400,86.434,LRS,35,2,29.4,7.5,13.7,7.6,0.6,1029.0,86,400,86,434
44,3861,CKP0CD,86.257,86.400,LRS,143,2,21.7,5.6,10.1,5.5,0.5,3103.1,86,257,86,400
45,3862,PDL0CKP,86.251,86.200,LK,52,2,15.0,4.5,4.5,5.1,1.0,780.0,86,251,86,200
46,3863,CKP0CD,86.205,86.257,LK,53,2,24.3,8.2,7.8,7.8,0.6,1287.9,86,205,86,257
47,3864,PDL0CKP,86.200,86.000,LK,200,2,15.1,4.3,4.7,5.3,0.8,3020.0,86,200,86,0
48,3865,CKP0CD,86.200,86.205,LK,6,2,19.9,9.5,3.9,6.3,0.2,119.4,86,200,86,205
49,3866,CKP0CD,86.119,86.200,LK,81,2,24.9,6.8,8.8,8.4,0.9,2016.9,86,119,86,200
50,3867,CKP0CD,86.104,86.119,LRS,15,2,17.3,3.8,7.8,5.7,0.1,259.5,86,104,86,119
51,3868,CKP0CD,86.062,86.104,LK,42,2,22.6,5.3,8.8,7.7,0.7,949.2,86,62,86,104
52,3869,PDL0CKP,86.000,85.800,LK,200,2,27.7,8.2,12.6,5.9,0.9,5540.0,86,0,85,800
53,3870,CKP0CD,86.000,86.062,LRS,63,2,22.2,6.1,7.8,8.1,0.2,1398.6,86,0,86,62

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems_86.groupby("antara")
ckp86 = antara.get_group('PDL0CKP').reset_index()
ckp86

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,2,1863,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741
1,4,1865,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651
2,5,1866,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600
3,6,1867,PDL0CKP,86.600,86.470,LK,130,2,16.5,4.8,4.6,6.9,0.3,2145.0,86,600,86,470
4,11,1872,PDL0CKP,86.470,86.465,JPL,6,2,16.7,9.5,1.5,5.7,0.0,100.2,86,470,86,465
5,12,1873,PDL0CKP,86.465,86.408,LK,57,2,25.9,10.2,5.1,10.0,0.6,1476.3,86,465,86,408
6,14,1875,PDL0CKP,86.408,86.400,LRS,9,2,9.7,2.2,2.3,3.2,2.0,87.3,86,408,86,400
7,15,1876,PDL0CKP,86.400,86.251,LRS,149,2,21.1,6.5,7.4,5.9,1.3,3143.9,86,400,86,251
8,18,1879,PDL0CKP,86.251,86.200,LK,52,2,15.0,4.5,4.5,5.1,1.0,780.0,86,251,86,200
9,20,1881,PDL0CKP,86.200,86.000,LK,200,2,15.1,4.3,4.7,5.3,0.8,3020.0,86,200,86,0
10,25,1886,PDL0CKP,86.000,85.800,LK,200,2,27.7,8.2,12.6,5.9,0.9,5540.0,86,0,85,800
11,29,3846,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741
12,31,3848,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651
13,32,3849,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600
14,33,3850,PDL0CKP,86.600,86.470,LK,130,2,16.5,4.8,4.6,6.9,0.3,2145.0,86,600,86,470
15,38,3855,PDL0CKP,86.470,86.465,JPL,6,2,16.7,9.5,1.5,5.7,0.0,100.2,86,470,86,465
16,39,3856,PDL0CKP,86.465,86.408,LK,57,2,25.9,10.2,5.1,10.0,0.6,1476.3,86,465,86,408
17,41,3858,PDL0CKP,86.408,86.400,LRS,9,2,9.7,2.2,2.3,3.2,2.0,87.3,86,408,86,400
18,42,3859,PDL0CKP,86.400,86.251,LRS,149,2,21.1,6.5,7.4,5.9,1.3,3143.9,86,400,86,251
19,45,3862,PDL0CKP,86.251,86.200,LK,52,2,15.0,4.5,4.5,5.1,1.0,780.0,86,251,86,200
20,47,3864,PDL0CKP,86.200,86.000,LK,200,2,15.1,4.3,4.7,5.3,0.8,3020.0,86,200,86,0
21,52,3869,PDL0CKP,86.000,85.800,LK,200,2,27.7,8.2,12.6,5.9,0.9,5540.0,86,0,85,800

In [ ]:
ckp86 = ckp86.drop(['level_0','index'],axis=1)

In [ ]:
em86 = ckp86.iloc[:10]
em86

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741
1,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651
2,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600
3,PDL0CKP,86.600,86.470,LK,130,2,16.5,4.8,4.6,6.9,0.3,2145.0,86,600,86,470
4,PDL0CKP,86.470,86.465,JPL,6,2,16.7,9.5,1.5,5.7,0.0,100.2,86,470,86,465
5,PDL0CKP,86.465,86.408,LK,57,2,25.9,10.2,5.1,10.0,0.6,1476.3,86,465,86,408
6,PDL0CKP,86.408,86.400,LRS,9,2,9.7,2.2,2.3,3.2,2.0,87.3,86,408,86,400
7,PDL0CKP,86.400,86.251,LRS,149,2,21.1,6.5,7.4,5.9,1.3,3143.9,86,400,86,251
8,PDL0CKP,86.251,86.200,LK,52,2,15.0,4.5,4.5,5.1,1.0,780.0,86,251,86,200
9,PDL0CKP,86.200,86.000,LK,200,2,15.1,4.3,4.7,5.3,0.8,3020.0,86,200,86,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em86['pertinggian_pjg'] = em86['pertinggian']*em86['panjang']
em86['angkatan_pjg'] = em86['angkatan']*em86['panjang']
em86['lestrengan_pjg'] = em86['lestrengan']*em86['panjang']
em86['lebar_sepur_pjg'] = em86['lebar_sepur']*em86['panjang']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em86.iloc[0:3] #600-800
em3 = em86.iloc[3:7] #400-600
em2 = em86.iloc[7:9] #200-400
em1 = em86.iloc[9:10] #200
em4

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
0,PDL0CKP,86.800,86.741,LK,59,2,18.4,4.5,4.3,9.2,0.4,1085.6,86,800,86,741,265.5,253.7,542.8,23.6
1,PDL0CKP,86.741,86.651,LRS,90,2,19.0,4.5,5.6,8.4,0.5,1710.0,86,741,86,651,405.0,504.0,756.0,45.0
2,PDL0CKP,86.651,86.600,LK,52,2,16.8,3.4,3.7,9.2,0.4,873.6,86,651,86,600,176.8,192.4,478.4,20.8

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 4.7
lestrengan 1: 5.3
lebar sepur 1: 0.8
pertinggian 1: 4.3
angkatan 2: 6.68
lestrengan 2: 5.72
lebar sepur 2: 1.23
pertinggian 2: 6.01
angkatan 3: 4.59
lestrengan 3: 7.65
lebar sepur 3: 0.46
pertinggian 3: 6.41
angkatan 4: 4.75
lestrengan 4: 8.89
lebar sepur 4: 0.45
pertinggian 4: 4.24

In [ ]:
#bikin dataframe baru
em_baru86 ={'KM_Awal':[86.000,86.200,86.400,86.600],
      'KM_Akhir':[86.200,86.400,86.600,86.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em86 = pd.DataFrame(em_baru86)
df_em86

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     86.0      86.2      4.70        5.30         0.80         4.30
1     86.2      86.4      6.68        5.72         1.23         6.01
2     86.4      86.6      4.59        7.65         0.46         6.41
3     86.6      86.8      4.75        8.89         0.45         4.24

## ambil data km 87

In [ ]:
#ambil data dari km 87
km = em.groupby("km1")
ems87 = km.get_group(87).reset_index()
ems87

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1847,PDL0CKP,87.991,87.800,LK,192,2,19.6,7.2,7.1,4.9,0.5,3763.2,87,991,87,800
1,1848,PDL0CKP,87.800,87.600,LK,200,2,22.7,10.9,7.6,4.1,0.2,4540.0,87,800,87,600
2,1849,CKP0CD,87.800,88.000,LK,200,2,15.5,3.9,8.2,3.4,0.0,3100.0,87,800,88,0
3,1850,PDL0CKP,87.600,87.400,LK,200,2,18.6,5.8,7.1,5.1,0.6,3720.0,87,600,87,400
4,1851,CKP0CD,87.600,87.800,LK,200,2,21.9,6.7,10.0,4.9,0.3,4380.0,87,600,87,800
5,1852,CKP0CD,87.417,87.600,LK,183,2,24.4,6.3,9.4,8.4,0.3,4465.2,87,417,87,600
6,1853,PDL0CKP,87.400,87.200,LK,200,2,29.3,9.3,11.2,8.5,0.3,5860.0,87,400,87,200
7,1854,CKP0CD,87.400,87.417,LRS,18,2,13.1,5.5,3.8,3.9,0.0,235.8,87,400,87,417
8,1855,CKP0CD,87.384,87.400,LRS,16,2,17.6,5.2,4.3,8.1,0.0,281.6,87,384,87,400
9,1856,CKP0CD,87.279,87.384,LK,105,2,19.3,5.4,7.2,6.1,0.6,2026.5,87,279,87,384
10,1857,PDL0CKP,87.200,87.000,LK,200,2,24.8,6.1,9.1,9.1,0.5,4960.0,87,200,87,0
11,1858,CKP0CD,87.200,87.279,LRS,80,2,29.4,7.7,11.8,9.4,0.5,2352.0,87,200,87,279
12,1859,PDL0CKP,87.000,86.800,LK,200,2,21.5,5.0,6.1,10.0,0.3,4300.0,87,0,86,800
13,1860,CKP0CD,87.000,87.200,LRS,200,2,25.8,8.5,9.7,7.2,0.5,5160.0,87,0,87,200
14,3830,PDL0CKP,87.991,87.800,LK,192,2,19.6,7.2,7.1,4.9,0.5,3763.2,87,991,87,800
15,3831,PDL0CKP,87.800,87.600,LK,200,2,22.7,10.9,7.6,4.1,0.2,4540.0,87,800,87,600
16,3832,CKP0CD,87.800,88.000,LK,200,2,15.5,3.9,8.2,3.4,0.0,3100.0,87,800,88,0
17,3833,PDL0CKP,87.600,87.400,LK,200,2,18.6,5.8,7.1,5.1,0.6,3720.0,87,600,87,400
18,3834,CKP0CD,87.600,87.800,LK,200,2,21.9,6.7,10.0,4.9,0.3,4380.0,87,600,87,800
19,3835,CKP0CD,87.417,87.600,LK,183,2,24.4,6.3,9.4,8.4,0.3,4465.2,87,417,87,600
20,3836,PDL0CKP,87.400,87.200,LK,200,2,29.3,9.3,11.2,8.5,0.3,5860.0,87,400,87,200
21,3837,CKP0CD,87.400,87.417,LRS,18,2,13.1,5.5,3.8,3.9,0.0,235.8,87,400,87,417
22,3838,CKP0CD,87.384,87.400,LRS,16,2,17.6,5.2,4.3,8.1,0.0,281.6,87,384,87,400
23,3839,CKP0CD,87.279,87.384,LK,105,2,19.3,5.4,7.2,6.1,0.6,2026.5,87,279,87,384
24,3840,PDL0CKP,87.200,87.000,LK,200,2,24.8,6.1,9.1,9.1,0.5,4960.0,87,200,87,0
25,3841,CKP0CD,87.200,87.279,LRS,80,2,29.4,7.7,11.8,9.4,0.5,2352.0,87,200,87,279
26,3842,PDL0CKP,87.000,86.800,LK,200,2,21.5,5.0,6.1,10.0,0.3,4300.0,87,0,86,800
27,3843,CKP0CD,87.000,87.200,LRS,200,2,25.8,8.5,9.7,7.2,0.5,5160.0,87,0,87,200

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems87.groupby("antara")
ckp87 = antara.get_group('PDL0CKP').reset_index()
ckp87

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1847,PDL0CKP,87.991,87.8,LK,192,2,19.6,7.2,7.1,4.9,0.5,3763.2,87,991,87,800
1,1,1848,PDL0CKP,87.800,87.6,LK,200,2,22.7,10.9,7.6,4.1,0.2,4540.0,87,800,87,600
2,3,1850,PDL0CKP,87.600,87.4,LK,200,2,18.6,5.8,7.1,5.1,0.6,3720.0,87,600,87,400
3,6,1853,PDL0CKP,87.400,87.2,LK,200,2,29.3,9.3,11.2,8.5,0.3,5860.0,87,400,87,200
4,10,1857,PDL0CKP,87.200,87.0,LK,200,2,24.8,6.1,9.1,9.1,0.5,4960.0,87,200,87,0
5,12,1859,PDL0CKP,87.000,86.8,LK,200,2,21.5,5.0,6.1,10.0,0.3,4300.0,87,0,86,800
6,14,3830,PDL0CKP,87.991,87.8,LK,192,2,19.6,7.2,7.1,4.9,0.5,3763.2,87,991,87,800
7,15,3831,PDL0CKP,87.800,87.6,LK,200,2,22.7,10.9,7.6,4.1,0.2,4540.0,87,800,87,600
8,17,3833,PDL0CKP,87.600,87.4,LK,200,2,18.6,5.8,7.1,5.1,0.6,3720.0,87,600,87,400
9,20,3836,PDL0CKP,87.400,87.2,LK,200,2,29.3,9.3,11.2,8.5,0.3,5860.0,87,400,87,200
10,24,3840,PDL0CKP,87.200,87.0,LK,200,2,24.8,6.1,9.1,9.1,0.5,4960.0,87,200,87,0
11,26,3842,PDL0CKP,87.000,86.8,LK,200,2,21.5,5.0,6.1,10.0,0.3,4300.0,87,0,86,800

In [ ]:
ckp87 = ckp87.drop(['level_0','index'],axis=1)

In [ ]:
em87 = ckp87.iloc[1:5]
em87

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
1,PDL0CKP,87.8,87.6,LK,200,2,22.7,10.9,7.6,4.1,0.2,4540.0,87,800,87,600
2,PDL0CKP,87.6,87.4,LK,200,2,18.6,5.8,7.1,5.1,0.6,3720.0,87,600,87,400
3,PDL0CKP,87.4,87.2,LK,200,2,29.3,9.3,11.2,8.5,0.3,5860.0,87,400,87,200
4,PDL0CKP,87.2,87.0,LK,200,2,24.8,6.1,9.1,9.1,0.5,4960.0,87,200,87,0

In [ ]:
#bikin dataframe baru
df_em87 = em87.drop(['antara','device_type','panjang','kelas','tqi','tqi_pjg','km1','hm1','km2','hm2'],axis=1)
df_em87

   km_awal  km_akhir  pertinggian  angkatan  lestrengan  lebar_sepur
1     87.8      87.6         10.9       7.6         4.1          0.2
2     87.6      87.4          5.8       7.1         5.1          0.6
3     87.4      87.2          9.3      11.2         8.5          0.3
4     87.2      87.0          6.1       9.1         9.1          0.5

In [ ]:
df_em87.columns = ['KM_Awal', 'KM_Akhir','Pertinggian', 'Angkatan','Lestrengan','Lebar Sepur']

In [ ]:
df_em87 = df_em87[['KM_Awal', 'KM_Akhir', 'Angkatan','Lestrengan','Lebar Sepur','Pertinggian']]
df_em87

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
1     87.8      87.6       7.6         4.1          0.2         10.9
2     87.6      87.4       7.1         5.1          0.6          5.8
3     87.4      87.2      11.2         8.5          0.3          9.3
4     87.2      87.0       9.1         9.1          0.5          6.1

## ambil data km 88

In [ ]:
#ambil data dari km 88
km = em.groupby("km1")
ems88 = km.get_group(88).reset_index()
ems88

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1817,PDL0CKP,88.978,88.808,LRS,170,2,21.1,6.8,8.7,5.2,0.4,3587.0,88,978,88,808
1,1818,PDL0CKP,88.808,88.800,LK,9,2,28.5,8.9,15.2,4.1,0.3,256.5,88,808,88,800
2,1819,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726
3,1820,CKP0CD,88.800,89.000,LK,200,2,28.4,8.2,12.9,6.9,0.4,5680.0,88,800,89,0
4,1821,CKP0CD,88.737,88.800,LK,62,2,28.9,11.4,5.9,11.2,0.4,1791.8,88,737,88,800
5,1822,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618
6,1823,CKP0CD,88.687,88.737,LK,51,2,24.2,7.1,8.7,8.4,0.0,1234.2,88,687,88,737
7,1824,CKP0CD,88.639,88.687,LRS,48,2,30.4,7.4,13.1,9.3,0.7,1459.2,88,639,88,687
8,1825,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600
9,1826,PDL0CKP,88.600,88.400,LK,200,2,20.3,6.3,6.9,6.8,0.4,4060.0,88,600,88,400
10,1827,CKP0CD,88.600,88.639,LK,40,2,20.7,5.1,4.8,10.2,0.5,828.0,88,600,88,639
11,1828,CKP0CD,88.482,88.600,LK,118,2,21.4,6.2,5.7,8.7,0.8,2525.2,88,482,88,600
12,1829,CKP0CD,88.473,88.482,BH,9,2,27.6,8.0,7.3,12.0,0.3,248.4,88,473,88,482
13,1830,CKP0CD,88.458,88.473,LK,15,2,35.8,14.5,16.5,4.0,0.8,537.0,88,458,88,473
14,1831,CKP0CD,88.454,88.458,BH,5,2,13.1,7.8,3.9,1.5,0.0,65.5,88,454,88,458
15,1832,PDL0CKP,88.400,88.200,LK,200,2,18.4,6.0,7.1,5.0,0.3,3680.0,88,400,88,200
16,1833,CKP0CD,88.400,88.454,LK,55,2,33.2,12.8,14.6,5.4,0.4,1826.0,88,400,88,454
17,1834,CKP0CD,88.209,88.400,LK,191,2,23.8,9.3,7.9,6.2,0.4,4545.8,88,209,88,400
18,1835,PDL0CKP,88.200,88.186,LK,14,2,14.8,5.6,5.9,3.3,0.0,207.2,88,200,88,186
19,1836,CKP0CD,88.200,88.209,LRS,10,2,11.5,4.2,3.1,3.9,0.3,115.0,88,200,88,209
20,1837,PDL0CKP,88.186,88.123,LK,63,2,15.7,6.7,3.6,4.7,0.6,989.1,88,186,88,123
21,1838,CKP0CD,88.130,88.200,LRS,70,2,28.2,8.1,10.5,9.0,0.6,1974.0,88,130,88,200
22,1839,PDL0CKP,88.123,88.116,LK,7,2,19.9,4.7,10.4,4.8,0.0,139.3,88,123,88,116
23,1840,CKP0CD,88.121,88.130,JPL,10,2,36.4,7.7,22.8,5.0,0.9,364.0,88,121,88,130
24,1841,PDL0CKP,88.116,88.108,LRS,9,2,25.7,7.4,8.9,9.2,0.3,231.3,88,116,88,108
25,1842,PDL0CKP,88.108,88.106,JPL,2,2,17.1,3.3,5.6,7.3,0.8,34.2,88,108,88,106
26,1843,PDL0CKP,88.106,88.000,LRS,106,2,29.4,9.0,10.3,9.7,0.5,3116.4,88,106,88,0
27,1844,CKP0CD,88.029,88.121,LRS,92,2,25.6,4.6,11.4,8.9,0.6,2355.2,88,29,88,121
28,1845,PDL0CKP,88.000,87.991,LRS,9,2,19.4,5.4,5.1,7.9,1.0,174.6,88,0,87,991
29,1846,CKP0CD,88.000,88.029,LK,30,2,32.7,4.2,18.8,9.2,0.6,981.0,88,0,88,29
30,3800,PDL0CKP,88.978,88.808,LRS,170,2,21.1,6.8,8.7,5.2,0.4,3587.0,88,978,88,808
31,3801,PDL0CKP,88.808,88.800,LK,9,2,28.5,8.9,15.2,4.1,0.3,256.5,88,808,88,800
32,3802,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726
33,3803,CKP0CD,88.800,89.000,LK,200,2,28.4,8.2,12.9,6.9,0.4,5680.0,88,800,89,0
34,3804,CKP0CD,88.737,88.800,LK,62,2,28.9,11.4,5.9,11.2,0.4,1791.8,88,737,88,800
35,3805,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618
36,3806,CKP0CD,88.687,88.737,LK,51,2,24.2,7.1,8.7,8.4,0.0,1234.2,88,687,88,737
37,3807,CKP0CD,88.639,88.687,LRS,48,2,30.4,7.4,13.1,9.3,0.7,1459.2,88,639,88,687
38,3808,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600
39,3809,PDL0CKP,88.600,88.400,LK,200,2,20.3,6.3,6.9,6.8,0.4,4060.0,88,600,88,400
40,3810,CKP0CD,88.600,88.639,LK,40,2,20.7,5.1,4.8,10.2,0.5,828.0,88,600,88,639
41,3811,CKP0CD,88.482,88.600,LK,118,2,21.4,6.2,5.7,8.7,0.8,2525.2,88,482,88,600
42,3812,CKP0CD,88.473,88.482,BH,9,2,27.6,8.0,7.3,12.0,0.3,248.4,88,473,88,482
43,3813,CKP0CD,88.458,88.473,LK,15,2,35.8,14.5,16.5,4.0,0.8,537.0,88,458,88,473
44,3814,CKP0CD,88.454,88.458,BH,5,2,13.1,7.8,3.9,1.5,0.0,65.5,88,454,88,458
45,3815,PDL0CKP,88.400,88.200,LK,200,2,18.4,6.0,7.1,5.0,0.3,3680.0,88,400,88,200
46,3816,CKP0CD,88.400,88.454,LK,55,2,33.2,12.8,14.6,5.4,0.4,1826.0,88,400,88,454
47,3817,CKP0CD,88.209,88.400,LK,191,2,23.8,9.3,7.9,6.2,0.4,4545.8,88,209,88,400
48,3818,PDL0CKP,88.200,88.186,LK,14,2,14.8,5.6,5.9,3.3,0.0,207.2,88,200,88,186
49,3819,CKP0CD,88.200,88.209,LRS,10,2,11.5,4.2,3.1,3.9,0.3,115.0,88,200,88,209
50,3820,PDL0CKP,88.186,88.123,LK,63,2,15.7,6.7,3.6,4.7,0.6,989.1,88,186,88,123
51,3821,CKP0CD,88.130,88.200,LRS,70,2,28.2,8.1,10.5,9.0,0.6,1974.0,88,130,88,200
52,3822,PDL0CKP,88.123,88.116,LK,7,2,19.9,4.7,10.4,4.8,0.0,139.3,88,123,88,116
53,3823,CKP0CD,88.121,88.130,JPL,10,2,36.4,7.7,22.8,5.0,0.9,364.0,88,121,88,130
54,3824,PDL0CKP,88.116,88.108,LRS,9,2,25.7,7.4,8.9,9.2,0.3,231.3,88,116,88,108
55,3825,PDL0CKP,88.108,88.106,JPL,2,2,17.1,3.3,5.6,7.3,0.8,34.2,88,108,88,106
56,3826,PDL0CKP,88.106,88.000,LRS,106,2,29.4,9.0,10.3,9.7,0.5,3116.4,88,106,88,0
57,3827,CKP0CD,88.029,88.121,LRS,92,2,25.6,4.6,11.4,8.9,0.6,2355.2,88,29,88,121
58,3828,PDL0CKP,88.000,87.991,LRS,9,2,19.4,5.4,5.1,7.9,1.0,174.6,88,0,87,991
59,3829,CKP0CD,88.000,88.029,LK,30,2,32.7,4.2,18.8,9.2,0.6,981.0,88,0,88,29

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems88.groupby("antara")
ckp88 = antara.get_group('PDL0CKP').reset_index()
ckp88

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1817,PDL0CKP,88.978,88.808,LRS,170,2,21.1,6.8,8.7,5.2,0.4,3587.0,88,978,88,808
1,1,1818,PDL0CKP,88.808,88.800,LK,9,2,28.5,8.9,15.2,4.1,0.3,256.5,88,808,88,800
2,2,1819,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726
3,5,1822,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618
4,8,1825,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600
5,9,1826,PDL0CKP,88.600,88.400,LK,200,2,20.3,6.3,6.9,6.8,0.4,4060.0,88,600,88,400
6,15,1832,PDL0CKP,88.400,88.200,LK,200,2,18.4,6.0,7.1,5.0,0.3,3680.0,88,400,88,200
7,18,1835,PDL0CKP,88.200,88.186,LK,14,2,14.8,5.6,5.9,3.3,0.0,207.2,88,200,88,186
8,20,1837,PDL0CKP,88.186,88.123,LK,63,2,15.7,6.7,3.6,4.7,0.6,989.1,88,186,88,123
9,22,1839,PDL0CKP,88.123,88.116,LK,7,2,19.9,4.7,10.4,4.8,0.0,139.3,88,123,88,116
10,24,1841,PDL0CKP,88.116,88.108,LRS,9,2,25.7,7.4,8.9,9.2,0.3,231.3,88,116,88,108
11,25,1842,PDL0CKP,88.108,88.106,JPL,2,2,17.1,3.3,5.6,7.3,0.8,34.2,88,108,88,106
12,26,1843,PDL0CKP,88.106,88.000,LRS,106,2,29.4,9.0,10.3,9.7,0.5,3116.4,88,106,88,0
13,28,1845,PDL0CKP,88.000,87.991,LRS,9,2,19.4,5.4,5.1,7.9,1.0,174.6,88,0,87,991
14,30,3800,PDL0CKP,88.978,88.808,LRS,170,2,21.1,6.8,8.7,5.2,0.4,3587.0,88,978,88,808
15,31,3801,PDL0CKP,88.808,88.800,LK,9,2,28.5,8.9,15.2,4.1,0.3,256.5,88,808,88,800
16,32,3802,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726
17,35,3805,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618
18,38,3808,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600
19,39,3809,PDL0CKP,88.600,88.400,LK,200,2,20.3,6.3,6.9,6.8,0.4,4060.0,88,600,88,400
20,45,3815,PDL0CKP,88.400,88.200,LK,200,2,18.4,6.0,7.1,5.0,0.3,3680.0,88,400,88,200
21,48,3818,PDL0CKP,88.200,88.186,LK,14,2,14.8,5.6,5.9,3.3,0.0,207.2,88,200,88,186
22,50,3820,PDL0CKP,88.186,88.123,LK,63,2,15.7,6.7,3.6,4.7,0.6,989.1,88,186,88,123
23,52,3822,PDL0CKP,88.123,88.116,LK,7,2,19.9,4.7,10.4,4.8,0.0,139.3,88,123,88,116
24,54,3824,PDL0CKP,88.116,88.108,LRS,9,2,25.7,7.4,8.9,9.2,0.3,231.3,88,116,88,108
25,55,3825,PDL0CKP,88.108,88.106,JPL,2,2,17.1,3.3,5.6,7.3,0.8,34.2,88,108,88,106
26,56,3826,PDL0CKP,88.106,88.000,LRS,106,2,29.4,9.0,10.3,9.7,0.5,3116.4,88,106,88,0
27,58,3828,PDL0CKP,88.000,87.991,LRS,9,2,19.4,5.4,5.1,7.9,1.0,174.6,88,0,87,991

In [ ]:
ckp88 = ckp88.drop(['level_0','index'],axis=1)

In [ ]:
em88 = ckp88.iloc[2:13].reset_index()
em88 = em88.drop(['index'],axis=1)
em88

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726
1,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618
2,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600
3,PDL0CKP,88.600,88.400,LK,200,2,20.3,6.3,6.9,6.8,0.4,4060.0,88,600,88,400
4,PDL0CKP,88.400,88.200,LK,200,2,18.4,6.0,7.1,5.0,0.3,3680.0,88,400,88,200
5,PDL0CKP,88.200,88.186,LK,14,2,14.8,5.6,5.9,3.3,0.0,207.2,88,200,88,186
6,PDL0CKP,88.186,88.123,LK,63,2,15.7,6.7,3.6,4.7,0.6,989.1,88,186,88,123
7,PDL0CKP,88.123,88.116,LK,7,2,19.9,4.7,10.4,4.8,0.0,139.3,88,123,88,116
8,PDL0CKP,88.116,88.108,LRS,9,2,25.7,7.4,8.9,9.2,0.3,231.3,88,116,88,108
9,PDL0CKP,88.108,88.106,JPL,2,2,17.1,3.3,5.6,7.3,0.8,34.2,88,108,88,106
10,PDL0CKP,88.106,88.000,LRS,106,2,29.4,9.0,10.3,9.7,0.5,3116.4,88,106,88,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em88['pertinggian_pjg'] = em88['pertinggian']*em88['panjang']
em88['angkatan_pjg'] = em88['angkatan']*em88['panjang']
em88['lestrengan_pjg'] = em88['lestrengan']*em88['panjang']
em88['lebar_sepur_pjg'] = em88['lebar_sepur']*em88['panjang']

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em88.iloc[0:3] #600-800
em3 = em88.iloc[3:4] #400-600
em2 = em88.iloc[4:5] #200-400
em1 = em88.iloc[5:11] #200
em4

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
0,PDL0CKP,88.800,88.726,LK,74,2,26.8,11.5,8.5,6.1,0.6,1983.2,88,800,88,726,851.0,629.0,451.4,44.4
1,PDL0CKP,88.726,88.618,LRS,108,2,25.6,8.6,9.3,7.1,0.6,2764.8,88,726,88,618,928.8,1004.4,766.8,64.8
2,PDL0CKP,88.618,88.600,LK,19,2,23.3,9.0,4.0,10.2,0.0,442.7,88,618,88,600,171.0,76.0,193.8,0.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 7.83
lestrengan 1: 7.51
lebar sepur 1: 0.48
pertinggian 1: 7.8
angkatan 2: 7.1
lestrengan 2: 5.0
lebar sepur 2: 0.3
pertinggian 2: 6.0
angkatan 3: 6.9
lestrengan 3: 6.8
lebar sepur 3: 0.4
pertinggian 3: 6.3
angkatan 4: 8.55
lestrengan 4: 7.06
lebar sepur 4: 0.55
pertinggian 4: 9.75

In [ ]:
#bikin dataframe baru
em_baru88 ={'KM_Awal':[88.000,88.200,88.400,88.600],
      'KM_Akhir':[88.200,88.400,88.600,88.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em88 = pd.DataFrame(em_baru88)
df_em88

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     88.0      88.2      7.83        7.51         0.48         7.80
1     88.2      88.4      7.10        5.00         0.30         6.00
2     88.4      88.6      6.90        6.80         0.40         6.30
3     88.6      88.8      8.55        7.06         0.55         9.75

## ambil data km 89

In [ ]:
#ambil data dari km 89
km = em.groupby("km1")
ems89 = km.get_group(89).reset_index()
ems89

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1794,CKP0CD,89.904,90.000,LK,96,2,21.1,4.6,9.5,6.2,0.7,2025.6,89,904,90,0
1,1795,CKP0CD,89.832,89.904,LRS,72,2,17.5,4.0,6.0,6.8,0.7,1260.0,89,832,89,904
2,1796,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788
3,1797,CKP0CD,89.800,89.832,LK,33,2,22.0,5.4,9.2,6.8,0.6,726.0,89,800,89,832
4,1798,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668
5,1799,CKP0CD,89.787,89.800,LK,13,2,26.7,2.6,11.4,12.7,0.0,347.1,89,787,89,800
6,1800,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600
7,1801,PDL0CKP,89.600,89.500,LK,123,2,22.1,10.7,7.0,4.4,0.0,2718.3,89,600,89,500
8,1802,CKP0CD,89.600,89.787,LRS,188,2,22.1,6.4,8.9,6.3,0.5,4154.8,89,600,89,787
9,1803,PDL0CKP,89.500,89.488,LK,12,2,17.5,9.7,5.9,1.9,0.0,210.0,89,500,89,488
10,1804,PDL0CKP,89.488,89.448,LRS,40,2,27.5,11.8,10.4,5.3,0.0,1100.0,89,488,89,448
11,1805,PDL0CKP,89.448,89.400,LK,49,2,22.3,6.4,9.7,6.2,0.0,1092.7,89,448,89,400
12,1806,PDL0CKP,89.400,89.381,LK,19,2,16.2,5.8,6.6,3.7,0.0,307.8,89,400,89,381
13,1807,CKP0CD,89.400,89.600,LRS,200,2,21.0,5.3,9.9,5.1,0.6,4200.0,89,400,89,600
14,1808,PDL0CKP,89.381,89.326,LRS,55,2,23.0,9.9,7.3,5.9,0.0,1265.0,89,381,89,326
15,1809,PDL0CKP,89.326,89.200,LK,127,2,25.6,7.0,8.4,10.2,0.0,3251.2,89,326,89,200
16,1810,PDL0CKP,89.200,89.000,LK,200,2,23.1,6.8,7.3,8.5,0.5,4620.0,89,200,89,0
17,1811,CKP0CD,89.200,89.400,LRS,200,2,28.7,7.7,12.7,7.9,0.5,5740.0,89,200,89,400
18,1812,CKP0CD,89.092,89.200,LRS,108,2,33.3,8.1,14.4,10.2,0.6,3596.4,89,92,89,200
19,1813,CKP0CD,89.074,89.092,LK,19,2,21.6,3.8,8.8,8.5,0.4,410.4,89,74,89,92
20,1814,CKP0CD,89.052,89.074,LK,22,2,23.6,5.2,5.4,12.3,0.6,519.2,89,52,89,74
21,1815,PDL0CKP,89.000,88.978,LK,22,2,12.6,5.3,2.9,4.4,0.0,277.2,89,0,88,978
22,1816,CKP0CD,89.000,89.052,LK,53,2,24.0,6.9,7.3,9.2,0.7,1272.0,89,0,89,52
23,3777,CKP0CD,89.904,90.000,LK,96,2,21.1,4.6,9.5,6.2,0.7,2025.6,89,904,90,0
24,3778,CKP0CD,89.832,89.904,LRS,72,2,17.5,4.0,6.0,6.8,0.7,1260.0,89,832,89,904
25,3779,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788
26,3780,CKP0CD,89.800,89.832,LK,33,2,22.0,5.4,9.2,6.8,0.6,726.0,89,800,89,832
27,3781,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668
28,3782,CKP0CD,89.787,89.800,LK,13,2,26.7,2.6,11.4,12.7,0.0,347.1,89,787,89,800
29,3783,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600
30,3784,PDL0CKP,89.600,89.500,LK,123,2,22.1,10.7,7.0,4.4,0.0,2718.3,89,600,89,500
31,3785,CKP0CD,89.600,89.787,LRS,188,2,22.1,6.4,8.9,6.3,0.5,4154.8,89,600,89,787
32,3786,PDL0CKP,89.500,89.488,LK,12,2,17.5,9.7,5.9,1.9,0.0,210.0,89,500,89,488
33,3787,PDL0CKP,89.488,89.448,LRS,40,2,27.5,11.8,10.4,5.3,0.0,1100.0,89,488,89,448
34,3788,PDL0CKP,89.448,89.400,LK,49,2,22.3,6.4,9.7,6.2,0.0,1092.7,89,448,89,400
35,3789,PDL0CKP,89.400,89.381,LK,19,2,16.2,5.8,6.6,3.7,0.0,307.8,89,400,89,381
36,3790,CKP0CD,89.400,89.600,LRS,200,2,21.0,5.3,9.9,5.1,0.6,4200.0,89,400,89,600
37,3791,PDL0CKP,89.381,89.326,LRS,55,2,23.0,9.9,7.3,5.9,0.0,1265.0,89,381,89,326
38,3792,PDL0CKP,89.326,89.200,LK,127,2,25.6,7.0,8.4,10.2,0.0,3251.2,89,326,89,200
39,3793,PDL0CKP,89.200,89.000,LK,200,2,23.1,6.8,7.3,8.5,0.5,4620.0,89,200,89,0
40,3794,CKP0CD,89.200,89.400,LRS,200,2,28.7,7.7,12.7,7.9,0.5,5740.0,89,200,89,400
41,3795,CKP0CD,89.092,89.200,LRS,108,2,33.3,8.1,14.4,10.2,0.6,3596.4,89,92,89,200
42,3796,CKP0CD,89.074,89.092,LK,19,2,21.6,3.8,8.8,8.5,0.4,410.4,89,74,89,92
43,3797,CKP0CD,89.052,89.074,LK,22,2,23.6,5.2,5.4,12.3,0.6,519.2,89,52,89,74
44,3798,PDL0CKP,89.000,88.978,LK,22,2,12.6,5.3,2.9,4.4,0.0,277.2,89,0,88,978
45,3799,CKP0CD,89.000,89.052,LK,53,2,24.0,6.9,7.3,9.2,0.7,1272.0,89,0,89,52

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems89.groupby("antara")
ckp89 = antara.get_group('PDL0CKP').reset_index()
ckp89

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,2,1796,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788
1,4,1798,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668
2,6,1800,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600
3,7,1801,PDL0CKP,89.600,89.500,LK,123,2,22.1,10.7,7.0,4.4,0.0,2718.3,89,600,89,500
4,9,1803,PDL0CKP,89.500,89.488,LK,12,2,17.5,9.7,5.9,1.9,0.0,210.0,89,500,89,488
5,10,1804,PDL0CKP,89.488,89.448,LRS,40,2,27.5,11.8,10.4,5.3,0.0,1100.0,89,488,89,448
6,11,1805,PDL0CKP,89.448,89.400,LK,49,2,22.3,6.4,9.7,6.2,0.0,1092.7,89,448,89,400
7,12,1806,PDL0CKP,89.400,89.381,LK,19,2,16.2,5.8,6.6,3.7,0.0,307.8,89,400,89,381
8,14,1808,PDL0CKP,89.381,89.326,LRS,55,2,23.0,9.9,7.3,5.9,0.0,1265.0,89,381,89,326
9,15,1809,PDL0CKP,89.326,89.200,LK,127,2,25.6,7.0,8.4,10.2,0.0,3251.2,89,326,89,200
10,16,1810,PDL0CKP,89.200,89.000,LK,200,2,23.1,6.8,7.3,8.5,0.5,4620.0,89,200,89,0
11,21,1815,PDL0CKP,89.000,88.978,LK,22,2,12.6,5.3,2.9,4.4,0.0,277.2,89,0,88,978
12,25,3779,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788
13,27,3781,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668
14,29,3783,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600
15,30,3784,PDL0CKP,89.600,89.500,LK,123,2,22.1,10.7,7.0,4.4,0.0,2718.3,89,600,89,500
16,32,3786,PDL0CKP,89.500,89.488,LK,12,2,17.5,9.7,5.9,1.9,0.0,210.0,89,500,89,488
17,33,3787,PDL0CKP,89.488,89.448,LRS,40,2,27.5,11.8,10.4,5.3,0.0,1100.0,89,488,89,448
18,34,3788,PDL0CKP,89.448,89.400,LK,49,2,22.3,6.4,9.7,6.2,0.0,1092.7,89,448,89,400
19,35,3789,PDL0CKP,89.400,89.381,LK,19,2,16.2,5.8,6.6,3.7,0.0,307.8,89,400,89,381
20,37,3791,PDL0CKP,89.381,89.326,LRS,55,2,23.0,9.9,7.3,5.9,0.0,1265.0,89,381,89,326
21,38,3792,PDL0CKP,89.326,89.200,LK,127,2,25.6,7.0,8.4,10.2,0.0,3251.2,89,326,89,200
22,39,3793,PDL0CKP,89.200,89.000,LK,200,2,23.1,6.8,7.3,8.5,0.5,4620.0,89,200,89,0
23,44,3798,PDL0CKP,89.000,88.978,LK,22,2,12.6,5.3,2.9,4.4,0.0,277.2,89,0,88,978

In [ ]:
ckp89 = ckp89.drop(['level_0','index'],axis=1)

In [ ]:
em89 = ckp89.iloc[:11]
em89

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788
1,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668
2,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600
3,PDL0CKP,89.600,89.500,LK,123,2,22.1,10.7,7.0,4.4,0.0,2718.3,89,600,89,500
4,PDL0CKP,89.500,89.488,LK,12,2,17.5,9.7,5.9,1.9,0.0,210.0,89,500,89,488
5,PDL0CKP,89.488,89.448,LRS,40,2,27.5,11.8,10.4,5.3,0.0,1100.0,89,488,89,448
6,PDL0CKP,89.448,89.400,LK,49,2,22.3,6.4,9.7,6.2,0.0,1092.7,89,448,89,400
7,PDL0CKP,89.400,89.381,LK,19,2,16.2,5.8,6.6,3.7,0.0,307.8,89,400,89,381
8,PDL0CKP,89.381,89.326,LRS,55,2,23.0,9.9,7.3,5.9,0.0,1265.0,89,381,89,326
9,PDL0CKP,89.326,89.200,LK,127,2,25.6,7.0,8.4,10.2,0.0,3251.2,89,326,89,200
10,PDL0CKP,89.200,89.000,LK,200,2,23.1,6.8,7.3,8.5,0.5,4620.0,89,200,89,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em89['pertinggian_pjg'] = em89['pertinggian']*em89['panjang']
em89['angkatan_pjg'] = em89['angkatan']*em89['panjang']
em89['lestrengan_pjg'] = em89['lestrengan']*em89['panjang']
em89['lebar_sepur_pjg'] = em89['lebar_sepur']*em89['panjang']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em89.iloc[0:3] #600-800
em3 = em89.iloc[3:7] #400-600
em2 = em89.iloc[7:10] #200-400
em1 = em89.iloc[10:11] #200
em4

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
0,PDL0CKP,89.800,89.788,LK,12,2,24.8,5.9,10.8,7.5,0.6,297.6,89,800,89,788,70.8,129.6,90.0,7.2
1,PDL0CKP,89.788,89.668,LRS,120,2,27.0,8.7,8.7,9.5,0.0,3240.0,89,788,89,668,1044.0,1044.0,1140.0,0.0
2,PDL0CKP,89.668,89.600,LK,69,2,24.3,8.8,8.0,7.5,0.0,1676.7,89,668,89,600,607.2,552.0,517.5,0.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 7.3
lestrengan 1: 8.5
lebar sepur 1: 0.5
pertinggian 1: 6.8
angkatan 2: 7.97
lestrengan 2: 8.45
lebar sepur 2: 0.0
pertinggian 2: 7.72
angkatan 3: 9.12
lestrengan 3: 5.4
lebar sepur 3: 0.0
pertinggian 3: 11.09
angkatan 4: 8.63
lestrengan 4: 8.74
lebar sepur 4: 0.04
pertinggian 4: 8.61

In [ ]:
#bikin dataframe baru
em_baru89 ={'KM_Awal':[89.000,89.200,89.400,89.600],
      'KM_Akhir':[89.200,89.400,89.600,89.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em89 = pd.DataFrame(em_baru89)
df_em89

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     89.0      89.2      7.30        8.50         0.50         6.80
1     89.2      89.4      7.97        8.45         0.00         7.72
2     89.4      89.6      9.12        5.40         0.00        11.09
3     89.6      89.8      8.63        8.74         0.04         8.61

## ambil data km 90

In [ ]:
#ambil data dari km 90
km = em.groupby("km1")
ems = km.get_group(90).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1766,PDL0CKP,90.901,90.897,JPL,5,2,23.8,14.4,2.8,5.5,1.1,119.0,90,901,90,897
1,1767,PDL0CKP,90.897,90.800,LK,98,2,21.7,8.2,7.7,5.3,0.5,2126.6,90,897,90,800
2,1768,PDL0CKP,90.800,90.798,LK,3,2,5.4,2.1,2.4,0.9,0.0,16.2,90,800,90,798
3,1769,CKP0CD,90.800,91.000,LK,200,2,24.9,6.6,10.5,7.2,0.5,4980.0,90,800,91,0
4,1770,PDL0CKP,90.798,90.688,LK,109,2,24.2,8.1,6.8,8.9,0.4,2637.8,90,798,90,688
5,1771,PDL0CKP,90.688,90.630,LRS,58,2,26.6,9.0,6.7,10.5,0.4,1542.8,90,688,90,630
6,1772,CKP0CD,90.674,90.800,LK,126,2,18.9,4.9,5.5,8.1,0.5,2381.4,90,674,90,800
7,1773,CKP0CD,90.632,90.674,LRS,42,2,39.1,12.2,17.1,9.4,0.3,1642.2,90,632,90,674
8,1774,PDL0CKP,90.630,90.600,LK,31,2,24.4,7.1,9.1,7.7,0.6,756.4,90,630,90,600
9,1775,PDL0CKP,90.600,90.565,LK,35,2,24.9,6.6,11.4,6.4,0.5,871.5,90,600,90,565
10,1776,CKP0CD,90.600,90.632,LK,33,2,24.4,5.8,10.1,8.1,0.4,805.2,90,600,90,632
11,1777,PDL0CKP,90.565,90.550,LRS,15,2,17.3,6.6,2.7,8.1,0.0,259.5,90,565,90,550
12,1778,PDL0CKP,90.550,90.400,LK,151,2,20.8,6.2,6.8,7.2,0.6,3140.8,90,550,90,400
13,1779,CKP0CD,90.529,90.600,LK,71,2,28.7,8.4,11.5,8.2,0.5,2037.7,90,529,90,600
14,1780,CKP0CD,90.484,90.529,LRS,45,2,19.9,4.8,9.6,4.8,0.7,895.5,90,484,90,529
15,1781,PDL0CKP,90.400,90.378,LK,22,2,25.7,5.7,7.8,11.7,0.5,565.4,90,400,90,378
16,1782,CKP0CD,90.400,90.484,LK,85,2,22.4,5.3,9.2,7.4,0.5,1904.0,90,400,90,484
17,1783,PDL0CKP,90.378,90.363,LRS,15,2,18.4,4.9,6.1,7.4,0.0,276.0,90,378,90,363
18,1784,CKP0CD,90.377,90.400,LK,23,2,28.3,4.7,10.9,12.8,0.0,650.9,90,377,90,400
19,1785,PDL0CKP,90.363,90.200,LK,164,2,17.3,4.6,3.7,8.3,0.6,2837.2,90,363,90,200
20,1786,CKP0CD,90.279,90.377,LK,98,2,26.7,7.8,11.5,7.0,0.4,2616.6,90,279,90,377
21,1787,CKP0CD,90.239,90.279,LRS,40,2,16.1,3.7,5.0,6.7,0.7,644.0,90,239,90,279
22,1788,PDL0CKP,90.200,90.000,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0
23,1789,CKP0CD,90.200,90.239,LK,40,2,21.1,3.6,10.7,6.2,0.6,844.0,90,200,90,239
24,1790,CKP0CD,90.185,90.200,LK,15,2,25.5,5.9,13.6,6.0,0.0,382.5,90,185,90,200
25,1791,CKP0CD,90.176,90.185,BH,9,2,21.2,3.7,2.1,15.3,0.0,190.8,90,176,90,185
26,1792,PDL0CKP,90.000,89.800,LK,200,2,20.7,7.0,4.8,8.4,0.4,4140.0,90,0,89,800
27,1793,CKP0CD,90.000,90.176,LK,177,2,16.7,4.0,7.2,5.3,0.2,2955.9,90,0,90,176
28,3749,PDL0CKP,90.901,90.897,JPL,5,2,23.8,14.4,2.8,5.5,1.1,119.0,90,901,90,897
29,3750,PDL0CKP,90.897,90.800,LK,98,2,21.7,8.2,7.7,5.3,0.5,2126.6,90,897,90,800
30,3751,PDL0CKP,90.800,90.798,LK,3,2,5.4,2.1,2.4,0.9,0.0,16.2,90,800,90,798
31,3752,CKP0CD,90.800,91.000,LK,200,2,24.9,6.6,10.5,7.2,0.5,4980.0,90,800,91,0
32,3753,PDL0CKP,90.798,90.688,LK,109,2,24.2,8.1,6.8,8.9,0.4,2637.8,90,798,90,688
33,3754,PDL0CKP,90.688,90.630,LRS,58,2,26.6,9.0,6.7,10.5,0.4,1542.8,90,688,90,630
34,3755,CKP0CD,90.674,90.800,LK,126,2,18.9,4.9,5.5,8.1,0.5,2381.4,90,674,90,800
35,3756,CKP0CD,90.632,90.674,LRS,42,2,39.1,12.2,17.1,9.4,0.3,1642.2,90,632,90,674
36,3757,PDL0CKP,90.630,90.600,LK,31,2,24.4,7.1,9.1,7.7,0.6,756.4,90,630,90,600
37,3758,PDL0CKP,90.600,90.565,LK,35,2,24.9,6.6,11.4,6.4,0.5,871.5,90,600,90,565
38,3759,CKP0CD,90.600,90.632,LK,33,2,24.4,5.8,10.1,8.1,0.4,805.2,90,600,90,632
39,3760,PDL0CKP,90.565,90.550,LRS,15,2,17.3,6.6,2.7,8.1,0.0,259.5,90,565,90,550
40,3761,PDL0CKP,90.550,90.400,LK,151,2,20.8,6.2,6.8,7.2,0.6,3140.8,90,550,90,400
41,3762,CKP0CD,90.529,90.600,LK,71,2,28.7,8.4,11.5,8.2,0.5,2037.7,90,529,90,600
42,3763,CKP0CD,90.484,90.529,LRS,45,2,19.9,4.8,9.6,4.8,0.7,895.5,90,484,90,529
43,3764,PDL0CKP,90.400,90.378,LK,22,2,25.7,5.7,7.8,11.7,0.5,565.4,90,400,90,378
44,3765,CKP0CD,90.400,90.484,LK,85,2,22.4,5.3,9.2,7.4,0.5,1904.0,90,400,90,484
45,3766,PDL0CKP,90.378,90.363,LRS,15,2,18.4,4.9,6.1,7.4,0.0,276.0,90,378,90,363
46,3767,CKP0CD,90.377,90.400,LK,23,2,28.3,4.7,10.9,12.8,0.0,650.9,90,377,90,400
47,3768,PDL0CKP,90.363,90.200,LK,164,2,17.3,4.6,3.7,8.3,0.6,2837.2,90,363,90,200
48,3769,CKP0CD,90.279,90.377,LK,98,2,26.7,7.8,11.5,7.0,0.4,2616.6,90,279,90,377
49,3770,CKP0CD,90.239,90.279,LRS,40,2,16.1,3.7,5.0,6.7,0.7,644.0,90,239,90,279
50,3771,PDL0CKP,90.200,90.000,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0
51,3772,CKP0CD,90.200,90.239,LK,40,2,21.1,3.6,10.7,6.2,0.6,844.0,90,200,90,239
52,3773,CKP0CD,90.185,90.200,LK,15,2,25.5,5.9,13.6,6.0,0.0,382.5,90,185,90,200
53,3774,CKP0CD,90.176,90.185,BH,9,2,21.2,3.7,2.1,15.3,0.0,190.8,90,176,90,185
54,3775,PDL0CKP,90.000,89.800,LK,200,2,20.7,7.0,4.8,8.4,0.4,4140.0,90,0,89,800
55,3776,CKP0CD,90.000,90.176,LK,177,2,16.7,4.0,7.2,5.3,0.2,2955.9,90,0,90,176

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1766,PDL0CKP,90.901,90.897,JPL,5,2,23.8,14.4,2.8,5.5,1.1,119.0,90,901,90,897
1,1,1767,PDL0CKP,90.897,90.800,LK,98,2,21.7,8.2,7.7,5.3,0.5,2126.6,90,897,90,800
2,2,1768,PDL0CKP,90.800,90.798,LK,3,2,5.4,2.1,2.4,0.9,0.0,16.2,90,800,90,798
3,4,1770,PDL0CKP,90.798,90.688,LK,109,2,24.2,8.1,6.8,8.9,0.4,2637.8,90,798,90,688
4,5,1771,PDL0CKP,90.688,90.630,LRS,58,2,26.6,9.0,6.7,10.5,0.4,1542.8,90,688,90,630
5,8,1774,PDL0CKP,90.630,90.600,LK,31,2,24.4,7.1,9.1,7.7,0.6,756.4,90,630,90,600
6,9,1775,PDL0CKP,90.600,90.565,LK,35,2,24.9,6.6,11.4,6.4,0.5,871.5,90,600,90,565
7,11,1777,PDL0CKP,90.565,90.550,LRS,15,2,17.3,6.6,2.7,8.1,0.0,259.5,90,565,90,550
8,12,1778,PDL0CKP,90.550,90.400,LK,151,2,20.8,6.2,6.8,7.2,0.6,3140.8,90,550,90,400
9,15,1781,PDL0CKP,90.400,90.378,LK,22,2,25.7,5.7,7.8,11.7,0.5,565.4,90,400,90,378
10,17,1783,PDL0CKP,90.378,90.363,LRS,15,2,18.4,4.9,6.1,7.4,0.0,276.0,90,378,90,363
11,19,1785,PDL0CKP,90.363,90.200,LK,164,2,17.3,4.6,3.7,8.3,0.6,2837.2,90,363,90,200
12,22,1788,PDL0CKP,90.200,90.000,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0
13,26,1792,PDL0CKP,90.000,89.800,LK,200,2,20.7,7.0,4.8,8.4,0.4,4140.0,90,0,89,800
14,28,3749,PDL0CKP,90.901,90.897,JPL,5,2,23.8,14.4,2.8,5.5,1.1,119.0,90,901,90,897
15,29,3750,PDL0CKP,90.897,90.800,LK,98,2,21.7,8.2,7.7,5.3,0.5,2126.6,90,897,90,800
16,30,3751,PDL0CKP,90.800,90.798,LK,3,2,5.4,2.1,2.4,0.9,0.0,16.2,90,800,90,798
17,32,3753,PDL0CKP,90.798,90.688,LK,109,2,24.2,8.1,6.8,8.9,0.4,2637.8,90,798,90,688
18,33,3754,PDL0CKP,90.688,90.630,LRS,58,2,26.6,9.0,6.7,10.5,0.4,1542.8,90,688,90,630
19,36,3757,PDL0CKP,90.630,90.600,LK,31,2,24.4,7.1,9.1,7.7,0.6,756.4,90,630,90,600
20,37,3758,PDL0CKP,90.600,90.565,LK,35,2,24.9,6.6,11.4,6.4,0.5,871.5,90,600,90,565
21,39,3760,PDL0CKP,90.565,90.550,LRS,15,2,17.3,6.6,2.7,8.1,0.0,259.5,90,565,90,550
22,40,3761,PDL0CKP,90.550,90.400,LK,151,2,20.8,6.2,6.8,7.2,0.6,3140.8,90,550,90,400
23,43,3764,PDL0CKP,90.400,90.378,LK,22,2,25.7,5.7,7.8,11.7,0.5,565.4,90,400,90,378
24,45,3766,PDL0CKP,90.378,90.363,LRS,15,2,18.4,4.9,6.1,7.4,0.0,276.0,90,378,90,363
25,47,3768,PDL0CKP,90.363,90.200,LK,164,2,17.3,4.6,3.7,8.3,0.6,2837.2,90,363,90,200
26,50,3771,PDL0CKP,90.200,90.000,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0
27,54,3775,PDL0CKP,90.000,89.800,LK,200,2,20.7,7.0,4.8,8.4,0.4,4140.0,90,0,89,800

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em90 = ckp.iloc[2:13].reset_index()
em90 = em90.drop(['index'],axis=1)
em90

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,90.800,90.798,LK,3,2,5.4,2.1,2.4,0.9,0.0,16.2,90,800,90,798
1,PDL0CKP,90.798,90.688,LK,109,2,24.2,8.1,6.8,8.9,0.4,2637.8,90,798,90,688
2,PDL0CKP,90.688,90.630,LRS,58,2,26.6,9.0,6.7,10.5,0.4,1542.8,90,688,90,630
3,PDL0CKP,90.630,90.600,LK,31,2,24.4,7.1,9.1,7.7,0.6,756.4,90,630,90,600
4,PDL0CKP,90.600,90.565,LK,35,2,24.9,6.6,11.4,6.4,0.5,871.5,90,600,90,565
5,PDL0CKP,90.565,90.550,LRS,15,2,17.3,6.6,2.7,8.1,0.0,259.5,90,565,90,550
6,PDL0CKP,90.550,90.400,LK,151,2,20.8,6.2,6.8,7.2,0.6,3140.8,90,550,90,400
7,PDL0CKP,90.400,90.378,LK,22,2,25.7,5.7,7.8,11.7,0.5,565.4,90,400,90,378
8,PDL0CKP,90.378,90.363,LRS,15,2,18.4,4.9,6.1,7.4,0.0,276.0,90,378,90,363
9,PDL0CKP,90.363,90.200,LK,164,2,17.3,4.6,3.7,8.3,0.6,2837.2,90,363,90,200
10,PDL0CKP,90.200,90.000,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em90['pertinggian_pjg'] = em90['pertinggian']*em90['panjang']
em90['angkatan_pjg'] = em90['angkatan']*em90['panjang']
em90['lestrengan_pjg'] = em90['lestrengan']*em90['panjang']
em90['lebar_sepur_pjg'] = em90['lebar_sepur']*em90['panjang']

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em90.iloc[0:4] #600-800
em3 = em90.iloc[4:7] #400-600
em2 = em90.iloc[7:10] #200-400
em1 = em90.iloc[10:11] #200
em1

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
10,PDL0CKP,90.2,90.0,LK,200,2,18.7,5.1,4.5,8.5,0.5,3740.0,90,200,90,0,1020.0,900.0,1700.0,100.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 4.5
lestrengan 1: 8.5
lebar sepur 1: 0.5
pertinggian 1: 5.1
angkatan 2: 4.35
lestrengan 2: 8.65
lebar sepur 2: 0.55
pertinggian 2: 4.77
angkatan 3: 7.33
lestrengan 3: 7.16
lebar sepur 3: 0.54
pertinggian 3: 6.33
angkatan 4: 7.1
lestrengan 4: 9.1
lebar sepur 4: 0.43
pertinggian 4: 8.16

In [ ]:
#bikin dataframe baru
em_baru90 ={'KM_Awal':[90.000,90.200,90.400,90.600],
      'KM_Akhir':[90.200,90.400,90.600,90.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em90 = pd.DataFrame(em_baru90)
df_em90

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     90.0      90.2      4.50        8.50         0.50         5.10
1     90.2      90.4      4.35        8.65         0.55         4.77
2     90.4      90.6      7.33        7.16         0.54         6.33
3     90.6      90.8      7.10        9.10         0.43         8.16

## ambil data km 91

In [ ]:
#ambil data dari km 91
km = em.groupby("km1")
ems = km.get_group(91).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1722,PDL0CKP,91.948,91.938,LK,10,2,9.5,2.9,2.3,3.8,0.4,95.0,91,948,91,938
1,1723,PDL0CKP,91.938,91.888,LRS,50,2,19.0,6.7,3.2,8.4,0.7,950.0,91,938,91,888
2,1724,CKP0CD,91.932,92.000,LK,68,2,22.9,8.3,8.9,5.2,0.6,1557.2,91,932,92,0
3,1725,CKP0CD,91.901,91.932,LK,32,2,33.6,10.0,11.1,12.5,0.0,1075.2,91,901,91,932
4,1726,PDL0CKP,91.888,91.818,LK,70,2,19.9,6.5,5.4,7.6,0.4,1393.0,91,888,91,818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,3744,PDL0CKP,91.083,91.000,LK,84,2,21.6,5.6,6.2,9.2,0.5,1814.4,91,83,91,0
84,3745,CKP0CD,91.045,91.100,LK,56,2,31.0,6.2,14.2,10.3,0.4,1736.0,91,45,91,100
85,3746,CKP0CD,91.023,91.045,LK,22,2,23.6,10.3,9.0,4.3,0.0,519.2,91,23,91,45
86,3747,PDL0CKP,91.000,90.901,LK,99,2,25.3,10.9,9.7,4.3,0.5,2504.7,91,0,90,901
87,3748,CKP0CD,91.000,91.023,LK,24,2,19.4,9.7,7.3,2.4,0.0,465.6,91,0,91,23

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1722,PDL0CKP,91.948,91.938,LK,10,2,9.5,2.9,2.3,3.8,0.4,95.0,91,948,91,938
1,1,1723,PDL0CKP,91.938,91.888,LRS,50,2,19.0,6.7,3.2,8.4,0.7,950.0,91,938,91,888
2,4,1726,PDL0CKP,91.888,91.818,LK,70,2,19.9,6.5,5.4,7.6,0.4,1393.0,91,888,91,818
3,6,1728,PDL0CKP,91.818,91.811,LRS,7,2,14.4,7.4,4.9,2.1,0.0,100.8,91,818,91,811
4,7,1729,PDL0CKP,91.811,91.800,WSL,12,2,23.9,7.5,6.3,10.1,0.0,286.8,91,811,91,800
5,8,1730,PDL0CKP,91.800,91.777,WSL,23,2,32.8,9.7,6.3,16.3,0.6,754.4,91,800,91,777
6,11,1733,PDL0CKP,91.777,91.767,LK,10,2,26.1,5.8,5.5,14.7,0.2,261.0,91,777,91,767
7,12,1734,PDL0CKP,91.767,91.731,WSL,37,2,29.0,6.9,10.6,11.5,0.0,1073.0,91,767,91,731
8,13,1735,PDL0CKP,91.731,91.703,LK,28,2,30.1,11.3,8.9,9.2,0.6,842.8,91,731,91,703
9,14,1736,PDL0CKP,91.703,91.653,LRS,50,2,31.6,7.9,14.3,8.9,0.5,1580.0,91,703,91,653
10,15,1737,PDL0CKP,91.653,91.600,LK,54,2,28.1,6.6,12.0,8.9,0.6,1517.4,91,653,91,600
11,16,1738,PDL0CKP,91.600,91.594,LK,6,2,16.0,3.1,9.2,3.7,0.0,96.0,91,600,91,594
12,18,1740,PDL0CKP,91.594,91.588,LK,6,2,19.9,5.2,10.3,4.4,0.0,119.4,91,594,91,588
13,19,1741,PDL0CKP,91.588,91.498,LRS,90,2,21.2,7.3,6.8,6.7,0.4,1908.0,91,588,91,498
14,21,1743,PDL0CKP,91.498,91.405,LK,94,2,20.7,5.2,6.6,8.6,0.2,1945.8,91,498,91,405
15,24,1746,PDL0CKP,91.405,91.400,LK,6,2,8.6,2.8,4.9,0.8,0.0,51.6,91,405,91,400
16,25,1747,PDL0CKP,91.400,91.217,LK,184,2,20.7,7.2,7.1,6.4,0.0,3808.8,91,400,91,217
17,29,1751,PDL0CKP,91.217,91.200,LK,17,2,19.2,3.9,5.5,9.8,0.0,326.4,91,217,91,200
18,30,1752,PDL0CKP,91.200,91.195,LK,5,2,8.0,4.6,2.2,1.1,0.0,40.0,91,200,91,195
19,32,1754,PDL0CKP,91.195,91.182,LRS,14,2,16.0,5.3,5.5,5.2,0.0,224.0,91,195,91,182
20,33,1755,PDL0CKP,91.182,91.151,WSL,31,2,35.2,9.1,7.2,18.4,0.5,1091.2,91,182,91,151
21,34,1756,PDL0CKP,91.151,91.134,LRS,17,2,27.5,5.6,9.2,11.9,0.8,467.5,91,151,91,134
22,35,1757,PDL0CKP,91.134,91.099,WSL,36,2,29.7,5.6,7.1,16.4,0.5,1069.2,91,134,91,99
23,38,1760,PDL0CKP,91.099,91.083,LRS,16,2,21.1,6.3,3.9,10.1,0.8,337.6,91,99,91,83
24,39,1761,PDL0CKP,91.083,91.000,LK,84,2,21.6,5.6,6.2,9.2,0.5,1814.4,91,83,91,0
25,42,1764,PDL0CKP,91.000,90.901,LK,99,2,25.3,10.9,9.7,4.3,0.5,2504.7,91,0,90,901
26,44,3705,PDL0CKP,91.948,91.938,LK,10,2,9.5,2.9,2.3,3.8,0.4,95.0,91,948,91,938
27,45,3706,PDL0CKP,91.938,91.888,LRS,50,2,19.0,6.7,3.2,8.4,0.7,950.0,91,938,91,888
28,48,3709,PDL0CKP,91.888,91.818,LK,70,2,19.9,6.5,5.4,7.6,0.4,1393.0,91,888,91,818
29,50,3711,PDL0CKP,91.818,91.811,LRS,7,2,14.4,7.4,4.9,2.1,0.0,100.8,91,818,91,811
30,51,3712,PDL0CKP,91.811,91.800,WSL,12,2,23.9,7.5,6.3,10.1,0.0,286.8,91,811,91,800
31,52,3713,PDL0CKP,91.800,91.777,WSL,23,2,32.8,9.7,6.3,16.3,0.6,754.4,91,800,91,777
32,55,3716,PDL0CKP,91.777,91.767,LK,10,2,26.1,5.8,5.5,14.7,0.2,261.0,91,777,91,767
33,56,3717,PDL0CKP,91.767,91.731,WSL,37,2,29.0,6.9,10.6,11.5,0.0,1073.0,91,767,91,731
34,57,3718,PDL0CKP,91.731,91.703,LK,28,2,30.1,11.3,8.9,9.2,0.6,842.8,91,731,91,703
35,58,3719,PDL0CKP,91.703,91.653,LRS,50,2,31.6,7.9,14.3,8.9,0.5,1580.0,91,703,91,653
36,59,3720,PDL0CKP,91.653,91.600,LK,54,2,28.1,6.6,12.0,8.9,0.6,1517.4,91,653,91,600
37,60,3721,PDL0CKP,91.600,91.594,LK,6,2,16.0,3.1,9.2,3.7,0.0,96.0,91,600,91,594
38,62,3723,PDL0CKP,91.594,91.588,LK,6,2,19.9,5.2,10.3,4.4,0.0,119.4,91,594,91,588
39,63,3724,PDL0CKP,91.588,91.498,LRS,90,2,21.2,7.3,6.8,6.7,0.4,1908.0,91,588,91,498
40,65,3726,PDL0CKP,91.498,91.405,LK,94,2,20.7,5.2,6.6,8.6,0.2,1945.8,91,498,91,405
41,68,3729,PDL0CKP,91.405,91.400,LK,6,2,8.6,2.8,4.9,0.8,0.0,51.6,91,405,91,400
42,69,3730,PDL0CKP,91.400,91.217,LK,184,2,20.7,7.2,7.1,6.4,0.0,3808.8,91,400,91,217
43,73,3734,PDL0CKP,91.217,91.200,LK,17,2,19.2,3.9,5.5,9.8,0.0,326.4,91,217,91,200
44,74,3735,PDL0CKP,91.200,91.195,LK,5,2,8.0,4.6,2.2,1.1,0.0,40.0,91,200,91,195
45,76,3737,PDL0CKP,91.195,91.182,LRS,14,2,16.0,5.3,5.5,5.2,0.0,224.0,91,195,91,182
46,77,3738,PDL0CKP,91.182,91.151,WSL,31,2,35.2,9.1,7.2,18.4,0.5,1091.2,91,182,91,151
47,78,3739,PDL0CKP,91.151,91.134,LRS,17,2,27.5,5.6,9.2,11.9,0.8,467.5,91,151,91,134
48,79,3740,PDL0CKP,91.134,91.099,WSL,36,2,29.7,5.6,7.1,16.4,0.5,1069.2,91,134,91,99
49,82,3743,PDL0CKP,91.099,91.083,LRS,16,2,21.1,6.3,3.9,10.1,0.8,337.6,91,99,91,83
50,83,3744,PDL0CKP,91.083,91.000,LK,84,2,21.6,5.6,6.2,9.2,0.5,1814.4,91,83,91,0
51,86,3747,PDL0CKP,91.000,90.901,LK,99,2,25.3,10.9,9.7,4.3,0.5,2504.7,91,0,90,901

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em91 = ckp.iloc[5:25].reset_index()
em91 = em91.drop(['index'],axis=1)
em91

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,91.800,91.777,WSL,23,2,32.8,9.7,6.3,16.3,0.6,754.4,91,800,91,777
1,PDL0CKP,91.777,91.767,LK,10,2,26.1,5.8,5.5,14.7,0.2,261.0,91,777,91,767
2,PDL0CKP,91.767,91.731,WSL,37,2,29.0,6.9,10.6,11.5,0.0,1073.0,91,767,91,731
3,PDL0CKP,91.731,91.703,LK,28,2,30.1,11.3,8.9,9.2,0.6,842.8,91,731,91,703
4,PDL0CKP,91.703,91.653,LRS,50,2,31.6,7.9,14.3,8.9,0.5,1580.0,91,703,91,653
5,PDL0CKP,91.653,91.600,LK,54,2,28.1,6.6,12.0,8.9,0.6,1517.4,91,653,91,600
6,PDL0CKP,91.600,91.594,LK,6,2,16.0,3.1,9.2,3.7,0.0,96.0,91,600,91,594
7,PDL0CKP,91.594,91.588,LK,6,2,19.9,5.2,10.3,4.4,0.0,119.4,91,594,91,588
8,PDL0CKP,91.588,91.498,LRS,90,2,21.2,7.3,6.8,6.7,0.4,1908.0,91,588,91,498
9,PDL0CKP,91.498,91.405,LK,94,2,20.7,5.2,6.6,8.6,0.2,1945.8,91,498,91,405
10,PDL0CKP,91.405,91.400,LK,6,2,8.6,2.8,4.9,0.8,0.0,51.6,91,405,91,400
11,PDL0CKP,91.400,91.217,LK,184,2,20.7,7.2,7.1,6.4,0.0,3808.8,91,400,91,217
12,PDL0CKP,91.217,91.200,LK,17,2,19.2,3.9,5.5,9.8,0.0,326.4,91,217,91,200
13,PDL0CKP,91.200,91.195,LK,5,2,8.0,4.6,2.2,1.1,0.0,40.0,91,200,91,195
14,PDL0CKP,91.195,91.182,LRS,14,2,16.0,5.3,5.5,5.2,0.0,224.0,91,195,91,182
15,PDL0CKP,91.182,91.151,WSL,31,2,35.2,9.1,7.2,18.4,0.5,1091.2,91,182,91,151
16,PDL0CKP,91.151,91.134,LRS,17,2,27.5,5.6,9.2,11.9,0.8,467.5,91,151,91,134
17,PDL0CKP,91.134,91.099,WSL,36,2,29.7,5.6,7.1,16.4,0.5,1069.2,91,134,91,99
18,PDL0CKP,91.099,91.083,LRS,16,2,21.1,6.3,3.9,10.1,0.8,337.6,91,99,91,83
19,PDL0CKP,91.083,91.000,LK,84,2,21.6,5.6,6.2,9.2,0.5,1814.4,91,83,91,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em91['pertinggian_pjg'] = em91['pertinggian']*em91['panjang']
em91['angkatan_pjg'] = em91['angkatan']*em91['panjang']
em91['lestrengan_pjg'] = em91['lestrengan']*em91['panjang']
em91['lebar_sepur_pjg'] = em91['lebar_sepur']*em91['panjang']

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em91.iloc[0:6] #600-800
em3 = em91.iloc[6:11] #400-600
em2 = em91.iloc[11:13] #200-400
em1 = em91.iloc[13:20] #200
em1

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
13,PDL0CKP,91.200,91.195,LK,5,2,8.0,4.6,2.2,1.1,0.0,40.0,91,200,91,195,23.0,11.0,5.5,0.0
14,PDL0CKP,91.195,91.182,LRS,14,2,16.0,5.3,5.5,5.2,0.0,224.0,91,195,91,182,74.2,77.0,72.8,0.0
15,PDL0CKP,91.182,91.151,WSL,31,2,35.2,9.1,7.2,18.4,0.5,1091.2,91,182,91,151,282.1,223.2,570.4,15.5
16,PDL0CKP,91.151,91.134,LRS,17,2,27.5,5.6,9.2,11.9,0.8,467.5,91,151,91,134,95.2,156.4,202.3,13.6
17,PDL0CKP,91.134,91.099,WSL,36,2,29.7,5.6,7.1,16.4,0.5,1069.2,91,134,91,99,201.6,255.6,590.4,18.0
18,PDL0CKP,91.099,91.083,LRS,16,2,21.1,6.3,3.9,10.1,0.8,337.6,91,99,91,83,100.8,62.4,161.6,12.8
19,PDL0CKP,91.083,91.000,LK,84,2,21.6,5.6,6.2,9.2,0.5,1814.4,91,83,91,0,470.4,520.8,772.8,42.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 6.53
lestrengan 1: 11.88
lebar sepur 1: 0.51
pertinggian 1: 6.24
angkatan 2: 7.0
lestrengan 2: 6.72
lebar sepur 2: 0.0
pertinggian 2: 6.96
angkatan 3: 6.89
lestrengan 3: 7.32
lebar sepur 3: 0.27
pertinggian 3: 6.06
angkatan 4: 11.02
lestrengan 4: 10.65
lebar sepur 4: 0.45
pertinggian 4: 8.02

In [ ]:
#bikin dataframe baru
em_baru91 ={'KM_Awal':[91.000,91.200,91.400,91.600],
      'KM_Akhir':[91.200,91.400,91.600,91.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em91 = pd.DataFrame(em_baru91)
df_em91

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     91.0      91.2      6.53       11.88         0.51         6.24
1     91.2      91.4      7.00        6.72         0.00         6.96
2     91.4      91.6      6.89        7.32         0.27         6.06
3     91.6      91.8     11.02       10.65         0.45         8.02

## ambil data km 92

In [ ]:
#ambil data dari km 92
km = em.groupby("km1")
ems = km.get_group(92).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1696,PDL0CKP,92.923,92.800,LRS,124,2,15.0,4.1,2.6,8.1,0.3,1860.0,92,923,92,800
1,1697,CKP0CD,92.890,93.000,LK,110,2,19.8,4.9,7.1,7.2,0.7,2178.0,92,890,93,0
2,1698,PDL0CKP,92.800,92.615,LRS,185,2,23.0,6.8,6.3,9.5,0.4,4255.0,92,800,92,615
3,1699,CKP0CD,92.800,92.890,LK,91,2,21.5,6.6,9.0,5.3,0.6,1956.5,92,800,92,890
4,1700,PDL0CKP,92.615,92.600,LK,16,2,36.6,11.3,18.5,6.7,0.0,585.6,92,615,92,600
5,1701,PDL0CKP,92.600,92.400,LK,200,2,23.7,8.4,8.3,6.5,0.6,4740.0,92,600,92,400
6,1702,CKP0CD,92.600,92.800,LK,200,2,24.2,7.0,9.9,6.7,0.6,4840.0,92,600,92,800
7,1703,CKP0CD,92.433,92.600,LK,167,2,23.0,6.0,11.1,5.4,0.5,3841.0,92,433,92,600
8,1704,CKP0CD,92.426,92.433,BH,8,2,16.0,8.2,6.6,1.2,0.0,128.0,92,426,92,433
9,1705,PDL0CKP,92.400,92.300,LK,100,2,26.4,11.4,10.6,3.9,0.5,2640.0,92,400,92,300
10,1706,CKP0CD,92.400,92.426,LK,26,2,17.2,5.8,7.4,3.4,0.6,447.2,92,400,92,426
11,1707,CKP0CD,92.341,92.400,LK,59,2,22.8,7.1,8.7,6.4,0.6,1345.2,92,341,92,400
12,1708,CKP0CD,92.330,92.341,JPL,11,2,26.0,9.1,13.1,3.8,0.0,286.0,92,330,92,341
13,1709,PDL0CKP,92.300,92.288,JPL,13,2,28.7,6.0,16.8,5.9,0.0,373.1,92,300,92,288
14,1710,PDL0CKP,92.288,92.282,LK,6,2,16.3,3.6,7.8,4.9,0.0,97.8,92,288,92,282
15,1711,PDL0CKP,92.282,92.216,LK,67,2,23.7,11.6,4.7,6.7,0.7,1587.9,92,282,92,216
16,1712,CKP0CD,92.262,92.330,LK,68,2,25.6,6.1,10.7,8.5,0.4,1740.8,92,262,92,330
17,1713,CKP0CD,92.222,92.262,LRS,40,2,26.9,9.5,7.9,9.0,0.5,1076.0,92,222,92,262
18,1714,PDL0CKP,92.216,92.200,LK,16,2,17.3,8.0,1.4,7.2,0.7,276.8,92,216,92,200
19,1715,CKP0CD,92.203,92.222,LK,20,2,31.3,5.2,14.9,10.5,0.7,626.0,92,203,92,222
20,1716,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133
21,1717,CKP0CD,92.200,92.203,LK,4,2,22.2,1.2,11.5,9.4,0.1,88.8,92,200,92,203
22,1718,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98
23,1719,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0
24,1720,PDL0CKP,92.000,91.948,LK,52,2,14.4,4.7,4.7,4.2,0.8,748.8,92,0,91,948
25,1721,CKP0CD,92.000,92.200,LK,200,2,23.8,7.2,9.4,6.5,0.6,4760.0,92,0,92,200
26,3679,PDL0CKP,92.923,92.800,LRS,124,2,15.0,4.1,2.6,8.1,0.3,1860.0,92,923,92,800
27,3680,CKP0CD,92.890,93.000,LK,110,2,19.8,4.9,7.1,7.2,0.7,2178.0,92,890,93,0
28,3681,PDL0CKP,92.800,92.615,LRS,185,2,23.0,6.8,6.3,9.5,0.4,4255.0,92,800,92,615
29,3682,CKP0CD,92.800,92.890,LK,91,2,21.5,6.6,9.0,5.3,0.6,1956.5,92,800,92,890
30,3683,PDL0CKP,92.615,92.600,LK,16,2,36.6,11.3,18.5,6.7,0.0,585.6,92,615,92,600
31,3684,PDL0CKP,92.600,92.400,LK,200,2,23.7,8.4,8.3,6.5,0.6,4740.0,92,600,92,400
32,3685,CKP0CD,92.600,92.800,LK,200,2,24.2,7.0,9.9,6.7,0.6,4840.0,92,600,92,800
33,3686,CKP0CD,92.433,92.600,LK,167,2,23.0,6.0,11.1,5.4,0.5,3841.0,92,433,92,600
34,3687,CKP0CD,92.426,92.433,BH,8,2,16.0,8.2,6.6,1.2,0.0,128.0,92,426,92,433
35,3688,PDL0CKP,92.400,92.300,LK,100,2,26.4,11.4,10.6,3.9,0.5,2640.0,92,400,92,300
36,3689,CKP0CD,92.400,92.426,LK,26,2,17.2,5.8,7.4,3.4,0.6,447.2,92,400,92,426
37,3690,CKP0CD,92.341,92.400,LK,59,2,22.8,7.1,8.7,6.4,0.6,1345.2,92,341,92,400
38,3691,CKP0CD,92.330,92.341,JPL,11,2,26.0,9.1,13.1,3.8,0.0,286.0,92,330,92,341
39,3692,PDL0CKP,92.300,92.288,JPL,13,2,28.7,6.0,16.8,5.9,0.0,373.1,92,300,92,288
40,3693,PDL0CKP,92.288,92.282,LK,6,2,16.3,3.6,7.8,4.9,0.0,97.8,92,288,92,282
41,3694,PDL0CKP,92.282,92.216,LK,67,2,23.7,11.6,4.7,6.7,0.7,1587.9,92,282,92,216
42,3695,CKP0CD,92.262,92.330,LK,68,2,25.6,6.1,10.7,8.5,0.4,1740.8,92,262,92,330
43,3696,CKP0CD,92.222,92.262,LRS,40,2,26.9,9.5,7.9,9.0,0.5,1076.0,92,222,92,262
44,3697,PDL0CKP,92.216,92.200,LK,16,2,17.3,8.0,1.4,7.2,0.7,276.8,92,216,92,200
45,3698,CKP0CD,92.203,92.222,LK,20,2,31.3,5.2,14.9,10.5,0.7,626.0,92,203,92,222
46,3699,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133
47,3700,CKP0CD,92.200,92.203,LK,4,2,22.2,1.2,11.5,9.4,0.1,88.8,92,200,92,203
48,3701,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98
49,3702,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0
50,3703,PDL0CKP,92.000,91.948,LK,52,2,14.4,4.7,4.7,4.2,0.8,748.8,92,0,91,948
51,3704,CKP0CD,92.000,92.200,LK,200,2,23.8,7.2,9.4,6.5,0.6,4760.0,92,0,92,200

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1696,PDL0CKP,92.923,92.800,LRS,124,2,15.0,4.1,2.6,8.1,0.3,1860.0,92,923,92,800
1,2,1698,PDL0CKP,92.800,92.615,LRS,185,2,23.0,6.8,6.3,9.5,0.4,4255.0,92,800,92,615
2,4,1700,PDL0CKP,92.615,92.600,LK,16,2,36.6,11.3,18.5,6.7,0.0,585.6,92,615,92,600
3,5,1701,PDL0CKP,92.600,92.400,LK,200,2,23.7,8.4,8.3,6.5,0.6,4740.0,92,600,92,400
4,9,1705,PDL0CKP,92.400,92.300,LK,100,2,26.4,11.4,10.6,3.9,0.5,2640.0,92,400,92,300
5,13,1709,PDL0CKP,92.300,92.288,JPL,13,2,28.7,6.0,16.8,5.9,0.0,373.1,92,300,92,288
6,14,1710,PDL0CKP,92.288,92.282,LK,6,2,16.3,3.6,7.8,4.9,0.0,97.8,92,288,92,282
7,15,1711,PDL0CKP,92.282,92.216,LK,67,2,23.7,11.6,4.7,6.7,0.7,1587.9,92,282,92,216
8,18,1714,PDL0CKP,92.216,92.200,LK,16,2,17.3,8.0,1.4,7.2,0.7,276.8,92,216,92,200
9,20,1716,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133
10,22,1718,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98
11,23,1719,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0
12,24,1720,PDL0CKP,92.000,91.948,LK,52,2,14.4,4.7,4.7,4.2,0.8,748.8,92,0,91,948
13,26,3679,PDL0CKP,92.923,92.800,LRS,124,2,15.0,4.1,2.6,8.1,0.3,1860.0,92,923,92,800
14,28,3681,PDL0CKP,92.800,92.615,LRS,185,2,23.0,6.8,6.3,9.5,0.4,4255.0,92,800,92,615
15,30,3683,PDL0CKP,92.615,92.600,LK,16,2,36.6,11.3,18.5,6.7,0.0,585.6,92,615,92,600
16,31,3684,PDL0CKP,92.600,92.400,LK,200,2,23.7,8.4,8.3,6.5,0.6,4740.0,92,600,92,400
17,35,3688,PDL0CKP,92.400,92.300,LK,100,2,26.4,11.4,10.6,3.9,0.5,2640.0,92,400,92,300
18,39,3692,PDL0CKP,92.300,92.288,JPL,13,2,28.7,6.0,16.8,5.9,0.0,373.1,92,300,92,288
19,40,3693,PDL0CKP,92.288,92.282,LK,6,2,16.3,3.6,7.8,4.9,0.0,97.8,92,288,92,282
20,41,3694,PDL0CKP,92.282,92.216,LK,67,2,23.7,11.6,4.7,6.7,0.7,1587.9,92,282,92,216
21,44,3697,PDL0CKP,92.216,92.200,LK,16,2,17.3,8.0,1.4,7.2,0.7,276.8,92,216,92,200
22,46,3699,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133
23,48,3701,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98
24,49,3702,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0
25,50,3703,PDL0CKP,92.000,91.948,LK,52,2,14.4,4.7,4.7,4.2,0.8,748.8,92,0,91,948

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em92 = ckp.iloc[1:12].reset_index()
em92 = em92.drop(['index'],axis=1)
em92

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,92.800,92.615,LRS,185,2,23.0,6.8,6.3,9.5,0.4,4255.0,92,800,92,615
1,PDL0CKP,92.615,92.600,LK,16,2,36.6,11.3,18.5,6.7,0.0,585.6,92,615,92,600
2,PDL0CKP,92.600,92.400,LK,200,2,23.7,8.4,8.3,6.5,0.6,4740.0,92,600,92,400
3,PDL0CKP,92.400,92.300,LK,100,2,26.4,11.4,10.6,3.9,0.5,2640.0,92,400,92,300
4,PDL0CKP,92.300,92.288,JPL,13,2,28.7,6.0,16.8,5.9,0.0,373.1,92,300,92,288
5,PDL0CKP,92.288,92.282,LK,6,2,16.3,3.6,7.8,4.9,0.0,97.8,92,288,92,282
6,PDL0CKP,92.282,92.216,LK,67,2,23.7,11.6,4.7,6.7,0.7,1587.9,92,282,92,216
7,PDL0CKP,92.216,92.200,LK,16,2,17.3,8.0,1.4,7.2,0.7,276.8,92,216,92,200
8,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133
9,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98
10,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em92['pertinggian_pjg'] = em92['pertinggian']*em92['panjang']
em92['angkatan_pjg'] = em92['angkatan']*em92['panjang']
em92['lestrengan_pjg'] = em92['lestrengan']*em92['panjang']
em92['lebar_sepur_pjg'] = em92['lebar_sepur']*em92['panjang']

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em92.iloc[0:2] #600-800
em3 = em92.iloc[2:3] #400-600
em2 = em92.iloc[3:8] #200-400
em1 = em92.iloc[8:11] #200
em1

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
8,PDL0CKP,92.200,92.133,LK,67,2,14.3,4.3,4.2,5.3,0.4,958.1,92,200,92,133,288.1,281.4,355.1,26.8
9,PDL0CKP,92.133,92.098,LRS,35,2,14.0,4.6,4.6,4.3,0.5,490.0,92,133,92,98,161.0,161.0,150.5,17.5
10,PDL0CKP,92.098,92.000,LK,99,2,13.7,3.5,4.4,5.1,0.6,1356.3,92,98,92,0,346.5,435.6,504.9,59.4

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 4.39
lestrengan 1: 5.05
lebar sepur 1: 0.52
pertinggian 1: 3.98
angkatan 2: 8.31
lestrengan 2: 5.3
lebar sepur 2: 0.54
pertinggian 2: 10.72
angkatan 3: 8.3
lestrengan 3: 6.5
lebar sepur 3: 0.6
pertinggian 3: 8.4
angkatan 4: 7.31
lestrengan 4: 9.32
lebar sepur 4: 0.37
pertinggian 4: 7.19

In [ ]:
#bikin dataframe baru
em_baru92 ={'KM_Awal':[92.000,92.200,92.400,92.600],
      'KM_Akhir':[92.200,92.400,92.600,92.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em92 = pd.DataFrame(em_baru92)
df_em92

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     92.0      92.2      4.39        5.05         0.52         3.98
1     92.2      92.4      8.31        5.30         0.54        10.72
2     92.4      92.6      8.30        6.50         0.60         8.40
3     92.6      92.8      7.31        9.32         0.37         7.19

## ambil data km 93

In [ ]:
#ambil data dari km 93
km = em.groupby("km1")
ems = km.get_group(93).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1673,PDL0CKP,93.987,93.984,BH,4,2,4.2,0.5,2.4,1.3,0.0,16.8,93,987,93,984
1,1674,PDL0CKP,93.984,93.800,LRS,184,2,24.6,11.0,6.4,6.8,0.4,4526.4,93,984,93,800
2,1675,PDL0CKP,93.800,93.788,LRS,12,2,13.3,8.6,2.2,2.5,0.0,159.6,93,800,93,788
3,1676,CKP0CD,93.800,94.000,LK,200,2,13.7,3.4,4.7,5.6,0.0,2740.0,93,800,94,0
4,1677,PDL0CKP,93.788,93.600,LK,189,2,23.8,7.4,7.3,8.7,0.4,4498.2,93,788,93,600
5,1678,CKP0CD,93.699,93.800,LK,101,2,18.7,3.9,7.4,6.8,0.6,1888.7,93,699,93,800
6,1679,CKP0CD,93.649,93.699,LRS,50,2,13.3,3.3,3.1,6.9,0.0,665.0,93,649,93,699
7,1680,CKP0CD,93.646,93.649,LK,3,2,4.7,1.2,2.1,1.4,0.0,14.1,93,646,93,649
8,1681,CKP0CD,93.607,93.646,LK,39,2,14.5,2.6,4.5,7.0,0.4,565.5,93,607,93,646
9,1682,PDL0CKP,93.600,93.400,LK,200,2,18.8,4.6,3.7,10.1,0.4,3760.0,93,600,93,400
10,1683,CKP0CD,93.600,93.607,LRS,8,2,9.3,3.1,1.8,4.1,0.3,74.4,93,600,93,607
11,1684,PDL0CKP,93.400,93.313,LK,87,2,19.7,3.9,4.4,11.1,0.3,1713.9,93,400,93,313
12,1685,CKP0CD,93.400,93.600,LRS,200,2,14.5,3.6,4.6,5.9,0.4,2900.0,93,400,93,600
13,1686,CKP0CD,93.349,93.400,LK,51,2,14.7,4.1,4.1,6.5,0.0,749.7,93,349,93,400
14,1687,CKP0CD,93.342,93.349,JPL,7,2,28.2,6.1,17.2,4.8,0.0,197.4,93,342,93,349
15,1688,PDL0CKP,93.313,93.305,JPL,8,2,15.8,2.1,2.5,11.2,0.0,126.4,93,313,93,305
16,1689,PDL0CKP,93.305,93.200,LK,106,2,20.1,5.8,5.0,8.8,0.4,2130.6,93,305,93,200
17,1690,CKP0CD,93.260,93.342,LK,83,2,18.7,4.6,6.7,7.5,0.0,1552.1,93,260,93,342
18,1691,CKP0CD,93.251,93.260,BH,9,2,14.6,2.6,2.5,9.5,0.0,131.4,93,251,93,260
19,1692,PDL0CKP,93.200,93.000,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0
20,1693,CKP0CD,93.200,93.251,LK,52,2,16.8,3.3,5.0,8.1,0.4,873.6,93,200,93,251
21,1694,PDL0CKP,93.000,92.923,LK,77,2,27.4,5.2,10.9,10.9,0.4,2109.8,93,0,92,923
22,1695,CKP0CD,93.000,93.200,LK,200,2,20.8,6.1,7.3,6.9,0.6,4160.0,93,0,93,200
23,3656,PDL0CKP,93.987,93.984,BH,4,2,4.2,0.5,2.4,1.3,0.0,16.8,93,987,93,984
24,3657,PDL0CKP,93.984,93.800,LRS,184,2,24.6,11.0,6.4,6.8,0.4,4526.4,93,984,93,800
25,3658,PDL0CKP,93.800,93.788,LRS,12,2,13.3,8.6,2.2,2.5,0.0,159.6,93,800,93,788
26,3659,CKP0CD,93.800,94.000,LK,200,2,13.7,3.4,4.7,5.6,0.0,2740.0,93,800,94,0
27,3660,PDL0CKP,93.788,93.600,LK,189,2,23.8,7.4,7.3,8.7,0.4,4498.2,93,788,93,600
28,3661,CKP0CD,93.699,93.800,LK,101,2,18.7,3.9,7.4,6.8,0.6,1888.7,93,699,93,800
29,3662,CKP0CD,93.649,93.699,LRS,50,2,13.3,3.3,3.1,6.9,0.0,665.0,93,649,93,699
30,3663,CKP0CD,93.646,93.649,LK,3,2,4.7,1.2,2.1,1.4,0.0,14.1,93,646,93,649
31,3664,CKP0CD,93.607,93.646,LK,39,2,14.5,2.6,4.5,7.0,0.4,565.5,93,607,93,646
32,3665,PDL0CKP,93.600,93.400,LK,200,2,18.8,4.6,3.7,10.1,0.4,3760.0,93,600,93,400
33,3666,CKP0CD,93.600,93.607,LRS,8,2,9.3,3.1,1.8,4.1,0.3,74.4,93,600,93,607
34,3667,PDL0CKP,93.400,93.313,LK,87,2,19.7,3.9,4.4,11.1,0.3,1713.9,93,400,93,313
35,3668,CKP0CD,93.400,93.600,LRS,200,2,14.5,3.6,4.6,5.9,0.4,2900.0,93,400,93,600
36,3669,CKP0CD,93.349,93.400,LK,51,2,14.7,4.1,4.1,6.5,0.0,749.7,93,349,93,400
37,3670,CKP0CD,93.342,93.349,JPL,7,2,28.2,6.1,17.2,4.8,0.0,197.4,93,342,93,349
38,3671,PDL0CKP,93.313,93.305,JPL,8,2,15.8,2.1,2.5,11.2,0.0,126.4,93,313,93,305
39,3672,PDL0CKP,93.305,93.200,LK,106,2,20.1,5.8,5.0,8.8,0.4,2130.6,93,305,93,200
40,3673,CKP0CD,93.260,93.342,LK,83,2,18.7,4.6,6.7,7.5,0.0,1552.1,93,260,93,342
41,3674,CKP0CD,93.251,93.260,BH,9,2,14.6,2.6,2.5,9.5,0.0,131.4,93,251,93,260
42,3675,PDL0CKP,93.200,93.000,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0
43,3676,CKP0CD,93.200,93.251,LK,52,2,16.8,3.3,5.0,8.1,0.4,873.6,93,200,93,251
44,3677,PDL0CKP,93.000,92.923,LK,77,2,27.4,5.2,10.9,10.9,0.4,2109.8,93,0,92,923
45,3678,CKP0CD,93.000,93.200,LK,200,2,20.8,6.1,7.3,6.9,0.6,4160.0,93,0,93,200

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,0,1673,PDL0CKP,93.987,93.984,BH,4,2,4.2,0.5,2.4,1.3,0.0,16.8,93,987,93,984
1,1,1674,PDL0CKP,93.984,93.800,LRS,184,2,24.6,11.0,6.4,6.8,0.4,4526.4,93,984,93,800
2,2,1675,PDL0CKP,93.800,93.788,LRS,12,2,13.3,8.6,2.2,2.5,0.0,159.6,93,800,93,788
3,4,1677,PDL0CKP,93.788,93.600,LK,189,2,23.8,7.4,7.3,8.7,0.4,4498.2,93,788,93,600
4,9,1682,PDL0CKP,93.600,93.400,LK,200,2,18.8,4.6,3.7,10.1,0.4,3760.0,93,600,93,400
5,11,1684,PDL0CKP,93.400,93.313,LK,87,2,19.7,3.9,4.4,11.1,0.3,1713.9,93,400,93,313
6,15,1688,PDL0CKP,93.313,93.305,JPL,8,2,15.8,2.1,2.5,11.2,0.0,126.4,93,313,93,305
7,16,1689,PDL0CKP,93.305,93.200,LK,106,2,20.1,5.8,5.0,8.8,0.4,2130.6,93,305,93,200
8,19,1692,PDL0CKP,93.200,93.000,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0
9,21,1694,PDL0CKP,93.000,92.923,LK,77,2,27.4,5.2,10.9,10.9,0.4,2109.8,93,0,92,923
10,23,3656,PDL0CKP,93.987,93.984,BH,4,2,4.2,0.5,2.4,1.3,0.0,16.8,93,987,93,984
11,24,3657,PDL0CKP,93.984,93.800,LRS,184,2,24.6,11.0,6.4,6.8,0.4,4526.4,93,984,93,800
12,25,3658,PDL0CKP,93.800,93.788,LRS,12,2,13.3,8.6,2.2,2.5,0.0,159.6,93,800,93,788
13,27,3660,PDL0CKP,93.788,93.600,LK,189,2,23.8,7.4,7.3,8.7,0.4,4498.2,93,788,93,600
14,32,3665,PDL0CKP,93.600,93.400,LK,200,2,18.8,4.6,3.7,10.1,0.4,3760.0,93,600,93,400
15,34,3667,PDL0CKP,93.400,93.313,LK,87,2,19.7,3.9,4.4,11.1,0.3,1713.9,93,400,93,313
16,38,3671,PDL0CKP,93.313,93.305,JPL,8,2,15.8,2.1,2.5,11.2,0.0,126.4,93,313,93,305
17,39,3672,PDL0CKP,93.305,93.200,LK,106,2,20.1,5.8,5.0,8.8,0.4,2130.6,93,305,93,200
18,42,3675,PDL0CKP,93.200,93.000,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0
19,44,3677,PDL0CKP,93.000,92.923,LK,77,2,27.4,5.2,10.9,10.9,0.4,2109.8,93,0,92,923

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em93 = ckp.iloc[2:9].reset_index()
em93 = em93.drop(['index'],axis=1)
em93

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,93.800,93.788,LRS,12,2,13.3,8.6,2.2,2.5,0.0,159.6,93,800,93,788
1,PDL0CKP,93.788,93.600,LK,189,2,23.8,7.4,7.3,8.7,0.4,4498.2,93,788,93,600
2,PDL0CKP,93.600,93.400,LK,200,2,18.8,4.6,3.7,10.1,0.4,3760.0,93,600,93,400
3,PDL0CKP,93.400,93.313,LK,87,2,19.7,3.9,4.4,11.1,0.3,1713.9,93,400,93,313
4,PDL0CKP,93.313,93.305,JPL,8,2,15.8,2.1,2.5,11.2,0.0,126.4,93,313,93,305
5,PDL0CKP,93.305,93.200,LK,106,2,20.1,5.8,5.0,8.8,0.4,2130.6,93,305,93,200
6,PDL0CKP,93.200,93.000,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em93['pertinggian_pjg'] = em93['pertinggian']*em93['panjang']
em93['angkatan_pjg'] = em93['angkatan']*em93['panjang']
em93['lestrengan_pjg'] = em93['lestrengan']*em93['panjang']
em93['lebar_sepur_pjg'] = em93['lebar_sepur']*em93['panjang']

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em93.iloc[0:2] #600-800
em3 = em93.iloc[2:3] #400-600
em2 = em93.iloc[3:6] #200-400
em1 = em93.iloc[6:7] #200
em1

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
6,PDL0CKP,93.2,93.0,LK,200,2,23.7,6.3,6.7,10.1,0.6,4740.0,93,200,93,0,1260.0,1340.0,2020.0,120.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 6.7
lestrengan 1: 10.1
lebar sepur 1: 0.6
pertinggian 1: 6.3
angkatan 2: 4.66
lestrengan 2: 9.94
lebar sepur 2: 0.34
pertinggian 2: 4.85
angkatan 3: 3.7
lestrengan 3: 10.1
lebar sepur 3: 0.4
pertinggian 3: 4.6
angkatan 4: 7.03
lestrengan 4: 8.37
lebar sepur 4: 0.38
pertinggian 4: 7.51

In [ ]:
#bikin dataframe baru
em_baru93 ={'KM_Awal':[93.000,93.200,93.400,93.600],
      'KM_Akhir':[93.200,93.400,93.600,93.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em93 = pd.DataFrame(em_baru93)
df_em93

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     93.0      93.2      6.70       10.10         0.60         6.30
1     93.2      93.4      4.66        9.94         0.34         4.85
2     93.4      93.6      3.70       10.10         0.40         4.60
3     93.6      93.8      7.03        8.37         0.38         7.51

## ambil data km 94

In [ ]:
#ambil data dari km 94
km = em.groupby("km1")
ems = km.get_group(94).reset_index()
ems

,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,1648,CKP0CD,94.924,95.000,LK,76,2,17.6,2.9,7.7,6.7,0.3,1337.6,94,924,95,0
1,1649,CKP0CD,94.850,94.924,LRS,75,2,20.6,5.0,10.0,5.2,0.4,1545.0,94,850,94,924
2,1650,CKP0CD,94.845,94.850,JPL,5,2,16.5,3.7,11.1,1.7,0.0,82.5,94,845,94,850
3,1651,PDL0CKP,94.800,94.600,LK,200,2,25.3,9.4,7.1,8.5,0.4,5060.0,94,800,94,600
4,1652,CKP0CD,94.800,94.845,LRS,46,2,15.7,3.8,6.1,5.8,0.0,722.2,94,800,94,845
5,1653,PDL0CKP,94.600,94.400,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400
6,1654,CKP0CD,94.600,94.800,LRS,200,2,15.4,4.0,5.2,5.7,0.5,3080.0,94,600,94,800
7,1655,CKP0CD,94.582,94.600,LRS,18,2,15.9,5.3,5.9,4.0,0.7,286.2,94,582,94,600
8,1656,CKP0CD,94.492,94.582,LK,91,2,20.7,4.9,7.2,8.0,0.5,1883.7,94,492,94,582
9,1657,CKP0CD,94.482,94.492,JPL,10,2,19.4,4.5,9.2,5.5,0.2,194.0,94,482,94,492
10,1658,CKP0CD,94.464,94.482,LK,18,2,17.3,2.7,10.6,3.2,0.8,311.4,94,464,94,482
11,1659,PDL0CKP,94.400,94.200,LK,200,2,25.1,8.0,6.9,9.9,0.4,5020.0,94,400,94,200
12,1660,CKP0CD,94.400,94.464,LRS,65,2,18.0,4.2,8.4,4.8,0.6,1170.0,94,400,94,464
13,1661,CKP0CD,94.300,94.400,LRS,100,2,23.4,7.0,8.7,7.3,0.5,2340.0,94,300,94,400
14,1662,CKP0CD,94.293,94.300,JPL,7,2,29.0,5.3,19.0,4.7,0.0,203.0,94,293,94,300
15,1663,CKP0CD,94.242,94.293,LRS,51,2,16.5,4.7,5.3,6.5,0.0,841.5,94,242,94,293
16,1664,PDL0CKP,94.200,94.075,LK,125,2,21.7,7.0,6.2,8.0,0.5,2712.5,94,200,94,75
17,1665,CKP0CD,94.200,94.242,LK,43,2,12.6,3.9,2.7,6.0,0.0,541.8,94,200,94,242
18,1666,PDL0CKP,94.075,94.013,LRS,62,2,15.8,3.8,5.2,6.3,0.6,979.6,94,75,94,13
19,1667,CKP0CD,94.050,94.200,LK,150,2,16.7,5.1,5.7,5.9,0.0,2505.0,94,50,94,200
20,1668,CKP0CD,94.044,94.050,JPL,6,2,13.0,1.2,10.1,1.6,0.0,78.0,94,44,94,50
21,1669,PDL0CKP,94.013,94.007,JPL,7,2,10.6,4.0,3.8,2.8,0.0,74.2,94,13,94,7
22,1670,PDL0CKP,94.007,94.000,LRS,8,2,30.8,14.4,12.6,3.8,0.0,246.4,94,7,94,0
23,1671,PDL0CKP,94.000,93.987,LRS,13,2,16.2,6.0,8.2,2.0,0.0,210.6,94,0,93,987
24,1672,CKP0CD,94.000,94.044,LK,45,2,14.0,3.3,6.8,3.9,0.0,630.0,94,0,94,44
25,3631,CKP0CD,94.924,95.000,LK,76,2,17.6,2.9,7.7,6.7,0.3,1337.6,94,924,95,0
26,3632,CKP0CD,94.850,94.924,LRS,75,2,20.6,5.0,10.0,5.2,0.4,1545.0,94,850,94,924
27,3633,CKP0CD,94.845,94.850,JPL,5,2,16.5,3.7,11.1,1.7,0.0,82.5,94,845,94,850
28,3634,PDL0CKP,94.800,94.600,LK,200,2,25.3,9.4,7.1,8.5,0.4,5060.0,94,800,94,600
29,3635,CKP0CD,94.800,94.845,LRS,46,2,15.7,3.8,6.1,5.8,0.0,722.2,94,800,94,845
30,3636,PDL0CKP,94.600,94.400,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400
31,3637,CKP0CD,94.600,94.800,LRS,200,2,15.4,4.0,5.2,5.7,0.5,3080.0,94,600,94,800
32,3638,CKP0CD,94.582,94.600,LRS,18,2,15.9,5.3,5.9,4.0,0.7,286.2,94,582,94,600
33,3639,CKP0CD,94.492,94.582,LK,91,2,20.7,4.9,7.2,8.0,0.5,1883.7,94,492,94,582
34,3640,CKP0CD,94.482,94.492,JPL,10,2,19.4,4.5,9.2,5.5,0.2,194.0,94,482,94,492
35,3641,CKP0CD,94.464,94.482,LK,18,2,17.3,2.7,10.6,3.2,0.8,311.4,94,464,94,482
36,3642,PDL0CKP,94.400,94.200,LK,200,2,25.1,8.0,6.9,9.9,0.4,5020.0,94,400,94,200
37,3643,CKP0CD,94.400,94.464,LRS,65,2,18.0,4.2,8.4,4.8,0.6,1170.0,94,400,94,464
38,3644,CKP0CD,94.300,94.400,LRS,100,2,23.4,7.0,8.7,7.3,0.5,2340.0,94,300,94,400
39,3645,CKP0CD,94.293,94.300,JPL,7,2,29.0,5.3,19.0,4.7,0.0,203.0,94,293,94,300
40,3646,CKP0CD,94.242,94.293,LRS,51,2,16.5,4.7,5.3,6.5,0.0,841.5,94,242,94,293
41,3647,PDL0CKP,94.200,94.075,LK,125,2,21.7,7.0,6.2,8.0,0.5,2712.5,94,200,94,75
42,3648,CKP0CD,94.200,94.242,LK,43,2,12.6,3.9,2.7,6.0,0.0,541.8,94,200,94,242
43,3649,PDL0CKP,94.075,94.013,LRS,62,2,15.8,3.8,5.2,6.3,0.6,979.6,94,75,94,13
44,3650,CKP0CD,94.050,94.200,LK,150,2,16.7,5.1,5.7,5.9,0.0,2505.0,94,50,94,200
45,3651,CKP0CD,94.044,94.050,JPL,6,2,13.0,1.2,10.1,1.6,0.0,78.0,94,44,94,50
46,3652,PDL0CKP,94.013,94.007,JPL,7,2,10.6,4.0,3.8,2.8,0.0,74.2,94,13,94,7
47,3653,PDL0CKP,94.007,94.000,LRS,8,2,30.8,14.4,12.6,3.8,0.0,246.4,94,7,94,0
48,3654,PDL0CKP,94.000,93.987,LRS,13,2,16.2,6.0,8.2,2.0,0.0,210.6,94,0,93,987
49,3655,CKP0CD,94.000,94.044,LK,45,2,14.0,3.3,6.8,3.9,0.0,630.0,94,0,94,44

In [ ]:
# ambil data PDL0CKP (Padalarang - cikampek)
antara = ems.groupby("antara")
ckp = antara.get_group('PDL0CKP').reset_index()
ckp

,level_0,index,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,3,1651,PDL0CKP,94.800,94.600,LK,200,2,25.3,9.4,7.1,8.5,0.4,5060.0,94,800,94,600
1,5,1653,PDL0CKP,94.600,94.400,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400
2,11,1659,PDL0CKP,94.400,94.200,LK,200,2,25.1,8.0,6.9,9.9,0.4,5020.0,94,400,94,200
3,16,1664,PDL0CKP,94.200,94.075,LK,125,2,21.7,7.0,6.2,8.0,0.5,2712.5,94,200,94,75
4,18,1666,PDL0CKP,94.075,94.013,LRS,62,2,15.8,3.8,5.2,6.3,0.6,979.6,94,75,94,13
5,21,1669,PDL0CKP,94.013,94.007,JPL,7,2,10.6,4.0,3.8,2.8,0.0,74.2,94,13,94,7
6,22,1670,PDL0CKP,94.007,94.000,LRS,8,2,30.8,14.4,12.6,3.8,0.0,246.4,94,7,94,0
7,23,1671,PDL0CKP,94.000,93.987,LRS,13,2,16.2,6.0,8.2,2.0,0.0,210.6,94,0,93,987
8,28,3634,PDL0CKP,94.800,94.600,LK,200,2,25.3,9.4,7.1,8.5,0.4,5060.0,94,800,94,600
9,30,3636,PDL0CKP,94.600,94.400,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400
10,36,3642,PDL0CKP,94.400,94.200,LK,200,2,25.1,8.0,6.9,9.9,0.4,5020.0,94,400,94,200
11,41,3647,PDL0CKP,94.200,94.075,LK,125,2,21.7,7.0,6.2,8.0,0.5,2712.5,94,200,94,75
12,43,3649,PDL0CKP,94.075,94.013,LRS,62,2,15.8,3.8,5.2,6.3,0.6,979.6,94,75,94,13
13,46,3652,PDL0CKP,94.013,94.007,JPL,7,2,10.6,4.0,3.8,2.8,0.0,74.2,94,13,94,7
14,47,3653,PDL0CKP,94.007,94.000,LRS,8,2,30.8,14.4,12.6,3.8,0.0,246.4,94,7,94,0
15,48,3654,PDL0CKP,94.000,93.987,LRS,13,2,16.2,6.0,8.2,2.0,0.0,210.6,94,0,93,987

In [ ]:
ckp = ckp.drop(['level_0','index'],axis=1)

In [ ]:
em94 = ckp.iloc[:7]
em94

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2
0,PDL0CKP,94.800,94.600,LK,200,2,25.3,9.4,7.1,8.5,0.4,5060.0,94,800,94,600
1,PDL0CKP,94.600,94.400,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400
2,PDL0CKP,94.400,94.200,LK,200,2,25.1,8.0,6.9,9.9,0.4,5020.0,94,400,94,200
3,PDL0CKP,94.200,94.075,LK,125,2,21.7,7.0,6.2,8.0,0.5,2712.5,94,200,94,75
4,PDL0CKP,94.075,94.013,LRS,62,2,15.8,3.8,5.2,6.3,0.6,979.6,94,75,94,13
5,PDL0CKP,94.013,94.007,JPL,7,2,10.6,4.0,3.8,2.8,0.0,74.2,94,13,94,7
6,PDL0CKP,94.007,94.000,LRS,8,2,30.8,14.4,12.6,3.8,0.0,246.4,94,7,94,0

In [ ]:
#bikin kolom baru panjang * std per parameter
em94['pertinggian_pjg'] = em94['pertinggian']*em94['panjang']
em94['angkatan_pjg'] = em94['angkatan']*em94['panjang']
em94['lestrengan_pjg'] = em94['lestrengan']*em94['panjang']
em94['lebar_sepur_pjg'] = em94['lebar_sepur']*em94['panjang']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
# 1 segmen = 200 meter, karena pada data em120 panjangnya belum ada yang 200, maka digabungin
em4 = em94.iloc[0:1] #600-800
em3 = em94.iloc[1:2] #400-600
em2 = em94.iloc[2:3] #200-400
em1 = em94.iloc[3:6] #200
em3

,antara,km_awal,km_akhir,device_type,panjang,kelas,tqi,pertinggian,angkatan,lestrengan,lebar_sepur,tqi_pjg,km1,hm1,km2,hm2,pertinggian_pjg,angkatan_pjg,lestrengan_pjg,lebar_sepur_pjg
1,PDL0CKP,94.6,94.4,LK,200,2,24.6,6.8,7.2,10.2,0.4,4920.0,94,600,94,400,1360.0,1440.0,2040.0,80.0

In [ ]:
#em1
pert1 = round((em1['pertinggian_pjg'].sum())/200,2)
ang1 = round((em1['angkatan_pjg'].sum())/200,2)
lest1 = round((em1['lestrengan_pjg'].sum())/200,2)
leb1 = round((em1['lebar_sepur_pjg'].sum())/200,2)

pert2 = round((em2['pertinggian_pjg'].sum())/200,2)
ang2 = round((em2['angkatan_pjg'].sum())/200,2)
lest2 = round((em2['lestrengan_pjg'].sum())/200,2)
leb2 = round((em2['lebar_sepur_pjg'].sum())/200,2)

pert3 = round((em3['pertinggian_pjg'].sum())/200,2)
ang3 = round((em3['angkatan_pjg'].sum())/200,2)
lest3 = round((em3['lestrengan_pjg'].sum())/200,2)
leb3 = round((em3['lebar_sepur_pjg'].sum())/200,2)

pert4 = round((em4['pertinggian_pjg'].sum())/200,2)
ang4 = round((em4['angkatan_pjg'].sum())/200,2)
lest4 = round((em4['lestrengan_pjg'].sum())/200,2)
leb4 = round((em4['lebar_sepur_pjg'].sum())/200,2)

print('angkatan 1:',ang1)
print('lestrengan 1:',lest1)
print('lebar sepur 1:',leb1)
print('pertinggian 1:',pert1)

print('angkatan 2:',ang2)
print('lestrengan 2:',lest2)
print('lebar sepur 2:',leb2)
print('pertinggian 2:',pert2)

print('angkatan 3:',ang3)
print('lestrengan 3:',lest3)
print('lebar sepur 3:',leb3)
print('pertinggian 3:',pert3)

print('angkatan 4:',ang4)
print('lestrengan 4:',lest4)
print('lebar sepur 4:',leb4)
print('pertinggian 4:',pert4)

angkatan 1: 5.62
lestrengan 1: 7.05
lebar sepur 1: 0.5
pertinggian 1: 5.69
angkatan 2: 6.9
lestrengan 2: 9.9
lebar sepur 2: 0.4
pertinggian 2: 8.0
angkatan 3: 7.2
lestrengan 3: 10.2
lebar sepur 3: 0.4
pertinggian 3: 6.8
angkatan 4: 7.1
lestrengan 4: 8.5
lebar sepur 4: 0.4
pertinggian 4: 9.4

In [ ]:
#bikin dataframe baru
em_baru94 ={'KM_Awal':[94.000,94.200,94.400,94.600],
      'KM_Akhir':[94.200,94.400,94.600,94.800],
      'Angkatan' : [ang1,ang2,ang3,ang4],
      'Lestrengan' : [lest1,lest2,lest3,lest4],
      'Lebar Sepur' : [leb1,leb2,leb3,leb4],
      'Pertinggian' :[pert1,pert2,pert3,pert4]
      }

df_em94 = pd.DataFrame(em_baru94)
df_em94

   KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0     94.0      94.2      5.62        7.05          0.5         5.69
1     94.2      94.4      6.90        9.90          0.4         8.00
2     94.4      94.6      7.20       10.20          0.4         6.80
3     94.6      94.8      7.10        8.50          0.4         9.40

## Menggabungkan data baru em120

In [ ]:
em120_baru = pd.concat([df_em84,df_em85,df_em86,df_em87,df_em88,df_em89,df_em90,df_em91,df_em92,df_em93,df_em94])
em120_baru = em120_baru.reset_index()
em120_baru = em120_baru.drop(['index'],axis=1)
em120_baru

    KM_Awal  KM_Akhir  Angkatan  Lestrengan  Lebar Sepur  Pertinggian
0      84.0      84.2     15.84        8.62         1.33         7.25
1      84.2      84.4     17.91       15.37         0.94        15.70
2      84.4      84.6     15.05        8.07         0.99        16.54
3      84.6      84.8      9.40        5.00         0.91         8.55
4      84.0      84.2     13.08        6.38         0.68        13.68
5      84.2      84.4     14.18        6.35         0.94         7.94
6      84.4      84.6     13.52        5.19         1.52         5.42
7      84.6      84.8      8.34        3.66         1.02         5.52
8      86.0      86.2      4.70        5.30         0.80         4.30
9      86.2      86.4      6.68        5.72         1.23         6.01
10     86.4      86.6      4.59        7.65         0.46         6.41
11     86.6      86.8      4.75        8.89         0.45         4.24
12     87.8      87.6      7.60        4.10         0.20        10.90
13     87.6      87.4      7.10        5.10         0.60         5.80
14     87.4      87.2     11.20        8.50         0.30         9.30
15     87.2      87.0      9.10        9.10         0.50         6.10
16     88.0      88.2      7.83        7.51         0.48         7.80
17     88.2      88.4      7.10        5.00         0.30         6.00
18     88.4      88.6      6.90        6.80         0.40         6.30
19     88.6      88.8      8.55        7.06         0.55         9.75
20     89.0      89.2      7.30        8.50         0.50         6.80
21     89.2      89.4      7.97        8.45         0.00         7.72
22     89.4      89.6      9.12        5.40         0.00        11.09
23     89.6      89.8      8.63        8.74         0.04         8.61
24     90.0      90.2      4.50        8.50         0.50         5.10
25     90.2      90.4      4.35        8.65         0.55         4.77
26     90.4      90.6      7.33        7.16         0.54         6.33
27     90.6      90.8      7.10        9.10         0.43         8.16
28     91.0      91.2      6.53       11.88         0.51         6.24
29     91.2      91.4      7.00        6.72         0.00         6.96
30     91.4      91.6      6.89        7.32         0.27         6.06
31     91.6      91.8     11.02       10.65         0.45         8.02
32     92.0      92.2      4.39        5.05         0.52         3.98
33     92.2      92.4      8.31        5.30         0.54        10.72
34     92.4      92.6      8.30        6.50         0.60         8.40
35     92.6      92.8      7.31        9.32         0.37         7.19
36     93.0      93.2      6.70       10.10         0.60         6.30
37     93.2      93.4      4.66        9.94         0.34         4.85
38     93.4      93.6      3.70       10.10         0.40         4.60
39     93.6      93.8      7.03        8.37         0.38         7.51
40     94.0      94.2      5.62        7.05         0.50         5.69
41     94.2      94.4      6.90        9.90         0.40         8.00
42     94.4      94.6      7.20       10.20         0.40         6.80
43     94.6      94.8      7.10        8.50         0.40         9.40

In [ ]:
em120_baru.to_csv('em120_prepos.csv',index=False)